### ISSUE TITLE
Respect ulimit

### ISSUE THREAD

**Issue by peterbraden** [isaacs/node-glob#116]
I have run into the infamous 'EMFILE, too many open files' error several times while using glob, and while upping the ulimit does mitigate this temporarily, it doesn't really seem to address the problem that glob is opening way too many files at once.

```
 at Object.fs.readdirSync (fs.js:659:18)
    at Glob._readdir (.../node_modules/glob/glob.js:662:20)
    at Glob._process (.../node_modules/glob/glob.js:446:15)
    at Glob.iterator (.../node_modules/glob/glob.js:181:10)
```

Perhaps we can use https://github.com/isaacs/node-graceful-fs?

(more people with this error: https://www.google.ch/search?q=EMFILE%2C+too+many+open+files&oq=EMFILE%2C+too+many+open+files&aqs=chrome..69i57j0l5.262j0j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=EMFILE%2C+too+many+open+files+glob)

**Comment by cletusw** [comment]
These issues are back due to #71
