### ISSUE TITLE
Are file order guaranteed?

### ISSUE THREAD

**Issue by sogko** [isaacs/node-glob#118]
Hi,
I would like to know if file order from globbing a folder (e.g. `./src/**/*`) would always be the same by default?

**Comment by DJviolin** [comment]
```
var glob = require('glob');
glob('*.jpg', { cwd: 'public/portfolio/weddings/', sort: true }, function (err, files) {
  console.log('GLOB RESULT: ' + files);
});
```

If I have a filename pattern of 7image-1.jpg, image-2.jpg, image-3.jpg, ..., image-10.jpg7, than it will return 7GLOB RESULT: image-1.jpg,image-10.jpg,image-11.jpg, ...7

How can I return the correct order?

**Comment by isaacs** [comment]
Files are sorted alphabetically.  So, this is "correct".

You could name files with a `image-01` instead of `image-1`, or write your own sorting function.

**Comment by pmoleri** [comment]
Hi @isaacs,
Sorry to come back to this old thread. The thing is after seeing the comment about `sort:true` I couldn't find any documentation on it, however I found a `nosort` flag.
Is the `sort:true` flag obsolete? Should we expect sorted results by default?
