### ISSUE TITLE
symlinks are not followed since 4.0.6?

### ISSUE THREAD

**Issue by seanmwalker** [isaacs/node-glob#134]
We have been leveraging glob to follow symlinks to list all files within a given path, and that had worked great until Monday when 4.1.0 came out. 

For instance a pattern of '~/myProject/*_/_'  would contain a mixture of folders, files and symlinked folders in the myProjects folder. We see the symlink itself in the list of file paths returned, but none of the child files from the location the symlink is pointing to are shown with the new versions of glob.

It looks like this may be happening on line 370 of glob.js

```
if (lstat.isSymbolicLink()) {
  //console.error('SYMLINK %j', abs)
  self._stat(abs, function (er, stat) {
    return cb(null, stat === 'DIR' ? [] : null)
  })
```

Was this change to stop following symlinks intended, and if so is there an option planned that will re-enable this feature?

**Comment by clintwood** [comment]
@isaacs so the `follow` option in the readme is incorrect?

_Feature Request_: It would be **really great** to be able to override the Bash 4.3 compliance of not following symlinks!  The option is there and it looks like a simple test for that option [here](https://github.com/isaacs/node-glob/blob/master/glob.js#L616) could turn this back on!  Is this a possibility?

**Comment by isaacs** [comment]
@clintwood Yes, in the latest release you can do `{follow: true}` in the options, and it'll happily go along until it gets an ELOOP error from the fs.

**Comment by clintwood** [comment]
Ahh, great, thank you!
