### ISSUE TITLE
Fails when pattern contains '[' char

### ISSUE THREAD

**Issue by felixbillon** [isaacs/node-glob#153]
Hi everybody,

I'm using karma which using node-glob. My karma test run locally but does not run when TFS launch it. The different was the path : 'C:\Build\7\[Dev] - refonte\Myproject\'. In this path glob lib convert '[' in strange char. I don't know why ?

**Comment by isaacs** [comment]
`[` is a magic char in globs, just like regexps.  It'd be looking for:

```
C:\Build\7D - refonte\Myproject\
C:\Build\7e - refonte\Myproject\
C:\Build\7v - refonte\Myproject\
```

Escape the `[` with a `\` char, like `"C:\\Build\\7\\[Dev\\] - refonte\\\Myproject\\\"` in js.

**Comment by sinedied** [comment]
@isaacs Escaping does not work for me :/

I used the regexp in https://github.com/isaacs/node-glob/issues/277 and checked that the path is escaped properly, but it still tries to match it.

I'm on OSX BTW.
