### ISSUE TITLE
Clarify behavior of "*.(xxx|yyy)"

### ISSUE THREAD

**Issue by davidmichaelkarr** [isaacs/node-glob#154]
In reading the "Glob Primer" section, I'm wondering what would be the matching behavior of a pattern like "*.(js|css)". I would expect this would match "*.js" and "*.css", but not "*.jscss" or "*.cssjs". However, nothing is said about the behavior of a "(xxx|yyy)" block WITHOUT a prefix character specifying the cardinality. If my guess about the behavior is correct, then I wonder what is the point of the "@" prefix character anyway, if the default is essentially the same?

**Comment by isaacs** [comment]
`*.(xxx|yyy)` isn't a valid glob pattern.  `(xxx|yyy)` is a regexp, which is equivalent to the `@(xxx|yyy)` glob pattern.

**Comment by isaacs** [comment]
You'd want to do `*.@(xxx|yyy)`

**Comment by isaacs** [comment]
Compare to Bash 4.3

```
$ echo *.@(xxx|yyy)
foo.xxx foo.yyy

$ echo *.(xxx|yyy)
bash: syntax error near unexpected token `('

$ node -p "require('../glob').sync('*.(xxx|yyy)')"
[]

$ node -p "require('../glob').sync('*.@(xxx|yyy)')"
[ 'foo.xxx', 'foo.yyy' ]
```
