### ISSUE TITLE
Trailing slash in pattern is matching files as well

### ISSUE THREAD

**Issue by meyer** [isaacs/node-glob#158]
I’ve encountered a peculiar issue and I’m not sure if it’s a bug.

I’m globbing folders with subfolders using the pattern `*/*/`. I only want to match folders, so I’m using the trailing slash to exclude files (I wish there was a `onlydir` option as well as a `nodir` option). Here’s the strange thing: The subfolder pattern is matching files as well, but when I use the pattern `*/`, no files are matched. I’ve uploaded an example for your perusal.

I’m not sure if this is a `node-glob` issue or a `minimatch` issue, but since I’ve encountered it while using `node-glob`, I put it here.

Using node 0.10.36 and node-glob 4.3.5. node-glob is `g` in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/13781/6052280/c0d5b186-ac85-11e4-9ef7-07e1373853a8.png)

At the moment I’m using a silly workaround to filter out files, but I’d rather have the glob pattern do that for me.

Is this a bug or intended behaviour? I did some issue searching and #49 looks tangentially related, but that was ages ago.

**Comment by isaacs** [comment]
That definitely looks like a bug to me.  It should never match a file with a trailing `/`.

**Comment by meyer** [comment]
Hmm. I’ve done some more digging. Looks like this bug has something to do with options.cwd being set, but not being equal to pwd.

Here’s the test code:

```coffee
glob = require "glob"
globtions = sync: true

process.chdir "/Users/meyer/glob-test"
console.log "PWD: #{process.cwd()}"
console.log "globtions.cwd: #{globtions.cwd}"
console.log "Matches:", glob("*/", globtions), "\n"

globtions.cwd = "/Users/meyer/glob-test"
console.log "PWD: #{process.cwd()}"
console.log "globtions.cwd: #{globtions.cwd}"
console.log "Matches:", glob("*/", globtions), "\n"

process.chdir "../"
console.log "PWD: #{process.cwd()}"
console.log "globtions.cwd: #{globtions.cwd}"
console.log "Matches:", glob("*/", globtions), "\n"
```

Here’s the output:

![image](https://cloud.githubusercontent.com/assets/13781/6055123/d6692726-acad-11e4-9c09-5a7244fb785e.png)

Contents of `~/glob-test`:

```
❯ ls -la ~/glob-test
total 16
drwxr-xr-x   5 meyer  staff   170 Feb  4 20:17 .
drwxr-xr-x+ 77 meyer  staff  2618 Feb  4 22:23 ..
-rw-r--r--@  1 meyer  staff  6148 Feb  4 20:17 .DS_Store
-rw-r--r--   1 meyer  staff     0 Feb  4 20:14 this is a file.txt
drwxr-xr-x   2 meyer  staff    68 Feb  4 20:14 this is a folder
```

Still digging…

**Comment by meyer** [comment]
I found the issue. It’s a multilevel thing. Kind of a cascading bug situation. Pretty simple to fix. I’ll submit a PR with some questions later on today.
