### ISSUE TITLE
Case insensitive search fails to find files

### ISSUE THREAD

**Issue by jmorrisIII** [isaacs/node-glob#161]
I am trying to perform a case insensitive search. An example file name and pattern are below. The search never finds the file with a '.DWG' extension. if I remove the nocase option and change the glob pattern to this "M:/428500/428716*.DWG" it works. What do I need to do to perform this search properly?

```
    // file name =  "M:/428500/428716C1-G.DWG";

    var globPattern = "M:/428500/428716*.dwg";
    glob(globPattern,{nocase:true},function(err,files){
        res.send({success:true, data:files})
    });
```

**Comment by alexeyten** [comment]
Have you seen #123 ?

**Comment by bilalakil** [comment]
Just wanted to raise that I'm having this issue too, and have been able to distill it to a more easily reproducible issue. It's been sitting in StackOverflow for a while: http://stackoverflow.com/q/29447637/1406230

I've had the problem on a Mac or two, across various OSes (considering the time I first posted that question), now on the latest, with glob v7.1.1.

**Comment by isaacs** [comment]
No longer an issue in v9
