### ISSUE TITLE
Directories Only

### ISSUE THREAD

**Issue by bannostookaylo** [isaacs/node-glob#163]
Is there anyway to bring back only an array of directories. I can't seem to find a module that only does an array of directories and sub-directories. This seems really close and almost EXACTLY how I wanted. I saw a post somewhere on google where you could pass in flags... was hoping I could pass the flag GLOB_ONLYDIR lol but that didn't work. Anyway excellent work on this I really appreciate it... thanks! :+1:

**Comment by isaacs** [comment]
Just end the pattern in a `/`.  Example:

```
glob('**/', function (er, dirs) {
  if (er) throw er // or handle or whatever
  console.log('all dirs:', dirs)
})
glob('*/', function (er, dirs) {
  if (er) throw er // or handle or whatever
  console.log('first-level dirs:', dirs)
})
```

**Comment by bannostookaylo** [comment]
BRILLIANT!!! Thank you so much! :+1:
