### ISSUE TITLE
Upgrading from 4.0.5 to 4.4.0

### ISSUE THREAD

**Issue by codydaig** [isaacs/node-glob#167]
When upgrading from 4.0.5 to 4.4.0 I get the following error without changing any code. If I go back to 4.0.5 it starts working again.

/Users/codydaig/Documents/Projects/rmsara.org/node_modules/glob/glob.js:69
      throw new TypeError('callback provided to sync glob')
            ^
TypeError: callback provided to sync glob
    at glob (/Users/codydaig/Documents/Projects/rmsara.org/node_modules/glob/glob.js:69:13)
    at Object.module.exports.getGlobbedFiles (/Users/codydaig/Documents/Projects/rmsara.org/util.js:25:4)
    at Object.<anonymous> (/Users/codydaig/Documents/Projects/rmsara.org/rmsara.org.js:15:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by heikki** [comment]
What does `/Users/codydaig/Documents/Projects/rmsara.org/util.js:25:4` look like i.e. are you using callback with sync glob?

**Comment by codydaig** [comment]
Yes I am. Is that no longer supported?

module.exports.getGlobbedFiles = function(globPatterns, removeRoot) {
	// Initiate the output array
	var output = [];

	// For context switching
	var _this = this;

	// URL paths regex
	var urlRegex = new RegExp('^(?:[a-z]+:)?\/\/', 'i');

	// If glob pattern is array so we use each pattern in a recursive way, otherwise we use glob
	if (_.isArray(globPatterns)) {
		globPatterns.forEach(function(globPattern) {
			output = _.union(output, _this.getGlobbedFiles(globPattern, removeRoot));
		});
	} else if (_.isString(globPatterns)) {
		if (urlRegex.test(globPatterns)) {
			output.push(globPatterns);
		} else {
			glob(globPatterns, { sync: true }, function(err, files) {
				if (removeRoot) {
					files = files.map(function(file) {
						return file.replace(removeRoot, '');
					});
				}
				output = _.union(output, files);
			});
		}
	}

	// return the array of globbed files
	return output;
}

**Comment by codydaig** [comment]
This open source projects uses it: https://github.com/meanjs/mean/blob/master/config/config.js

I've taken that project and reworked it to fit my needs. But when I take that same project and upgrade to 4.4.0 I have the same issue that I am having.

**Comment by heikki** [comment]
Looks like the behaviour has changed. This should do the same without callback:

```js
var files = glob.sync(globPatterns);
if (removeRoot) {
    files = files.map(function(file) {
        return file.replace(removeRoot, '');
    });
}
output = _.union(output, files);
```

https://github.com/isaacs/node-glob#globsyncpattern-options

**Comment by codydaig** [comment]
@heikki Thanks a bunch! That worked perfectly!!

**Comment by isaacs** [comment]
I'll upgrade the error message to provide clearer instructions here.

**Comment by tyagiakhilesh** [comment]
Works like a charm. Thanks guys.
