### ISSUE TITLE
braced sections: forbid to have space before/after comma symbol ?

### ISSUE THREAD

**Issue by ustccjw** [isaacs/node-glob#168]
as title, if so should have a tip, hah
`'*.{styl,css,js,jedi,php,html' ` is always ok, but `'*.{styl, css, js, jedi, php, html' ` does not work well.

**Comment by isaacs** [comment]
Spaces are a valid char to have in a filename, so no, that would mean a different thing.

If you're suggesting that we auto-trim the braced sections, that would be a breaking change and a departure from Bash behavior, so that's not going to happen.
