### ISSUE TITLE
Add support for ignoring EACCES

### ISSUE THREAD

**Issue by sielay** [isaacs/node-glob#169]
I have situation I have to run glob against mounted file system, that has symlinks to other mounted system. One inaccessible path and whole lookup fails.

**Comment by isaacs** [comment]
What version of glob are you using?  When I set up a test to raise EACCES, it just acts as if the files aren't there, because the stats and readdirs fail.

**Comment by sielay** [comment]
I used latest from NPM. But then I figured out I can handle it with `g.continue();`. So you can close this issue. Maybe doc could be more clear on handling crawl errors.

**Comment by isaacs** [comment]
What is `g.continue()`?  Are you sure you're using this module, and not something else?

**Comment by sielay** [comment]
Now I am confused, as I use it ;) (here https://github.com/sielay/roadmarks/blob/master/src/RoadMarks.js#L138) But maybe my test is wrong and it jumps over it. Anyhow I see you have `g.resume` which does the same.
