### ISSUE TITLE
glob does not return the path of a broken directory symlink, even when 'nonull:true' is set

### ISSUE THREAD

**Issue by fourcube** [isaacs/node-glob#170]
Version: `glob 4.4.1`
OS: `Linux devbox 3.16.0-30-generic #40-Ubuntu SMP Mon Jan 12 22:06:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Steps to reproduce:

```bash
cd /tmp
mkdir foo
ln -s foo bar
rm -r foo

npm install glob
```

Run the following code:
```js
glob('bar', {nonull:true}, function (er, res) { 
  console.log(er, res);
});
```
Result: `null []`

```bash
fourcube@devbox:/tmp$ stat bar
  File: ‘bar’ -> ‘foo’
  Size: 3         	Blocks: 0          IO Block: 4096   symbolic link
Device: 801h/2049d	Inode: 65333       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/fourcube)   Gid: ( 1000/fourcube)
Access: 2015-03-04 17:29:34.964707559 +0100
Modify: 2015-03-04 17:29:32.220707646 +0100
Change: 2015-03-04 17:29:32.220707646 +0100
 Birth: -
```

**Comment by fourcube** [comment]
https://github.com/fourcube/node-glob/blob/master/glob.js#L642

```js
if (er) {
    this.statCache[abs] = false
    return cb()
}
```

When a broken symlink is encountered, `er` will be `ENOENT`. Should the error and path be returned when `nonull:true`?

**Comment by isaacs** [comment]
Yeah, it should probably be doing an `lstat` to figure out existence, and then just try to `readdir` to see if it's a directory if it shows up as either a dir or symlink.

Good find!  This is indeed a bug.

**Comment by isaacs** [comment]
I suspect that this is causing isaacs/rimraf#65 and ember-cli/ember-cli#3413.

**Comment by fourcube** [comment]
@isaacs I stumbled over this while running `broccoli serve` with a dependency tree like <plugin>->less-processor->rimraf->glob. Since ember-cli's build pipeline is also based on broccoli, ember-cli/ember-cli#3413 might also be fixed by solving this one.

What happens during `broccoli serve` is this:

1. A symlink is set on a temporary directory by X
2. Processing works as normal
3. ... <some file is changed>
4. Temporay directory is deleted
5. The symlink still exists, but is reported as absent by `glob`
7. `rimraf` does not delete the link
8. X tries to create the link again -> `EEXIST`

**Comment by fourcube** [comment]
Thank you for fixing this issue so quickly!
