### ISSUE TITLE
Has v4.4.1 been removed?

### ISSUE THREAD

**Issue by binarykitchen** [isaacs/node-glob#171]
Suddenly I am getting `Error: version not found: glob@4.4.1` in my deployment builds. Looks like that version has been removed :/

I see no such hint nor warning anywhere.

**Comment by isaacs** [comment]
Yes, this was on purpose.

`rimraf` version 2.3.0 depends on `glob@^4.4.1`, which has a bug that is not present in `glob@4.4.2`.

**Comment by binarykitchen** [comment]
Ah, thanks @isaacs, makes sense.

No idea how npm deals with these situations but is there a chance npm could print a warning/hint on removed versions?

Like that we wouldn't have to wonder why a deployment or build fails and save some minutes.
