### ISSUE TITLE
Allow check if a filename match by glob pattern.

### ISSUE THREAD

**Issue by rentalhost** [isaacs/node-glob#175]
For instance:

    // Very useful.
    glob.match("**/*.less", "myfile.less"); // true
    glob.match("**/*.less", "path/myfile.less"); // true
    glob.match("**/*.less", "path/myfile.js"); // false
    glob.match("**/*.less", "path/myfile.css"); // false

    // Optional 1
    glob.match([ "**/*.js", "**/*.less" ], "myfile.less"); // true
    glob.match([ "**/*.js", "**/*.less" ], "path/myfile.less"); // true
    glob.match([ "**/*.js", "**/*.less" ], "path/myfile.js"); // true
    glob.match([ "**/*.js", "**/*.less" ], "path/myfile.css"); // false

    // Optional 2
    glob.match("**/*.less", [ "file.less", "other/file.less" ]); // return [ "file.less", "other/file.less" ]
    glob.match("**/*.less", [ "file.css", "other/file.less" ]); // return [ "other/file.less" ]
    glob.match("**/*.less", [ "file.css", "other/file.css" ]); // return [] or false

Definition:

    glob.match(string, string): boolean; // First example.
    glob.match(string[], string): boolean; // Optional 1.
    glob.match(string, string[]): string[]; // Optional 2.
    glob.match(string[], string[]): string[]; // Optional 1 and 2 together.

**Comment by isaacs** [comment]
You want minimatch, not this module.
