### ISSUE TITLE
Please Help: Running tests for Windows-specific issues

### ISSUE THREAD

**Issue by isaacs** [isaacs/node-glob#178]
We need a CI and also a dead-simple dev setup for running tests in a windows (or suitably windows-like) environment.

Mocking fs is fine.

This is blocking some much-needed windows fixes.

**Comment by fvictorio** [comment]
Is this still relevant now that there's a GitHub workflow that includes windows?

**Comment by isaacs** [comment]
Hahah yeah, v9 will close a lot of issues.
