### ISSUE TITLE
ignore certain folders

### ISSUE THREAD

**Issue by lfender6445** [isaacs/node-glob#180]
I have a project that looks like this

    ls foo/
    - file0.js
    - a/file1.js
    - b/file2.js
    - c/file3.js
    - d/file4.js

How do I write a [glob pattern][1] to **exclude the c & d folder** but get all other javascript files?

I imagine the solution would look similar to this:

    glob('+(**/*.js|!(c|d))', function(err, file) {
      return console.log(f);
    });

I am wanting back 

    - file0.js
    - a/file1.js
    - b/file2.js

**Comment by isaacs** [comment]
Use the "ignore" feature.

```
glob('**/*.js', { ignore: '{c,d}/**' }, cb)
```

**Comment by lfender6445** [comment]
ahh just found ignore, let me try that

**Comment by isaacs** [comment]
The issue here is that you can't put slashes inside of extglob patterns.  They can only refer to path portions.

**Comment by lfender6445** [comment]
thank you so much for the quick response!
