### ISSUE TITLE
realpath usage fails when options.cwd != process.cwd()

### ISSUE THREAD

**Issue by jldec** [isaacs/node-glob#181]
the result is something like

    Error: ENOENT, lstat '<actual-cwd>/<first-file-in-options.cwd>'

since fs.realpath does path.resolve() on the path, glob needs to pass absolute paths, not just the match results.

from node fs.js:

``` javascript
fs.realpath = function realpath(p, cache, cb) {
  if (typeof cb !== 'function') {
    cb = maybeCallback(cache);
    cache = null;
  }

  // make p is absolute
  p = pathModule.resolve(p);
```

**Comment by isaacs** [comment]
Yep, that's a bug.  Good find!
