### ISSUE TITLE
realpath results different from Glob eventEmitter matches

### ISSUE THREAD

**Issue by jldec** [isaacs/node-glob#184]
realpath results are absolute paths and when there are symlinks to the same directory, de-dup'ing will produce a smaller set of results than the eventEmitter matches.

i'm not sure if the inconsistency with `match` events was intentional -- if it was,  perhaps a mention in readme would be helpful.

otherwise, if you plan to make `match` events consistent with realpath results, it would be helpful, when both `realpath` and `follow` are set, to use realpath matches to avoid symlink cycles during directory traversal. This would help prevent inadvertent long delays in tools like node-inspector when module developers accidentally create cycles with `npm link`.

**Comment by isaacs** [comment]
Doc patch welcome.

The `match` event is the specific thing that matched, as matches are found.  It is not deduplicated in the normal case, and is not yet resolved to a realpath.  If we had to move the `fs.realpath` call up earlier in the process, then this would require some inconvenient refactoring.

**Comment by jldec** [comment]
posted small PR #185 for the readme.

the [node-inspector](https://github.com/node-inspector/node-inspector/pull/586) issue i was working on doesn't require streaming matches from glob a.t.m - but probably as more modules adopt streaming this will resurface.

thanks for implementing the `realpath` and `follow` options!
