### ISSUE TITLE
Usage of Lumpy Space Princess

### ISSUE THREAD

**Issue by rhubarbselleven** [isaacs/node-glob#193]
Confirmed my decision to use this lib :+1:

**Comment by isaacs** [comment]
True story: I saw the title of the email and for a second I was scared this issue was a C&D from Williams St for copyright violation.

**Comment by isaacs** [comment]
(or I guess it'd be Frederator? I'm not sure who owns AT.)

**Comment by rhubarbselleven** [comment]
Haha :D
