### ISSUE TITLE
`opts.ignore` not applied to results emitted by `match`

### ISSUE THREAD

**Issue by jmm** [isaacs/node-glob#194]
Given glob@5.0.5, node v0.10.32, on linux, and the following test case:

```js
var
  glob = require('glob'),
  paths = {basename: 'test.js'},
  opts = {};

paths.in = paths.basename;
opts.ignore = paths.in;
opts.cwd = __dirname;

(new glob.Glob(paths.in, opts))
  .on('match', function (match) {
    console.log('match', match === opts.ignore);
  })
  .on('end', function (matches) {
    console.log('end', matches.length);
  });
```

I expect the output to be:

```
end 0
```

Actual output:

```
match true
end 0
```

**Comment by mlmorg** [comment]
+1

You can get around this today by doing something like:

```js
var glob = require('glob');
var isIgnored = require('glob/common').isIgnored;

var globber = glob.Glob('**/*.js', {ignore: ['foo.js']});
globber.on('match', function onMatch(match) {
  if (isIgnored(globber, match)) {
    return;
  }
  // Do something will paths that are not ignored...
});
```

**Comment by jmm** [comment]
@mlmorg Unfortunately that's no help for my situation: using `gulp.src()`, which uses this under the hood. With that all you can do is pass in `pattern` and `options` and it implements a `match` handler. However, they special-case negated patterns (`!whatever`), so I'm relying on that for now, although it feels pretty hokey since `gulp.src()` is documenting as accepting the same pattern and options input as `node-glob`

**Comment by mik01aj** [comment]
+1.

I do `glob.sync('**/*-test.js', {cwd: '../api', ignore: ['*-integration-test.js']})` and get:
```
[ '__tests__/Mapper-test.js',
  '__tests__/authorization-integration-test.js', <--- WTF?
(...)
  'services/__tests__/s3service-test.js' ]
```

**Comment by isaacs** [comment]
@mik01aj You should use `ignore: ['**/*-integration-test.js']`.  As you've written it, it'll only ignore `*-integration-test.js` files that are not in a sub-directory.

**Comment by isaacs** [comment]
Patch welcome for this.  Probably just need to find the bits where `match` is emitted and call `isIgnored` like @mlmorg is doing in the workaround.  I'll get to it soon-ish if no one else does.  (Note that patches require a test!)

**Comment by jmm** [comment]
Awesome, thanks!

**Comment by isaacs** [comment]
I've noticed that with this module, and a few others, about half the time I say "patch welcome" I end up just writing it later that afternoon...

**Comment by jmm** [comment]
If only you could sense when you were going to say patch welcome a few weeks in advance...

**Comment by mlmorg** [comment]
Thanks @isaacs. Sorry, I was going to take a look at it later tonight but glad you got to it first!
