### ISSUE TITLE
Callback never called for glob of same path after "unusual" filesystem error

### ISSUE THREAD

**Issue by maxg** [isaacs/node-glob#197]
In this example, the second `console.log` never happens:

    var fs = require('fs')
    fs.readdir = function(path, cb) { cb(new Error()) }
    var glob = require('glob')
    glob('*', function(err, files) { console.log('1st callback', err, files) })
    glob('*', function(err, files) { console.log('2nd callback', err, files) })

Problem appears to be that in `strict` mode (the default), when an "unusual" filesystem occurs, `_readdirError` returns without calling the `inflight`-ified callback ([line 568](https://github.com/isaacs/node-glob/blob/7a0d65d7ed11871be6b5a68dc6f15e3f4b3fb93d/glob.js#L568)). On a subsequent search of the same path, `_readdir` adds its callback to the zombie `inflight` request and returns ([line 497](https://github.com/isaacs/node-glob/blob/7a0d65d7ed11871be6b5a68dc6f15e3f4b3fb93d/glob.js#L497)). The callback is never called.

I don't understand the eventemitter/callback wiring well enough to propose a fix.

**Comment by isaacs** [comment]
Thanks for the report!  fixed on 5.0.7

**Comment by maxg** [comment]
Awesome, thanks for the fix.
