### ISSUE TITLE
Negation question

### ISSUE THREAD

**Issue by Avcajaraville** [isaacs/node-glob#201]
On the documentation, this is written :

"The intent for negation would be for a pattern starting with ! to match everything that doesn't match the supplied pattern. However, the implementation is weird, and for the time being, this should be avoided. The behavior is deprecated in version 5, and will be removed entirely in version 6."

So, my question is: if the negation using ! should be avoided, what is the alternative ? What should I use then ?

Thanks !

**Comment by jcrben** [comment]
This is not precisely the same question, but if negation is going away, should the general overview mention it so people get more of a heads-up without reading down into the details? I mean something in the [Glob Patterns section which notes the negation](https://github.com/isaacs/node-glob):
`!(pattern|pattern|pattern) Matches anything that does not match any of the patterns provided.`
