### ISSUE TITLE
Glob pattern for windows directory wildcard

### ISSUE THREAD

**Issue by jmorrisIII** [isaacs/node-glob#203]
I am trying to find files from multiple directories with one glob pattern. For example There are 2 directories with names of L:/05XX14/ and L:/05XX15/. If I use the first 2  patters below I get the files from the individual locations. If I try the last pattern I get nothing. Any Ideas?

```
works           L:/05XX14/*.dwg
works           L:/05XX15/*.dwg

not working       L:/05**/*.dwg
```

**Comment by jvoccia** [comment]
You probably should be using: 
L:/05*/*.dwg 
not:  
L:/05**/*.dwg

A "globstar" (**) should be used alone in a path Like: yyyy/**/*.dwg

**Comment by isaacs** [comment]
@jvoccia Right, but `L:/05**/*.dwg` ought to match the same things as `L:/05*/*.dwg`.  I gather that's the bug.

**Comment by isaacs** [comment]
@jmorrisIII What's the L: drive in this case?  Network share or something?  Does it work in C:?

**Comment by jmorrisIII** [comment]
@isaacs the L: drive is a network drive. I also tried the 'L:/05**/*.dwg' pattern on my C: drive with the following pattern 'C:/globtest/05*/*.dwg' and it does work locally.

**Comment by bruce** [comment]
FWIW, I'm seeing what I think is similar behavior -- or at least cross-drive issues with globbing.

```javascript
> glob.sync('E:/B56F007A.BIN')
[ 'E:/B56F007A.BIN' ]
> glob.sync('E:/B56F007*.BIN')
[]
```

`E:` is an attached mass-storage device.

**Comment by joshvito** [comment]
I have also noticed the same behavior.
I would expect to get matches from `"pre_*.xls"`, but reverted to matching` "*.xls"` and transforming the returned array instead.

**Comment by kosso** [comment]
I had a similar issue matching files on an SD card. Setting the `cwd` option to the drive mount-point/letter fixed it for me.

**Comment by isaacs** [comment]
This is no longer an issue on v9, as drive letter paths are handled properly.
