### ISSUE TITLE
Callback or Promise

### ISSUE THREAD

**Issue by TuckerWhitehouse** [isaacs/node-glob#206]
I saw there was a closed pull request to add a ```glob.promise``` wrapper using Q.
I would like to propose that you make the callback optional, and in the absence of a callback, return a promise (if Promises are available).

The LESS precompiler applies this signature to their ```render``` function.
http://lesscss.org/usage/#programmatic-usage

**Comment by isaacs** [comment]
I'd rather not.

Most promise libs have easy shorthands for promise-ifying a callback-taking function.  I'd rather let node-glob focus on globbing, and stick to the simplest possible API pattern for asynchrony: a function.

**Comment by TuckerWhitehouse** [comment]
Understandable, thanks for the great library.
