### ISSUE TITLE
multiple invoke async glob at the same time fails

### ISSUE THREAD

**Issue by viclm** [isaacs/node-glob#209]
The situation when load multipe files at the same time, and each file is concated from one or more files on the disk, I use the async glob, it fails. It seems the function may be confused by multiple invoking,  for example, glob(A) may get the result of B.Of cause the glob.sync works, but I still hope to use the async one

**Comment by isaacs** [comment]
Can you provide a simple test script that demonstrates what you're seeing?

Explaining in english < explaining in JavaScript ;)
