### ISSUE TITLE
Access to the users "HOME" directory ('~' analogue)

### ISSUE THREAD

**Issue by jacobdr** [isaacs/node-glob#210]
Definitely more of an enhancement than an issue, and maybe I am just missing it in the docs, but it seems like a fairly common use case in the shell to the use the `~` expansion. I think it can be accessed in a fairly platform agnostic way using "process.env.HOME" but would be nice syntactic sugar to have the package expand `~`  to it.

**Comment by isaacs** [comment]
I've put off adding `~` support until Node has cross-platform passwd functions (coming to io.js soon, I believe?)  Then we can do stuff like `~root/foo` and `~bob/bar` and have it expand with the home dir of the specified user.

**Comment by jacobdr** [comment]
Sounds good. Thanks for the response. You might want to consider adding a
note of future (but not present) support into the README. I have seen some
package developers try to use it before -- incorrectly -- thinking they
have full shell support. Such a line might stop a few from a careless
mistake.

**Comment by fenwick67** [comment]
Node now supports [`os.homedir`](https://nodejs.org/api/os.html#os_os_homedir) as of v2.3 according to the docs.  Would you accept a PR to add this?

**Comment by isaacs** [comment]
@fenwick67 Is there any way to get the home directory of someone other than the current user?  (Ie, resolve something like `~root/foo` to `/root/foo` and resolve `~user/foo` to `/home/user/foo`, etc?)

**Comment by hhamilto** [comment]
As of node v6.0.0 we have [`os.userInfo([options])`](https://nodejs.org/api/os.html#os_os_userinfo_options). That method returns an object that includes the users `homedir`.

Is there a minimum version of node that node-glob targets support for?

@fenwick67 are you still interested in doing the PR?

**Comment by hhamilto** [comment]
Update: My mistake: `os.userInfo` still only returns the home directory of the current effective user.

**Comment by isaacs** [comment]
It's been 8 years, and Node doesn't have this feature, so I'm thinking it's best to just close this issue.
