### ISSUE TITLE
npm pack not working on glob

### ISSUE THREAD

**Issue by jm00121542** [isaacs/node-glob#211]
Hi, 
npm pack is failing as it tries to run benchclean. benchclean.js is not present in the glob module. There is a reference of benchlean.js in scripts in package.json.
I have downloaded module using following command.
npm install glob

If i remove scripts from package.json then npm pack works fine. 
What will be the impact of not using scripts?

Thanks,
Jaspreet

**Comment by isaacs** [comment]
fixed on latest release
