### ISSUE TITLE
`dir/**` matches `dir`

### ISSUE THREAD

**Issue by UltCombo** [isaacs/node-glob#213]
A lone globstar in the last path segment currently matches the parent directory. I'm not sure if this is a bug, but it diverges from `find`:

```
➜  glob-test  nodetree .
.
└── dir1
    └── dir1.1

2 directories, 0 files
➜  glob-test  find dir1/** -maxdepth 0
dir1/dir1.1
➜  glob-test  node -p 'require("glob").sync("dir1/**");'
[ 'dir1', 'dir1/dir1.1' ]
```

**Comment by isaacs** [comment]
`find(1)` is not the model that this module matches, but rather the globbing pattern-matching behavior in Bash 4.3.

```
$ mkdir -p dir/subdir/subsub
$ for i in dir/**; do echo $i; done
dir/
dir/subdir
dir/subdir/subsub
```

**Comment by UltCombo** [comment]
Makes sense, thanks for the explanation. :smile:
That behavior seems rather counterintuitive imho, but it is compliant to the bash standard after all.

The output is different when I test your sample in bash 3.2 and in zsh, and I also noticed there are discrepancies regarding `dir/**/*`. I wish there was a real standard for globbing.

**Comment by isaacs** [comment]
Bash 3 didn't have globstar support, so of course it would not do anything special with `**`; it'd be the same as `dir/*/*`.  (You can emulate this behavior by setting `{ noglobstar: true }` in the options object.)

I'm not super familiar with zsh, so I can't speak to how that works.

**Comment by UltCombo** [comment]
Thanks for the info.
FWIW, testing on Zsh 5.0.5, `dir/**` seems to match the same as Bash 3, but `dir/**/*` will do deep matching as expected (but will not match the parent `dir`):

```
$ mkdir -p dir/subdir/subsub
$ for i in dir/**; do echo $i; done
dir/subdir
$ for i in dir/**/*; do echo $i; done
dir/subdir
dir/subdir/subsub
```

**Comment by isaacs** [comment]
@UltCombo It's not doing globstar matching at all, that's why.  You're getting the same results as `dir/*/*`.

You can observe this if you do `mkdir -p dir/a/b/c/d/e/f/g` and see what it matches.

**Comment by UltCombo** [comment]
@isaacs nope, Zsh seems to have its own glob variation:

```
$ mkdir -p dir/a/b/c/d/e/f/g
$ for i in dir/**; do echo $i; done
dir/a
$ repos  for i in dir/**/*; do echo $i; done
dir/a
dir/a/b
dir/a/b/c
dir/a/b/c/d
dir/a/b/c/d/e
dir/a/b/c/d/e/f
dir/a/b/c/d/e/f/g
```

Also, if `dir/**/*` was treated the same as `dir/*/*`, it would not match `dir/subdir` in the [comment above](https://github.com/isaacs/node-glob/issues/213#issuecomment-126111904), right?

**Comment by isaacs** [comment]
Wild!  Yeah, that's totally different.  What does `dir/**/` match?

> Also, if `dir/**/*` was treated the same as `dir/*/*`, it would not match `dir/subdir` in the comment above, right?

Ah, good point.

Anyway, zsh's globbing is not the reference implementation that this module targets :)

**Comment by UltCombo** [comment]
Oh yes, that was just a side note that ended up diverging the topic a bit too much.
I'll update my Bash so I can properly test the globbing before reporting issues.
Thanks for the help and explanations. :smile:

**Comment by UltCombo** [comment]
Oh sorry, I missed your question:

> Wild! Yeah, that's totally different. What does `dir/**/` match?

It matches all directories including the parent (`dir`), exactly like node-glob.

**Comment by iulo** [comment]
what about windows ?  seems like `dir/**` also matches the parent directory

**Comment by UltCombo** [comment]
@iulo That's the expected behavior, I believe. Isaac explained it [above](https://github.com/isaacs/node-glob/issues/213#issuecomment-126047563).
