### ISSUE TITLE
Working with browserify and using bulk-require i'm getting this fs.readdirSync is not a function

### ISSUE THREAD

**Issue by juliancantillo** [isaacs/node-glob#214]
Hi to all,

I'm trying to work with browserify and angularjs but i can't. Inspired from [jakemmarhs/angular-gulp-browserify-boilerplate](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate) but using elixir because my backend is a laravel application.

```javascript
// This file is called _index.js
'use strict';

var angular = require('angular');
var bulk = require('bulk-require');

module.exports = angular.module('app.controllers', []);

bulk(__dirname, ['./**/!(*_index|*.spec).js']);
```

this generates the following error: 

```bash
Uncaught TypeError: fs.readdirSync is not a function
Glob._readdir @ glob.js:662
Glob._process @ glob.js:446
iterator @ glob.js:181
Glob @ glob.js:179
glob @ glob.js:57
globSync @ glob.js:76
(anonymous function) @ index.js:23
module.exports @ index.js:17
(anonymous function) @ _index.js:819
.angular @ _index.js:8
s @ _prelude.js:1
(anonymous function) @ _prelude.js:120
../controllers/_index @ main.js:6
s @ _prelude.js:1
e @ _prelude.js:1
(anonymous function) @ _prelude.js:1
```
This are my current dependencies

```json
    "angular": "^1.4.3",
    "angular-messages": "^1.4.3",
    "angular-ui-router": "^0.2.15",
    "bootstrap-sass": "^3.0.0",
    "brfs": "^1.2.0",
    "browser-sync": "^2.7.6",
    "browserify": "^5.10.0",
    "browserify-istanbul": "^0.2.0",
    "browserify-ngannotate": "^0.1.0",
    "bulk-require": "^0.2.1",
    "bulkify": "^1.1.1",
    "debowerify": "^1.2.0",
    "laravel-elixir": "^2.0.0"
```

I've tested several versions of the libraries, but no matter i do, i'm always getting the same error.

Any idea of what i'm doing wrong?

**Comment by sondreb** [comment]
You need to run additional transforms on the browserify instance. You only need the 'bulkify' transform, and you can see example of it here:

https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserify.js

**Comment by juliancantillo** [comment]
@sondreb going to take a look, thanks.

**Comment by isaacs** [comment]
Not a node-glob issue.
