### ISSUE TITLE
Support multiple patterns

### ISSUE THREAD

**Issue by gajus** [isaacs/node-glob#217]
There are two packages that do more or less the same at the moment:
- https://www.npmjs.com/package/glob
- https://www.npmjs.com/package/globby

If `glob` package were to support multiple patterns like `globby`, then there would be no need for the latter and everyone would be a winner.

**Comment by isaacs** [comment]
A) How would you like the API to look?  (Note that this may involve some trade-offs that turn out to not be too costly.)

B) How does that differ from just using `{,,,}` to break up your patterns?  Eg, instead of doing `glob([pattern1, pattern2], cb)` you could do `glob('{' + pattern1 + ',' + pattern2 + '}', cb)`.  I guess it's different if the patterns have `,` chars in them?  Is there any other reason why this workaround is objectionable?

**Comment by isaacs** [comment]
Especially: if a file matches more than one pattern, should it be included in the results more than once?  And, do you need to know which pattern a file matched?

**Comment by gajus** [comment]
First of all, I was not aware that `glob` package does support multiple paths.

Regarding the different between using `{,,,}` and an array of patterns is that:

* you do not need to worry about escaping when providing an array of patterns
* easier to debug

However, I'd like to suggest that @sindresorhus is made a contributor to this library. You could join the forces and I am sure @sindresorhus would be happy to share his insights given that he is maintaining a very popular branch of your package that supports array syntax.

**Comment by isaacs** [comment]
I took a look at globby.  It seems like it just extends node-glob to take an array of patterns, and uses a Promise for the async API rather than a callback.

Unless this feature gets a champion willing to do the work, I'm not super excited to do it myself, especially since globby already exists.  There are some interesting optimizations that could maybe be taken advantage of (like having the multiple different glob instances share cache objects, for example), but no one's complaining about the speed of globby right now.

**Comment by JPeer264** [comment]
How about adding the following in `Glob()`:

```js
if (Object.prototype.toString.call(pattern) === '[object Array]') {
    pattern = `{${pattern.join(',')}}`;
}
```

Wouldn't this solve this issue?

**Comment by stevenvachon** [comment]
This would be solved by #332.

**Comment by wzup** [comment]
@isaacs 

> do you need to know which pattern a file matched?

Yes, this would be a good advantage. Is it possible to have a result as an object `pattern: match`?

Suppose a pattern is:
```
'?(index|commons|vendors).*.js'
```

So, currently the match is:
```
["commons.6018ac96ba9a08ad3719.js","index.b0f8a1ea8725f3d65633.js"]
```

A preferred match would be:
```
{
    'index/*.*.js': "index.b0f8a1ea8725f3d65633.js",
    'commons/*.*.js': "commons.6018ac96ba9a08ad3719.js",
}
```

And it would be great if the plugin could generate the latter map from this combined pattern:
```
'?(index|commons|vendors).*.js'
```

**Comment by mgadda** [comment]
`{${pattern.join(',')}}`; doesn't quite solve the problem. If `pattern.length == 1`, the result is always empty. I would have expected that the pattern `{foo}` would be the same as `foo`.

**Comment by slavafomin** [comment]
It would definitely be very beneficial to have this feature built-in. I've spent some time today trying to figure out how to specify multiple patterns for it and I couldn't find a way to do this, looking at the documentation. At least you should add a section regarding this directly to the README. And if you are not willing to implement it, just mention the `globby` there. It would save a lot of time for end developers.

**Comment by stevenvachon** [comment]
[fast-glob](https://npmjs.com/fast-glob) is what [globby](https://npmjs.com/globby) depends on. They both support multiple patterns.

**Comment by myuseringithub** [comment]
**Convert pattern JS Array to multiple Glob matching pattern:**

`const convertToMultiplePatternMatching = array => (array.length > 1 ? array.join(',') |> (multiplePatternString => `{${multiplePatternString}}`) : array[0]) // Multiple patterns are represented in globs as `{pattern1, pattern2, pattern3}`
`

And then usage: 
`[
      '**/*.js',
      '**/*.css',
    ] |> convertToMultiplePatternMatching `

**Comment by WORMSS** [comment]
@myuseringithub I've never seen |> used like that. Is there a sneaky trick I am unaware of? I know Typescript isn't a massive fan of it. I was just wondering the purpose?
I ended up having to do the below to make Typescript happy.
```
const convertToMultiplePatternMatching = (array) => array.length > 1 ? `{${array.join(',')}}` : array[0];
```

**Comment by myuseringithub** [comment]
@WORMSS What you wrote is neater. The purpose may be to use a separate function for wrapping a string and separate the stages of manipulating a target value, e.g. `array.join(',') |> wrap('{','}')`

**Comment by WORMSS** [comment]
I was more interested in what `|>` was.. I have since managed to find it. It's an experimental pipe feature that doesn't seem to be implemented in node/typescript/chrome so I had no reference to what it was or how to run it. I will atleast know this for the future.

**Comment by Diokuz** [comment]
So, `glob` does not respect polymorphism, and that is official?)

PS: Have the same problem. Had a big issue with single array item. How I have to write several lines of code to handle this problem. Probably will move to globby.

**Comment by isaacs** [comment]
Implemented on v9
