### ISSUE TITLE
Invalid negate matching

### ISSUE THREAD

**Issue by dangreen** [isaacs/node-glob#231]
```js
glob("./**/*!(.dyn).css", function(err, res) { console.log(err, res) });
```

returns files with `.dyn.css` extension.

**Comment by thirdcreed** [comment]
I think that negation has been fully deprecated.  Use the ignore option instead.

**Comment by isaacs** [comment]
@thirdcreed Only the "negate the whole pattern by prefixing with a !" has been deprecated.  This kind of negation should still work.

@dangreen what does your file tree look like?  What gets returned?

**Comment by isaacs** [comment]
As far as I can tell, this is behaving exactly like bash 4.3

```
[gh:node-glob/master]isaacs@urdva:~/dev/js/glob/a node@v4.0.0
$ tree
.
├── b/
│   ├── c/
│   │   ├── bar.dyn.css
│   │   └── foo.css
│   ├── bar.dyn.css
│   └── foo.css
├── bar.dyn.css
└── foo.css

2 directories, 6 files

[gh:node-glob/master]isaacs@urdva:~/dev/js/glob/a node@v4.0.0
$ for i in ./**/*!(.dyn).css ; do echo $i; done
./b/bar.dyn.css
./b/c/bar.dyn.css
./b/c/foo.css
./b/foo.css
./bar.dyn.css
./foo.css

[gh:node-glob/master]isaacs@urdva:~/dev/js/glob/a node@v4.0.0
$ node -p 'require("../").sync("./**/*!(.dyn).css")'
[ './b/bar.dyn.css',
  './b/c/bar.dyn.css',
  './b/c/foo.css',
  './b/foo.css',
  './bar.dyn.css',
  './foo.css' ]
```

What's happening here is that if you have a file like `foo.dyn.css`, then the `*` matches `fo`, and then `o.dyn` is not equal to `.dyn`, and then the `.css` matches `.css`.

**Comment by isaacs** [comment]
If you do use an `ignore` pattern like @thirdcreed suggests, then it works as you probably want:

```
$ node -p 'require("../").sync("./**/*.css",{ignore:"./**/*.dyn.css"})'
[ './b/c/foo.css', './b/foo.css', './foo.css' ]
```
