### ISSUE TITLE
unable to remove path from filenames

### ISSUE THREAD

**Issue by matt212** [isaacs/node-glob#234]
hi, 

i am getting below as output i want to remove path from files names

output
['E:/older/a.jpg','E:/older/a.jpg']
i want output to be 
['a.jpg','a.jpg']

**Comment by isaacs** [comment]
Without seeing the code, I have no way to know what might need to change.

But the `path.basename()` function probably will do what you want.

**Comment by matt212** [comment]
var drivepath="E";
var myPath= ""+drivepath+":/older/**/*.jpg";


glob(myPath, function (er, files) {

 console.log(files) is below
 //['E:/older/a.jpg','E:/older/a.jpg']
 //  i want output to be 
//['a.jpg','a.jpg']
	
	});
