### ISSUE TITLE
2nd of two glob tests quietly crashes when using mocha

### ISSUE THREAD

**Issue by dwbruhn** [isaacs/node-glob#236]
If I have two asynchronous mocha tests w/ glob, the 2nd one just quietly quits if:
* the 1st test includes `*` in the glob pattern, and
* the 1st test fails

I made a minimal demo here:
https://github.com/dwbruhn/globTest

Not sure if it's a bug in glob or mocha (or my own code)?

**Comment by isaacs** [comment]
No idea, sorry.  Looks like you're using glob right.

Do you have a test that *doesn't* use mocha?  I'm not very familiar with it.

**Comment by dwbruhn** [comment]
Thanks for your quick response! Actually, I think I'm using mocha wrong - my code is throwing an assert exception in an asynchronous callback, which mocha can't reliably catch. Instead, I should [catch the assert exception myself and pass it to done()](https://github.com/dwbruhn/globTest/blob/master/test/test-glob-good.js#L20):


```
try {
    assert(0, 'Forced assert exception'); // if this is commented out, the 2nd test runs fine
} catch (e) {
    return done(e);
}
```
I guess I've just gotten lucky until now!

Interestingly, when I tried the same improper assert handling with [tap](https://github.com/dwbruhn/globTest/blob/master/tapTests/test-glob-tap.js), it gave me a more informative error:

```
Test Glob > Should return list of files 2
  not ok test unfinished: Should return list of files 2
```

**Comment by isaacs** [comment]
Interesting.

If you use [tap](http://npm.im/tap) then it supports throws in async tests.  Just sayin ;)
