### ISSUE TITLE
OS-specificity: case insensitivity on OSX

### ISSUE THREAD

**Issue by Wandalen** [isaacs/node-glob#237]
One more problem:

On Mac:
```
/pro/web/Dave/app/builder/../proto/index/viewer/script/feature/printer/logger/Logger.s -> /pro/web/Dave/app/proto/index/viewer/script/feature/printer/logger/Logger.s 
```   
On Linux:
```
/pro/web/Dave/app/builder/../proto/index/viewer/script/feature/printer/logger/Logger.s -> 
```

By some reason on OSX it is case insensitive.

**Comment by isaacs** [comment]
If the file system is case insensitive, then this module will be case insensitive. There's not much to be done about that, since all the fs functions will play along with the "wrong" case.

**Comment by Wandalen** [comment]
File system on OSX is case sensitive by default. 
Also it significantly decreases area of application if function cant act predictable on most platforms.

Anyway thank you for your contribution into open source. It's great deal.

**Comment by isaacs** [comment]
It is only case preserving in some cases.  In this case, node-glob and bash do the same thing:

```
$ mkdir -p A/B/C
$ echo a/**
a/ a/B a/B/C
$ node -p 'require("./").sync("a/**")'
[ 'a', 'a/B', 'a/B/C' ]
```

However, there IS a discrepancy here:

```
$ echo readme.*
README.md
$ node -p 'require("./").sync("readme.*")'
[]
```

Gonna open a new bug for this.  Thanks for helping to find it :)
