### ISSUE TITLE
Broken minimatch dependency

### ISSUE THREAD

**Issue by lutzh** [isaacs/node-glob#241]
I try to include org.webjars.npm:glob:5.0.15 as a dependency with Ivy, but I get resolution errors.

org.webjars.npm#minimatch;[2,3),[3,4): not found

This seems to be a problem with Ivy not supporting multiple sets of version ranges (in my test this one could be resolved with Maven, but not Ivy). The definition strikes me as odd, though, because 3 is excluded in the first set, included in the second - what is it supposed to mean? Is it not identical to [2,4)? Maven currently takes version 3.0.0 for this (the latest).

**Comment by isaacs** [comment]
I have no idea what to do about this.  I don't manage the webjars repo at all, and that version range syntax is not one I'm familiar with.
