### ISSUE TITLE
** does not match all subdirectories on Ubuntu

### ISSUE THREAD

**Issue by ikrtolica** [isaacs/node-glob#244]
I have the following directory contents:

/app/processor/test/test_images/raw_images/IMG_0001.jpg
/app/processor/test/test_images/raw_images/IMG_0002.jpg
/app/processor/test/test_images/raw_images/IMG_0003.jpg
/app/processor/test/test_images/IMG_0004.jpg
/app/processor/test/test_images/IMG_0005.jpg
/app/processor/test/test_images/IMG_0006.jpg

Calling glob('/app/processor/test/test_images/\*\*/*.jpg', (err, files) =>  { ... }) results in a listing that contains only:

/app/processor/test/test_images/IMG_0004.jpg
/app/processor/test/test_images/IMG_0005.jpg
/app/processor/test/test_images/IMG_0006.jpg

I would expect the files in 'raw_images' to also match when using globstar?

**Comment by Izhaki** [comment]
How did you solve this?
