### ISSUE TITLE
expose the routes using blob

### ISSUE THREAD

**Issue by alfredopacino** [isaacs/node-glob#246]
My routes are exposed this way
```
var routes = require('./routes/index');
var users = require('./routes/users');
var dashboard = require('./routes/dashboard');

app.use('/', routes);
app.use('/users', users);
app.use('/dashboard', dashboard);

```

how can I generalize and include all the routes directory in glob?

**Comment by isaacs** [comment]
I'm not sure what this question is about, but it doesn't seem like it's about this module.

Did you post this issue to the right repo?

**Comment by alfredopacino** [comment]
I think so, I would avoid list explicitly all the routes like I posted, I just want to iterate over the routes directory and execute an app.use() over all the files, I guess I just need the filename without extension to accomplish that

**Comment by isaacs** [comment]
You're almost there.

```javascript
glob.sync('./routes/**/*.js').forEach(function (file) {
  var f = file.replace(/^\.\/routes/, '').replace(/(index)?\.js$/, '')
  app.use(f, require(file))
})
```

Maybe also relevant: https://nodejs.org/api/path.html#path_path_basename_p_ext

**Comment by alfredopacino** [comment]
very thanks! you even take care of the index question :+1: 

do you think it's a good pratice expose the routes automatically like this?

**Comment by isaacs** [comment]
> do you think it's a good pratice expose the routes automatically like this?

I have no opinion on the matter. It's your program, do as you like :)
