### ISSUE TITLE
ignoring absolute paths is platform dependent 

### ISSUE THREAD

**Issue by schnittstabil** [isaacs/node-glob#248]
Having read https://github.com/isaacs/node-glob/issues/189#issuecomment-94215438, I'm not sure how `ignore` should work and what behavior to expect, but I think it should work platform independently.
### Test script

``` js
glob.sync('/build/**', {
    ignore: ['/build', '/build/goat.png']
})
```
### Linux

Files:

``` sh
/build/goat.png
/build/unicorn.png
```

Output:

``` sh
[ '/build/unicorn.png' ]
```
### Windows

Files:

``` sh
C:\build\goat.png
C:\build\unicorn.png
```

Output:

``` sh
[ 'C:/build', 'C:/build/goat.png', 'C:/build/unicorn.png' ]

# with `realpath: true`
[ 'C:\\build', 'C:\\build\\goat.png', 'C:\\build\\unicorn.png' ]

# with `ignore: ['C:/build', 'C:/build/goat.png']`
[ 'C:/build/unicorn.png' ]
```

(same with async…)
Maybe related: #189

**Comment by isaacs** [comment]
Hm. Yeah, that seems like a bug for sure.  `/build/goat.png` would match `c:/build/goat.png` on win32 systems, so that ignore pattern should prevent `c:/build/goat.png` from being returned in the results.

**Comment by isaacs** [comment]
No longer an issue on v9
