### ISSUE TITLE
Options starting with `no-` are forced into boolean false

### ISSUE THREAD

**Issue by r4j4h** [isaacs/node-glob#249]
If I run with

`--ano-instrument-glob **/vendor/** --ano-instrument-glob shared/**`

in the arguments I get

` 'ano-instrument-glob': [ '**/vendor/**', 'shared/**' ] }`

from node-glob, but when I run with 

`--no-instrument-glob **/vendor/** --no-instrument-glob shared/**`

in the arguments I get

`'instrument-glob': false`

from node-glob.

I am not sure if this is intended behavior but I think it should be more clearly documented if so, or made optionable.

I sincerely apologize if this is already documented somewhere, and moreso if it already has an option to toggle the behavior off, but I could not find it.

**Comment by isaacs** [comment]
Sorry, I don't know what `--no-instrument-glob` means.

What program are you running?  Does it use this module?

**Comment by r4j4h** [comment]
Ah mess, I meant to post this under a different project! :x This has nothing to do with node-glob, I accidentally posted here because the example parameter has glob in it. :3

To answer your question, it's an arbitrary parameter that's poorly named. A better example would have been --no-colors to indicate not inserting terminal color characters. Instead of no-colors true, it comes as colors: false. Which is fine, but just unexpected. I believe I meant to post this to substack's minimist.

Sorry for the bother!

**Comment by r4j4h** [comment]
Well, I was going to post and update this with the link but it looks like it's already been discussed as being undocumented but hasn't been merged yet https://github.com/substack/minimist/pull/60 .

Again, sorry to bother!
