### ISSUE TITLE
Inflight complicates runtime, can it be made optional?

### ISSUE THREAD

**Issue by alexk-z** [isaacs/node-glob#250]
The behavior of "inflight" module seems to complicate greatly execution flow with glob, especially when callback could throw error.

What is intended use for it? Can it be made optional? After I disabled "inflight" usage in my private glob.js - all my functional tests are still passing. Maybe I'm missing some race condition? What dragons should I expect if I use version without wrapping callbacks with "inflight"?

Thanks!

===============================================================

The reason why I'm asking:

It caught my attention when stepping through really weird behavior of async mocha tests, which were throwing assertion errors. Glob seems to "leak" inflight callback from previous test and that callback interferes later with other tests. I'm still trying to grasp the details of what exactly happens. Once I remove "inflight" usage from glob.js - behavior is simple and expected.

Aside from test issue - I'm concerned how glob would operate in production environment if something would manage to throw something in the chain of callback. Would Glob keep "inflight" callback for some keys when callback throws? Would that impact runtime going forward if callbacks were leaked from previous Glob usages?

**Comment by alexk-z** [comment]
All Glob tests are passing as well on Ubuntu.

Should I prepare pull request with options parameter, which makes 'inflight' optional? Will it be accepted?

**Comment by isaacs** [comment]
Here's the problem: without using inflight, this module can end up doing a **lot** more syscalls.

Do you have a reduced test case that shows how glob leaks callbacks when a callback throws?

**Comment by alexk-z** [comment]
These are with mocha. First test will hang glob callback for the path '/test/test1*'. Two others will timeout after 2 seconds (standard mocha timeout).

    var glob = require("glob");
    var assert = require("assert");

    describe("GlobInflightMinRepro", function() {

        it("1", function (done) {
            glob("/test/test1*", function(err, fileNames) {
                if (err) {
                    done(err);
                    return;
                }

                assert.equal(fileNames.length, 1, "Unexpected number of files found.");

                done();
            });
        });
    
        it("2", function (done) {

            glob("/test/test1*", function(err, fileNames) {
                if (err) {
                    done(err);
                    return;
                }

                assert.equal(fileNames.length, 1, "Unexpected number of files found.");

                done();
            });
        });

        it("3", function (done) {
            glob("/test/test1*", function(err, fileNames) {
                if (err) {
                    done(err);
                    return;
                }

                assert.equal(fileNames.length, 1, "Unexpected number of files found.");

                done();
            });
        });

    });

**Comment by alexk-z** [comment]
What is the verdict? Should I create PR for providing option to avoid using 'inflight'?

**Comment by phated** [comment]
@isaacs I believe this is fixed with the inflight patch from yesterday

**Comment by isaacs** [comment]
@phated Ah, this is the glob bug you were talking about!  Thanks.

Yes, this should be fixed with the latest `inflight` release.
