### ISSUE TITLE
Is there any AND logical operator?

### ISSUE THREAD

**Issue by inf3rno** [isaacs/node-glob#254]
I am using a library that uses glob for pattern matching, but does not provide any ignore option. I need to exclude `*.exclude.js` from `*.js`. Is this possible?

As far as I understand glob supports only the `OR` and `NOT` logical operators, while this would require something like `AND("*.js", NOT("*.exclude.js"))`.

**Comment by inf3rno** [comment]
Hmm `AND(a, NOT(b))` can be written as `NOT(OR(NOT(a), b))`. I tried with `some/folder/**/!(!(*.js)|(*.exclude.js))`, but this does not work, the result is empty.

**Comment by inf3rno** [comment]
I was able to do this in a simpler way: `some/folder/**/!(*.exclude).js`

**Comment by isaacs** [comment]
```javascript
glob('**/*.js', { exclude: '**/*.exclude.js' }, cb)
```

**Comment by inf3rno** [comment]
@isaacs  

> I am using a library that uses glob for pattern matching, but does not provide any ignore option.

**Comment by isaacs** [comment]
Oh, sorry, I skimmed past that, I guess. Seems like it'd be good if that library let you pass options to glob somehow, then.
