### ISSUE TITLE
Windows tests are broken

### ISSUE THREAD

**Issue by alexk-z** [isaacs/node-glob#256]
test/nocase-nomagic.js ................................ 1/5 2s
  nocase, nomagic
  not ok should be equivalent
    +++ found
    --- wanted
     [
    -  "g:/TMP/A"
    -  "g:/TMP/a"
    -  "g:/tMP/A"
    -  "g:/tMP/a"
    -  "g:/tMp/A"
    -  "g:/tMp/a"
    -  "g:/tmp/A"
    -  "g:/tmp/a"
    +  "G:/TMP/A"
    +  "G:/TMP/a"
    +  "G:/tMP/A"
    +  "G:/tMP/a"
    +  "G:/tMp/A"
    +  "G:/tMp/a"
    +  "G:/tmp/A"
    +  "G:/tmp/a"
     ]
    at:
      line: 98
      column: 7
      file: test/nocase-nomagic.js
    stack: |
      test/nocase-nomagic.js:98:7
      f (node_modules/once/once.js:17:25)
      Glob.<anonymous> (glob.js:9:6041)
      Glob._finish (glob.js:9:8600)
      done (glob.js:9:7740)
      Glob._processReaddir2 (glob.js:9:21305)
      glob.js:9:17744
      RES (node_modules/inflight/inflight.js:23:14)
      f (node_modules/once/once.js:17:25)
      Glob._readdirEntries (glob.js:9:29460)
      glob.js:9:28301
      test/nocase-nomagic.js:62:9
    source: |
      t.same(res.sort(), want)

  nocase, nomagic
  not ok should be equivalent
    +++ found
    --- wanted
     [
    -  "g:/TMP/A"
    -  "g:/TMP/a"
    -  "g:/tMP/A"
    -  "g:/tMP/a"
    -  "g:/tMp/A"
    -  "g:/tMp/a"
    -  "g:/tmp/A"
    -  "g:/tmp/a"
    +  "G:/TMP/A"
    +  "G:/TMP/a"
    +  "G:/tMP/A"
    +  "G:/tMP/a"
    +  "G:/tMp/A"
    +  "G:/tMp/a"
    +  "G:/tmp/A"
    +  "G:/tmp/a"
     ]
    at:
      line: 108
      column: 7
      file: test/nocase-nomagic.js
    stack: |
      test/nocase-nomagic.js:108:7
      f (node_modules/once/once.js:17:25)
      Glob.<anonymous> (glob.js:9:6041)
      Glob._finish (glob.js:9:8600)
      done (glob.js:9:7740)
      Glob._processReaddir2 (glob.js:9:21305)
      glob.js:9:17744
      RES (node_modules/inflight/inflight.js:23:14)
      f (node_modules/once/once.js:17:25)
      Glob._readdirEntries (glob.js:9:29460)
      glob.js:9:28301
      test/nocase-nomagic.js:62:9
    source: |
      t.same(res.sort(), want)

  nocase, with some magic
  not ok should be equivalent
    +++ found
    --- wanted
     [
    -  "g:/TMP/A"
    -  "g:/TMP/a"
    -  "g:/tMP/A"
    -  "g:/tMP/a"
    -  "g:/tMp/A"
    -  "g:/tMp/a"
    -  "g:/tmp/A"
    -  "g:/tmp/a"
    +  "G:/TMP/A"
    +  "G:/TMP/a"
    +  "G:/tMP/A"
    +  "G:/tMP/a"
    +  "G:/tMp/A"
    +  "G:/tMp/a"
    +  "G:/tmp/A"
    +  "G:/tmp/a"
     ]
    at:
      line: 134
      column: 7
      file: test/nocase-nomagic.js
    stack: |
      test/nocase-nomagic.js:134:7
      f (node_modules/once/once.js:17:25)
      Glob.<anonymous> (glob.js:9:6041)
      Glob._finish (glob.js:9:8600)
      done (glob.js:9:7740)
      Glob._processReaddir2 (glob.js:9:21305)
      glob.js:9:17744
      RES (node_modules/inflight/inflight.js:23:14)
      f (node_modules/once/once.js:17:25)
      Glob._readdirEntries (glob.js:9:29460)
      glob.js:9:28301
      test/nocase-nomagic.js:62:9
    source: |
      t.same(res.sort(), want)

  nocase, with some magic
  not ok should be equivalent
    +++ found
    --- wanted
     [
    -  "g:/TMP/A"
    -  "g:/TMP/a"
    -  "g:/tMP/A"
    -  "g:/tMP/a"
    -  "g:/tMp/A"
    -  "g:/tMp/a"
    -  "g:/tmp/A"
    -  "g:/tmp/a"
    +  "G:/TMP/A"
    +  "G:/TMP/a"
    +  "G:/tMP/A"
    +  "G:/tMP/a"
    +  "G:/tMp/A"
    +  "G:/tMp/a"
    +  "G:/tmp/A"
    +  "G:/tmp/a"
     ]
    at:
      line: 141
      column: 7
      file: test/nocase-nomagic.js
    stack: |
      test/nocase-nomagic.js:141:7
      f (node_modules/once/once.js:17:25)
      Glob.<anonymous> (glob.js:9:6041)
      Glob._finish (glob.js:9:8600)
      done (glob.js:9:7740)
      Glob._processReaddir2 (glob.js:9:21305)
      glob.js:9:17744
      RES (node_modules/inflight/inflight.js:23:14)
      f (node_modules/once/once.js:17:25)
      Glob._readdirEntries (glob.js:9:29460)
      glob.js:9:28301
      test/nocase-nomagic.js:62:9
    source: |
      t.same(res.sort(), want)

**Comment by phated** [comment]
This seems to no longer be valid.

**Comment by isaacs** [comment]
@phated Thanks!
