### ISSUE TITLE
support function-type options.ignore

### ISSUE THREAD

**Issue by kaelzhang** [isaacs/node-glob#261]
Is it possible for `node-glob` to support `function`-type `options.ignore` ?
## Case

If we want to list all **files** according to the `.gitignore`, and the `.gitignore` file is:

```
node_modules/*
!node_modules/dir-to-be-included/
```

Suppose there are thousands of things inside `node_modules`, we should filter out those useless directories at the certain stage of `glob` and not after `glob`bing, or the matching process of glob will be very slow.

But it is not that easy to use glob pattern to imitate the behavior of gitignore.
## Proposal

``` js
glob('**/*', {
  ignore: function(path){
     return whetherShouldIgnoreByGitignore(path) 
     // Pay attention that gitignore patterns are not glob patterns
  }
}, (err, files) => {
  doThingsWith(files)
})
```

**Comment by kaelzhang** [comment]
If it is ok to do this, I can help with pr.

**Comment by kaelzhang** [comment]
@isaacs May I have any suggestions?

**Comment by isaacs** [comment]
This is a good feature request for v9, but supporting it on v8 was too terrible to consider.
