### ISSUE TITLE
statCache not consistently populated

### ISSUE THREAD

**Issue by Macrofig** [isaacs/node-glob#265]
I created a repository to help illustrate this issue. I would have preferred using something like JSBin but not sure how I would use it to describe this issue. Regardless, the repo is here: https://github.com/Macrofig/glob-test

If I have a pattern, say `/test/**/*.*`, Glob finds and populates the `cache` and `statCache` objects properly.  But if I have a pattern like `/test/**/*.{js,stache}`, some items are not populated in the file. In my case, it seems to be the `stache` files but I am not certain that is the case.

We were previously using version 5.0.3 of Glob and this pattern wasn't an issue. We are updating to version 7.0.4 and experiencing this bug. Specifically, through Karma. We were also updating Karma from 0.12.31 which was using Glob 3.x. The current version of Karma uses 7.x.

Doing some research, it seems like [this PR](https://github.com/isaacs/node-glob/pull/159) introduced this issue but I'm not entirely sure I understand the use case for #158 so I can't be certain what the fix is. I'd love to help with a PR but I would need some guidance.

Thoughts, ideas? Is it maybe my pattern that is incorrect? Thanks!

**Comment by dherges** [comment]
Adjusting the glob pattern may help. An example:

```diff
diff --git a/.angular-cli.json b/.angular-cli.json
index 4b69daf..90d31c6 100644
--- a/.angular-cli.json
+++ b/.angular-cli.json
@@ -66,7 +66,7 @@
         },
         {
           "input": "../../../docs",
-          "glob": "**/*.{jpg,jpeg,png}",
+          "glob": "**/*+.{jpg|jpeg|png}",
           "output": "content/guide"
         }
       ],
```

**Comment by isaacs** [comment]
No longer an issue on v9
