### ISSUE TITLE
Question: working with a large number of files

### ISSUE THREAD

**Issue by alexander-akait** [isaacs/node-glob#270]
I have about 500k files (images), which need compress, i use `node-glob` for search all files and then pass their in `imagemin`, but i got error (memory overflow):

``` shell
<--- Last few GCs --->

   24271 ms: Mark-sweep 1354.9 (1434.9) -> 1354.9 (1434.9) MB, 1567.2 / 1 ms [allocation failure] [GC in old space requested].
   25829 ms: Mark-sweep 1354.9 (1434.9) -> 1354.9 (1434.9) MB, 1558.1 / 1 ms [allocation failure] [GC in old space requested].
   27404 ms: Mark-sweep 1354.9 (1434.9) -> 1354.9 (1434.9) MB, 1575.7 / 1 ms [last resort gc].
   28978 ms: Mark-sweep 1354.9 (1434.9) -> 1354.9 (1434.9) MB, 1573.6 / 1 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2cacb3cc9e59 <JS Object>
    1: inflight [/path/to/node_modules/inflight/inflight.js:~7] [pc=0x1858eddaad79] (this=0x2cacb3ce3fc1 <JS Global Object>,key=0xc9efc90a3f9 <String[137]\: stat\x00/path/to/uploads/2016/06/b5e6e38192ef1ae7279d51b991465f31-700x720.jpg>,cb=0xc9efc90a069 <J...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Aborted
```

The solution to increase the memory consumption is not suitable. Attempts to write code using `pause` and `resume` with event `match` also throw error (memory overflow, see above) after a few `pause` and `resume`. Is it possible to organize the work with so many files? If so then tell me. Perhaps it would be a good idea to give the possibility of batch processing (e.g. number of files or memory settable across options).

**Comment by isaacs** [comment]
Can you provide any more details?  Like, the depth of paths, pattern being used, etc?

I'm sure it's something that could probably be addressed, but a reproducible test case would be the first step.

**Comment by evilebottnawi** [comment]
@isaacs 
deps of path is 0, all images in one directory (500k images).
pattern - `u/**/*.{png,jpg,jpeg,gif,svg,webp}`.
node - 6.2.2, globby - lastest (use `"glob": "^7.0.3"`).

```javascript
globby(input, { // input = 'u/**/*.{png,jpg,jpeg,gif,svg,webp}'
        cwd: opts.cwd,
        nodir: true
    })
        .then((paths) => paths.map((filepath) => {
            // The error occurs before getting here
            const realFilepath = path.resolve(path.join(opts.cwd, filepath));
            const total = paths.length;

            return handleFile(realFilepath, opts)
                .then(
                    () => {
                        counter++;

                        if (!options.quite) {
                            spinner.text = `Done minifying image "${filepath}" (${counter} of ${total})`;
                        }

                        return filepath;
                    }
                );
        }))
```
I try use `node-glob` directly and i get same error. Trouble is not in `globby`.

**Comment by DomVinyard** [comment]
I am also butting up against that. Would it be possible to stream the files directly (as per https://www.npmjs.com/package/native-readdir) rather than rely on fs.readdir?

**Comment by feross** [comment]
I had a user report the same issue on `standard`: https://github.com/feross/standard/issues/746

They have an absolutely insane number of `node_modules/` folders. We're calling:

```js
glob('**/*.js', {
        ignore: [
          '**/*.min.js',
          '**/bundle.js',
          'coverage/**',
          'node_modules/**',
          'vendor/**'
        ],
        nodir: true
      }, callback)
```

And it seems like every single `*.js` file is discovered first (and this usr has a TON of them, including tons in `node_modules/`). Then, the process crashes before the ignoring/filtering can happen.

Is there any way we could make ignoring `node_modules/` happen sooner in the process?

**Comment by isaacs** [comment]
The ignore stuff is no longer an issue in v9, and it does handle large numbers of matches much more efficiently and safely.  See #375 for some additional thoughts on this issue.
