### ISSUE TITLE
Abort killing/freezing other globs?

### ISSUE THREAD

**Issue by Akkuma** [isaacs/node-glob#279]
I have code that looks like this

``` js
function abortGlobs(globs) {
  globs.forEach(g => g.abort());
}

function removeEventListeners(globs) {
  globs.forEach(g => g.removeAllListeners('match'));
}

function createGlobsPromise(patterns, opts) {
  const deferred = Promise.future();
  const globs = patterns.reduce((acc, pattern) => {
    acc.push(new glob.Glob(pattern, opts));
    return acc;
  }, []);

  globs.forEach((g) => {
    g.on('match', (path) => {
      deferred.resolve({globs: globs, path: path});
      removeEventListeners(globs);
      abortGlobs(globs);
    });
  });

  return deferred.promise;
}

//Elsewhere in the code
const glob1Prom = createGlobsPromise(somePatterns, opts);
const glob2Prom = createGlobsPromise(differentPatterns, opts);
```

`glob1Prom` resolves, but `glob2Prom` will never resolve. If I remove `abortGlobs` and switch to `g.abort()` this works, but obviously this isn't aborting all the other globs with related patterns as I only need a single match out of all patterns.

**Comment by phated** [comment]
You probably want to use https://github.com/sindresorhus/globby which does exactly what you are looking for.

**Comment by Akkuma** [comment]
No, I don't want to use Globby, because my implementation knows that the first match is the only possible match and I don't need to keep looking through each file.

**Comment by isaacs** [comment]
This is easily achieved in v9 by using an AbortSignal.

```js
import { globStream } from 'glob'

const getFirstResult = async (patterns, options = {}) => {
  const ac = new AbortController()
  const s = globStream(patterns, { ...options, signal: ac.signal })
  return new Promise((res, rej) =>
    s.once('data', match => {
      res(match)
      ac.abort()
    })
    s.on('error', er => {
      if (!ac.signal.aborted) rej(er)
    })
  })
}
```

Note that in many cases, the specific match you get will be non-deterministic, based on which filesystem call happens to resolve sooner.  For example, if you search for `['a/b/c/*', 'x/y/z/*']`, then it's possible for the second readdir to resolve before the first, resulting in a match in `x/y/z/` rather than a match in `a/b/c/`.
