### ISSUE TITLE
Discussion: emitting absolute paths

### ISSUE THREAD

**Issue by phated** [isaacs/node-glob#292]
In `glob-stream`, we do processing on each glob to resolve it to an absolute path before passing it to a globber.  This allows us to ensure we always have absolute paths emitted by this module.  However, I noticed that absolute paths are already being calculated (generated?) at https://github.com/isaacs/node-glob/blob/master/glob.js#L471

How would you feel about an added option, like `emitAbsolute`, to always emit the absolute path instead of the relative one?

**Comment by isaacs** [comment]
I would accept a PR to add something like this, yes.  Maybe just `absolute: true` as an option.

**Comment by phated** [comment]
Excellent.  I'll dig into it

**Comment by isaacs** [comment]
I think you could basically just `this.emit('match', this._absolute ? abs : e)` in that function, and set `this._absolute = !!options.absolute` in the ctor.  Then tests and docs, and you're done :)
