### ISSUE TITLE
how to close race condition

### ISSUE THREAD

**Issue by sdetweil** [isaacs/node-glob#297]
I am using glob() over a network drive.. pretty sure there will be slowness.. 

if I glob(), then look a the 
if(glob object.found.length >0) , 

I get a error.. 'undefined'.  due to the race.

if I come back a couple seconds later, the results are filled in and all is ok..
is there a way to set an .on() event handler for when the contents are complete or partial?

**Comment by isaacs** [comment]
The object is not filled up synchronously, even on a non-network drive it'll be empty.

Try this:

```js
var g = new glob.Glob(pattern, options)
g.on('end', function (matches) {
  if (g.found.length > 0) { ... whatever ... }
})
```

Or, perhaps simpler:

```
var g = new glob.Glob(pattern, options, function (error, matches) {
  if (error) { ... handle error ... }
  if (g.found.length > 0) { ... whatever ... }
})
```

**Comment by sdetweil** [comment]
thanks..
