### ISSUE TITLE
`options.strict` default value

### ISSUE THREAD

**Issue by schnittstabil** [isaacs/node-glob#298]
As far as I can see, the default value of `strict` is `false`:
[`self.strict = options.strict !== false`](https://github.com/isaacs/node-glob/blob/cea11fea473f18c565a515b0c61c8f194fc23aaa/common.js#L67).

Which sounds sensible to me, btw. However, in the [readme](https://github.com/isaacs/node-glob/tree/cea11fea473f18c565a515b0c61c8f194fc23aaa#options):

> All options are false by default, unless otherwise noted.
> …
> - `strict` When an unusual error is encountered when attempting to read a directory, the process will just continue on in search of other matches. Set the `strict` option to raise an error in these cases.

**Comment by isaacs** [comment]
No longer an issue on v9
