### ISSUE TITLE
Use graceful-fs

### ISSUE THREAD

**Issue by blond** [isaacs/node-glob#299]
Hi!

I know that `graceful-fs` was removed because of monkeypatching (#71).

But since v4 `graceful-fs` this has been fixed:

> Do not monkey-patch the fs module. This module may now be used as a drop-in dep, and users can opt into monkey-patching the fs builtin if their app requires it.
### Why do I need `graceful-fs`?

I'm developing the [tartifacts](https://github.com/blond/tartifacts) package. It uses [glob-stream](https://github.com/gulpjs/glob-stream) to find files by patters.

if run `tartifacts` for project with a large number of files, then `glob` fails (https://github.com/blond/tartifacts/pull/58):

> Error: ENFILE: file table overflow, open

To fix this I have to do strange things using `proxyquire`:

``` js
const globStream = proxyquire('glob-stream', {
    'glob': proxyquire('glob', {
        'fs': require('graceful-fs')
    })
});
```
### Why not call `gracefulFs.gracefulify()` in project?

In most cases, we can do that:

``` js
const realFs = require('fs');

const gracefulFs = require('graceful-fs');
const tartifacts = require('tartifacts');

gracefulFs.gracefulify(realFs);

tartifacts();
```

But `tartifacts` run `glob-stream` in different processes (https://github.com/blond/tartifacts/pull/40).
### Alternatives

if there is another reason for which `glob` can't use `graceful-fs` need to be able change `fs` with options (#280).

**Comment by isaacs** [comment]
Definitely not going to go back to pulling in graceful-fs.  Same answer as https://github.com/isaacs/node-glob/issues/280, add it to PathScurry, and glob will get it for free.
