### ISSUE TITLE
memory leak, how to cleanup glob requests

### ISSUE THREAD

**Issue by sdetweil** [isaacs/node-glob#314]
I have this long running application (days, weeks, months), that is doing file searches under the covers. 

as the results are all presented by callbacks, and the original requesting function has long since exited, 
how do I cleanup the glob object that was used to call the callback, and any buffers etc it held?

**Comment by sdetweil** [comment]
if I put the glob object on a list to process later, is there a way to 

1. find the current glob object from the callback
2. determine if the glob is still active (callback not yet done), from a timer type process working to close the items on the list..

**Comment by isaacs** [comment]
You don't have to do anything special to clean up the memory.  Just remove references to it.

If you put the glob object in a list, you can kill whatever it's currently doing by calling `myGlob.abort()`.  You can see its results by listening for the `end` event.  If you just want to check on it some time later, you can do something like:

```js
var myGlob = new Glob(somePattern)
myGlob.on('end', function () {
  this.done = true
})

// some time later...

if (myGlob.done) {
  console.log('it is done', myGlob.matches)
} else {
  console.log('still working')
}
```
