### ISSUE TITLE
Permission 

### ISSUE THREAD

**Issue by Chiru13** [isaacs/node-glob#315]
I am using the library to create something electron

Here's what I get:

```
matches undefined
glob error { Error: EPERM: operation not permitted, scandir 'C:\Documents and Settings'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'C:\\Documents and Settings' }
```

and sometimes this:

```
matches undefined
glob error { Error: EBUSY: resource busy or locked, scandir 'C:\hiberfil.sys'
    at Error (native)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'scandir',
  path: 'C:\\hiberfil.sys' }
```

What I tried:

```
var html = glob('/**/*.html', function(er, matches) {
    html_detection = 0
    console.log('matches', matches);
  })
```

I also gave the following options to test:

`{ strict: false }`

but it has no impact on the result, either way it gives me an error of either BUSY or CAN'T READ and I need to be able to see if a file exists or not, not necessarily grab its contents.

All I want is to search for all .html files in the whole of the user's computer (including all drives), and for every user.

**Comment by Chiru13** [comment]
After doing some research I found out that I will need to give Node.JS the permission but I cannot find tutorials on how to do this (but I am not 100% sure if this is the cause of the problem either), I tried giving CMD and Git Bash Admin permissions this doesn't solve the problem tho.

**Comment by danelkhen** [comment]
+1
Is there no option to 'try/catch' / ignore errors / skip errors in glob?

**Comment by isaacs** [comment]
No longer an issue on v9
