### ISSUE TITLE
root option is not being used when passed in

### ISSUE THREAD

**Issue by jasonyilkk** [isaacs/node-glob#322]
#### Use Case:
Project Layout:
/src
  - /routes

glob does not using the root in options to search for .js file.
glob.sync('routes/*.js', {
            root: __dirname,
        }).forEach(file => {
            const route = require(path.join(__dirname, file));
            server.route(route);
        });

potenial pitfall 
Common.js: line #205  if (f.charAt(0) === '/') { abs = path.join(self.root, f)
should be: if (root) insetad

**Comment by isaacs** [comment]
Root is entirely different in v9.  (Technically, it's nonexistent in 9.0, but there's a PR open to add it back in 9.1.)
