### ISSUE TITLE
Match numeric range

### ISSUE THREAD

**Issue by ninox92** [isaacs/node-glob#325]
Matching with numbers in a range does not work.

pattern: ```*(*\.stat|*\.foo|*\.[0-9]+)```
case: I have some files with a certain extension that is numeric.

filename_12345-12345_H.000
filename_12345-12345_H.001
filename_12345-12345_H.002

Even testing with only \*\\.[0-9]+ does not seem to give any results.
I was hoping that someone could point me in the right direction.

Possible bug found?
Doens't work:  ```*\.[0-9]+ ```
Doens't work:  ```*\.[0-9]{3,5} ```
works: ```*\.[0-9]*```

**Comment by bitstrider** [comment]
Standard regex patterns are not supported currently, so the quantifiers you're using (`n+`, `n*`, `n{3,5}`) will not work as you expect.

However, there is support for the range pattern `[...]`, which works similar to the one in regex.

To match your numeric file extensions, you can use: `*.[0-9][0-9][0-9]`

**Comment by isaacs** [comment]
Yeah, what @bitstrider said.

Globs are not regular expressions.  Type `man bash` in your terminal, and look for the section on Pattern Matching.
