### ISSUE TITLE
False match for inacessible directories

### ISSUE THREAD

**Issue by stach78** [isaacs/node-glob#327]
It seems glob gives false match if directory is inaccessible. 

If there is a directory in ./test/ that is not accessible (i. e. insufficent privileges), it will be returned as match, even though it doesn't contain matching file. 

For example, if test directory contains:
/test$ ls -la
total 0
drwxrwxr-x. 4 user user 42 Mar 28 10:20 .
drwxrwxr-x. 4 user user 69 Mar 28 10:18 ..
drw-r--r--. 2 root  root  6 Mar 28 10:20 inaccessibledir (empty directory)
drwxrwxr-x. 2 user user 28 Mar 28 10:19 somedir (contains matching file)

`glob.sync("./test/*/some_result.log");` will return following result:

'./test/inaccessibledir/some_result.log',
'./test/somedir/some_result.log'

If we change inaccessibledir permissions with chmod +x, results become correct.

This behavior is the same if we use { nodir: true } option.

**Comment by isaacs** [comment]
Fixed in v9
