### ISSUE TITLE
Cannot receive filenames without complete dir absolute path

### ISSUE THREAD

**Issue by Muzietto** [isaacs/node-glob#333]
After checking all the available options, I seem unable to remove dir absolute names from glob results.
For example: result `/root/mydir/file.txt` should be presented as plainly `file.txt`
Isn't there an option to obtain that?

**Comment by cscalfani** [comment]
There is an option `absolute` that should be defaulted to `false` but it doesn't work.

**Comment by peterthomashorn** [comment]
This is still a problem in version 7.1.3

**Comment by peterthomashorn** [comment]
I just noticed that it apparently depends on the globbing pattern provided.  When specifying a _relative_ pattern without an absolute prefix it works.

**Comment by isaacs** [comment]
The plan for 9.1 is that `absolute:false` will mean "always relative", `absolute:true` will mean "always absolute", and `absolute:undefined` will mean "relative if the pattern is relative, absolute if the pattern is absolute".  (Currently in 9.0, `absolute:false` is handled like `absolute:undefined`.)
