### ISSUE TITLE
Fibrous breaks options.sync check

### ISSUE THREAD

**Issue by gavinaiken** [isaacs/node-glob#340]
The issue is that fibrous adds a `sync` function to `Object.prototype` so when glob creates an empty object for its options, sync is truthy on that new options object. 

```js
> var obj = {};
> console.log(obj.sync);
// undefined
> var fibrous = require('fibrous');
> var obj = {};
> console.log(obj.sync);
// { that: {} }
> var obj = Object.create(null)
> console.log(obj.sync);
// undefined
```

This is really more fibrous's issue than glob's, but there is a simple fix in glob, so I wanted to see if you would be willing to accept a PR for it. e.g. we could change:
```js
if (typeof options === 'function') cb = options, options = {}
```

to:
```js
if (typeof options === 'function') cb = options, options = Object.create(null)
```

Happy to submit a PR if you would consider it...

Also see issue https://github.com/goodeggs/fibrous/issues/41 in fibrous.

**Comment by isaacs** [comment]
No longer relevant in v9.
