### ISSUE TITLE
Glob#abort() is broken

### ISSUE THREAD

**Issue by mysticatea** [isaacs/node-glob#342]
Versions:

- glob 7.1.2
- Node.js both 6.10.3 and 8.0.0

I aborted a Glob instance, then another Glob instance has gotten broken.

**test.js**

```js
const Glob = require("glob").Glob

new Glob("*.js")
    .on("match", () => console.log("match 1"))
    .on("end", () => console.log("end 1"))
    .on("abort", () => console.log("abort 1"))
    .abort()
new Glob("*.js")
    .on("match", () => console.log("match 2"))
    .on("end", () => console.log("end 2"))
    .on("abort", () => console.log("abort 2"))
```

```console
$ node test.js
abort 1
$
```

`"end 2"` is never printed.

----

I guess the cause is at [glob.js#L529-L531](https://github.com/isaacs/node-glob/blob/8fa8d561e08c9eed1d286c6a35be2cd8123b2fb7/glob.js#L529-L531).

```js
  cb = inflight('readdir\0'+abs+'\0'+inGlobStar, cb)
  if (!cb)
    return
```

This is called via `Glob#_processGlobStar` from the `Glob` constructor.
In the second call, the `inflight()` function returns `null`, so the original `cb` is never called. Then 

```js
Glob.prototype._processGlobStar = function (prefix, read, abs, remain, index, inGlobStar, cb) {
  var self = this
  this._readdir(abs, inGlobStar, function (er, entries) {
    self._processGlobStar2(prefix, read, abs, remain, index, inGlobStar, entries, cb)
  })
}
```

The `_processGlobStar2` method is never executed.

**Comment by isaacs** [comment]
This is no longer an issue in v9.  The way to abort a walk is with an AbortSignal, which aborts all walks in the context of a single Glob object.
