### ISSUE TITLE
Option `nocase:true` seems to have no effect on `ignore` patterns

### ISSUE THREAD

**Issue by qbolec** [isaacs/node-glob#343]
Consider this scenario:
```
$ mkdir test
$ mkdir test/BIG
$ touch test/BIG/file.txt
$ node
const gg = require('glob');
undefined
> gg('test/**',{ignore:['test/BIG/**'],nocase:true},(err,x) => console.log(x)),0;
0
> [ 'test' ]

> gg('test/**',{ignore:['test/big/**'],nocase:true},(err,x) => console.log(x)),0;
0
> [ 'test', 'test/BIG', 'test/BIG/file.txt' ]

> gg('TEST/**',{ignore:['test/big/**'],nocase:true},(err,x) => console.log(x)),0;
0
> [ 'test', 'test/BIG', 'test/BIG/file.txt' ]

> gg('TEST/**',{ignore:['test/BIG/**'],nocase:true},(err,x) => console.log(x)),0;
0
> [ 'test' ]
```
I would expect that `nocase:true` is taken into account when processing `ignore:['test/big/**']`.

(The important implication of this problem is that `del(['test','!test/big','!test/big/file.txt'],{nocase:true})` can delete the test/BIG/file.txt on OSX.)

**Comment by zyj1314** [comment]
no  you are not distrion to say what this is ??

**Comment by qbolec** [comment]
I assume, that you want to know what distribution I use:
```
$ uname -a
Darwin Jakubs-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```

**Comment by megamindbrian** [comment]
@meatballhat Can travis run tests suites against multiple platforms?

**Comment by isaacs** [comment]
In v9, the `nocase` option on the glob is also applied to the ignore patterns, and is inferred from the platform.  (Ie, defaults `true` on `darwin` and `win32`, `false` elsewhere.)  So there's no need to set it unless you know that the case sensitivity is not the platform default.  (And setting it differently from the platform can cause some really weird results.)
