### ISSUE TITLE
bug in lib: Hardlinked/symlinked folders disappear in folder tree 

### ISSUE THREAD

**Issue by seanvree** [isaacs/node-glob#347]
REF:  https://github.com/alm-tools/alm/issues/573

OS: windows 10E 1703 x64
NPM: 5.3.0

Issue:
Alm basic function works great. However, I'm trying to use the folder tree to work in a directory outside of the ALM working DIR. So, I create a directory hard link within my ALM working DIR via windows CMD prompt ("mklink /D DIRNAME TARGET"), and ALM sees the root directory and it's subfolders right away, and I can work in it. But if I close the browser and/or stop ALM and relaunch, the folder tree will list the top level working DIR, and it's subfolders to include the hard link root DIR, but the sub DIRs of the hard linked DIRs just won't appear. There's no errors, in the console or the browser.

Any ideas? Am I going about this the wrong way?

**Comment by leram84** [comment]
Just to add on to this, This does not only affect linked directories, I have local files and directories in my root that are not showing up in the folder tree as well. Is this a windows only thing? I don't understand how people are working around this issue. If there is a better way to manage directories, please lmk, im totally willing to rework my library structure around the requirement here if there's something i can do beyond waiting for a fix. Thanks!

**Comment by isaacs** [comment]
I tested this on v9, and can't seem to reproduce it.  It seems like it's no longer relevant?  Happy to re-open if I missed something.
