### ISSUE TITLE
Glob.sync results include files that don't exist

### ISSUE THREAD

**Issue by mitchhentges** [isaacs/node-glob#351]
I've added a reproduce repository [here](https://github.com/mitchhentges/node-glob-returning-file-that-doesnt-exist).

Sometimes, `glob.sync()` will return paths to files that don't actually exist. For example, with the following tree:

```
$ tree -a
.
├── index.js
└── node_modules
    └── @namespace
        └── src-package-a
            └── node_modules
                └── lib-b
                    └── node_modules
                        └── lib-c
                            └── bin
                                └── file.js
```

The glob `'node_modules/**/node_modules/**/node_modules/**/node_modules'` will return  `node_modules/@namespace/src-package-a/node_modules/lib-b/node_modules/lib-c/bin/file.js/node_modules`, which doesn't actually exist.

Node `v6.11.3`, MacOS `10.12.6`

-----

This is because upon a `readdir` error happening, `glob.sync` assumes that a `ENOTDIR` error means that a path points to a file. However, in the case where a path _includes_ a file (e.g. `/etc/passwd/some_directory`, where `passwd` is the file in the middle of the path), `fs.readdir()` will throw `ENOTDIR`, not `ENOENT`.
The solution here is: when catching an `fs.readdir()` error, if it is of type `ENOTDIR`, verify that the result is indeed a real file, and not an invalid path with a file in the middle.

**Comment by jdalton** [comment]
I ran into this issue too 👍

**Comment by jdalton** [comment]
It causes an error to be thrown when using the `realpath: true` option too (since the path doesn't exist)

**Comment by isaacs** [comment]
This is no longer an issue in v9.
