### ISSUE TITLE
[Feature Request] Check if there is any match for the pattern

### ISSUE THREAD

**Issue by felipenmoura** [isaacs/node-glob#356]
All I want is to verify if there is any match for the giving pattern.

For example, I want to know if there is any file matching `scripts/**/*.jsx` in the current tree.
I can use it to get ALL the files matching that pattern, but all I need is to know IF there is ANY file matching that.

I know I could use it normally, but I bet there would be some perf improvement if we could stop looking for matches as soon as the first is found :)

**Comment by felipenmoura** [comment]
Hi.

I'm trying to accomplish this by using the events for match and then, aborting it.
But if it does NOT match any file, it never resolves!
The "end" event is never triggered! Any idea why?

**Comment by isaacs** [comment]
On `match`, you know that at least 1 match exists.  Call `abort()` to stop further processing.  On `end` with an empty set, you know that no matches exist.

Something like this: (not tested)

```js
function anyMatch (pattern, cb) {
  const g = new Glob(pattern)
  let called = false
  const callback = (er, matched) => {
    if (called)
      return
    called = true
    cb(er, matched)
  }
  g.on('error', callback)
  g.on('match', () => {
    callback(null, true)
    g.abort()
  })
  g.on('end', (matches) => callback(null, matches.length !== 0))
}
```

**Comment by isaacs** [comment]
> I think it works like a singleton. Even if I instantiated new different globs, if one aborts, all of them will have aborted=true

Show me a test demonstrating this.  It is not a singleton.  It's an `instanceof Glob`, as the assertion at the top of the function is guaranteeing.

**Comment by felipenmoura** [comment]
I did exactly that.
It was like this:

```
async function thereIsAnyFileMatching (pattern, options = {}) {
  return new Promise((resolve, reject) => {
    let Glob = glob.Glob
    let g = new Glob(pattern, options)
    g.on('match', function(file){
      g.abort() // found
      resolve(true)
    })
    g.on('end', function(){
      resolve(false)
    })
    g.on('error', function(err){
      reject(err)
    })
  })
}
```

Using it like this:

```
await thereIsAnyFileMatching ('**/*.jsx') // resolves true
await thereIsAnyFileMatching ('**/*.foo) // will never trigger the "end" event
await thereIsAnyFileMatching ('**/*.js') // resolves true
```

But if I use it like this:

```
await thereIsAnyFileMatching ('**/*.foo) // resolves false (triggers the "end" event)
await thereIsAnyFileMatching ('**/*.jsx') // resolves true
await thereIsAnyFileMatching ('**/*.js') // resolves true
```

**Comment by isaacs** [comment]
Aborting with abort signals is now the way to do this, and it is much cleaner in v9.
