### ISSUE TITLE
Webpack doesn't seem to bundle

### ISSUE THREAD

**Issue by smitray** [isaacs/node-glob#357]
Hi there,
I'm trying to bundle my code using webpack and I've used glob to find and import all the modules in a loop. I know it's not the best practice but I don't like to manually load each modules in my project. Anyways, my issue is webpack isn't bundling the code.

**Comment by isaacs** [comment]
This isn't something that glob can help you with, I'm afraid.  Webpack can't bundle unless you use string literals to import your deps, becuase it relies on static analysis.
