### ISSUE TITLE
is there any doc for the error objects returned? 

### ISSUE THREAD

**Issue by sdetweil** [isaacs/node-glob#358]
my source volume is on a network mounted drive.. sometimes the server is not up, sometimes it went away, sometimes it doesn't respond.. 

trying to figure out what the errors will be without having to attempt to cause them all..

**Comment by isaacs** [comment]
There are vanishingly few cases where it'll raise an error on v9.  A directory that can't be read is just treated as "not a valid directory to read", but it doesn't break anything.  Files that need to be statted and fail just are excluded, same with realpath.
