### ISSUE TITLE
Return an object

### ISSUE THREAD

**Issue by esaramago** [isaacs/node-glob#362]
I'm using node-glob to create multiple entries in webpack.

Is it possible to return an object like:

{
"fileX": "src/js/fileX.js",
"fileY": "src/js/fileY.js",
"fileZ: ...
}

**Comment by wookieb** [comment]
No. It always returns array. You can convert the array to an object you need via Array.prototype.reduce.

**Comment by isaacs** [comment]
No longer relevant on v9
