### ISSUE TITLE
Circular / cyclic dependency between glob.js and sync.js

### ISSUE THREAD

**Issue by paulocoghi** [isaacs/node-glob#365]
When using glob in a project processed by Rollup, it identifies a circular dependency between `glob.js` and `sync.js`.

This issue is just a note, because we can use glob as it is and it is possible to work around this problem. But I'd like to notify you of that.

**Comment by isaacs** [comment]
This is not a problem.  Why does rollup think it is?

**Comment by masone** [comment]
since #374 is not moving forward - what's the workaround @paulocoghi?

**Comment by paulocoghi** [comment]
@masone , unfortunately I don't remember exactly _but_ I believe the solution was to mark "node-glob" as an external dependency, leaving it on the "dependencies" of your project, instead of the "dev-dependencies"

**Comment by paulocoghi** [comment]
This is sad because one positive consequence of using Rollup is to dedup and bundle all deps in a single independent JS file with zero runtime deps, providing a better experience for the users of your library (lower lib size, lower install time, etc).

Such workarounds, like informing to do not bundle a specific library, undoes part of this benefit.

I don't know if Rollup could be able to solve such problems (circular dep) by itself.

**Comment by kuraga** [comment]
Rollup workarounded it in https://github.com/rollup/plugins/pull/1038 (`@rollup/plugin-commonjs` 22.0.0).

It's a shame to tell `this is not a problem` in a PR which removes needlless code and let us to compile it.

**Comment by Stanzilla** [comment]
> This is not a problem. Why does rollup think it is?

Even though it isn't, would still be nice to get it fixed since it is holding back large parts of the ecosystem that depend on node-glob.

**Comment by leumasme** [comment]
I ended up just switching to `fast-glob`. It has a proper project structure&tests, supports promises and is written in typescript. Seems to be actively maintained.
