### ISSUE TITLE
Glob for DockerFile

### ISSUE THREAD

**Issue by aeos** [isaacs/node-glob#366]
This is coming from the gulp project issue tracker, so my examples are from gulp, but the gulp team says that the glob is handled by node-glob without any modifications.

When using a glob containing a dockerfile (without an extension) the pipe does not execute:

For instance if I run gulp.src("Designer/Models/**/Dockerfile").pipe(...)

It won't execute the next step in the pipe. However if I change the filename in the folder to include an extension and then update the glob:

gulp.src("Designer/Models/**/Dockerfile.d")

it runs just fine. I feel like the glob is thinking the first example is a folder and therefore doesn't run, but then how do I have glob for an extensionless files?

**Comment by isaacs** [comment]
Glob has no problem matching an extensionless file.

I don't know what to tell you?

```
$ mkdir -p foo/bar/baz

$ touch foo/bar/baz/boo

$ touch foo/bar/boo

$ touch foo/boo

$ node
> require('glob').sync('foo/**/boo')
[ 'foo/bar/baz/boo', 'foo/bar/boo', 'foo/boo' ]
```

**Comment by aeos** [comment]
I forgot to mention that I am currently running this on windows which may actually be the source of the issue.

**Comment by isaacs** [comment]
Yep.  Works the same on Windows, always has.

```
> var glob = require('g:\\glob\\glob.js')
undefined
> glob.sync('foo/**/boo')
[ 'foo/bar/baz/boo', 'foo/bar/boo', 'foo/boo' ]
```
