### ISSUE TITLE
How to quote or escape glob argument like PHP's preg_quote()?

### ISSUE THREAD

**Issue by zmorris** [isaacs/node-glob#367]
Apologies if this has already been asked, but I didn't see a built-in way to quote a parameter to glob.

This is needed when the string you're looking for comes from a variable instead of being hardcoded.

Based on:

http://php.net/manual/en/function.preg-quote.php
http://php.net/manual/en/function.glob.php#86425 (which quotes with `[]` instead of `\`)

I ended up making a function to prefix any of the special characters `*+?![]()|@` from:

https://github.com/isaacs/node-glob#glob-primer

with a backslash (`\`) character:

```
function glob_quote(string) {
    const chars = ['*', '+', '?', '!', '{', '}', '[', ']', '(', ')', '|', '@'];

    return string.replace(new RegExp('[' + '\\' + chars.join('\\') + ']', 'g'), function(match) {
        return '\\' + match;
    });
}
```

Here's an examples of usage:

```
glob.sync('*' + glob_quote('*') + '*.js', {
    dot: true
}).forEach(function(file) {
    console.log(file);
});
```

Which might print something like:

```
...
example-file-with-asterisk-*.js
...
```

And this (somewhat contrived) example which uses the glob result for another glob:

```
glob.sync('**/', {
    dot: true
}).forEach(function(directory) {
    // console.log(directory);

    glob.sync(glob_quote(directory) + '/' + '*.js', {
        dot: true
    }).forEach(function(file) {
        console.log(file);
    });
});
```

And might print something like:

```
...
example-directory-with-asterisk-*/something.js
...
```

Note that the contents of the `directory` variable in the callback above end in a `/` because the pattern `**/` ends in a `/`, so the `+ '/' +` I added is superfluous.  But glob collapses runs of `//` into a single `/` so I left the code generic to work with any result.

It would be great to have a `glob.quote()` function like this built into node-glob.  Otherwise I hope this helps someone.

**Comment by isaacs** [comment]
I'd call it `glob.escape()` to match the more common naming convention for this in JavaScript. Patch welcome, should come with tests.

Here's a one-liner:

```ts
const globEscape = (s: string) => s.replace(/[?*+@!()[\]]/g, '\\$&')
```
