### ISSUE TITLE
root option was not work

### ISSUE THREAD

**Issue by jasonChen1982** [isaacs/node-glob#368]
>app
>>demos
>>>studio

>>node_modules
>>>studio

```js
const dirs = glob.sync('**/studio/', {
  root: path.join(cwd, 'demos'),
});
```

but `dirs` will include node_modules/studio

**Comment by vytautas-pranskunas-** [comment]
same issue here!

**Comment by liuweiGL** [comment]
You should replace the pattern starting with `/`:
```ts
const dirs = glob.sync('/**/studio/', {
  root: path.join(cwd, 'demos'),
});
```

or you can use `cwd` option.

---

- cwd The current working directory in which to search. Defaults to process.cwd().
- root The place where patterns starting with / will be mounted onto

**Comment by isaacs** [comment]
https://github.com/isaacs/node-glob/pull/498
