### ISSUE TITLE
Drop support for node 0.10, 0.12 and maybe more?

### ISSUE THREAD

**Issue by jimmywarting** [isaacs/node-glob#376]
I wish you dropped support for eol versions and only targeting LTS version so that you can for example drop inherits and instead use `class Gulp extends EE {}`

as a new Major version update where you also drop all deprecated api (old api surface) code

all test in travis fails due to `update-notifier` using `let`

**Comment by the-spyke** [comment]
And replace callbacks with Promises? 😅
