### ISSUE TITLE
Absolute path on windows doesn't work with { nocase: true }

### ISSUE THREAD

**Issue by denis-isaev** [isaacs/node-glob#378]
With nocase param:
`> node -e "require('glob').glob('C:/111/**/*.{jpg,jpeg,png}', { nocase
: true }, (error, files) => {console.log(error, files)});"`

Result:
`null []`

Without nocase param:
`node -e "require('glob').glob('C:/111/**/*.{jpg,jpeg,png}', {  }, (error, files) => {console.log(error, files)});"`

Result:
`null [ 'C:/258832-original.jpg',
  'C:/258850-original.jpg',
  'C:/258852-original.jpg' ]`

**Comment by ilanc** [comment]
It also breaks if you have other options set - e.g.:
```
const glob = require("glob")
glob.sync(process.cwd()+"/**/*.pdf")
[ 'C:/cloudbank/Dev/spike-pdf/data/supported/NEDBANK_ALL_EMAIL_0/user1/20170829_5866.pdf',
  'C:/cloudbank/Dev/spike-pdf/data/supported/NEDBANK_ALL_EMAIL_0/user1/20171002_5866.pdf',
  'C:/cloudbank/Dev/spike-pdf/data/supported/NEDBANK_ALL_EMAIL_0/user1/20171028_5866.pdf',
  'C:/cloudbank/Dev/spike-pdf/data/supported/NEDBANK_ALL_EMAIL_0/user2/10. BS(CA) NovDec\'16.pdf' ]
> glob.sync(process.cwd()+"/**/*.pdf", { nocase: true })
[]
> glob.sync(process.cwd()+"/*.pdf", { matchBase: true })
[]
```

**Comment by kristinochka** [comment]
Seeing the same issue. I run `glob.sync(path, { nocase: true })` on Windows and it always returns nothing.

**Comment by kristinochka** [comment]
I'm also seeing the same issue on some environments in Linux. I'm running my code in a container, if that makes any difference.

**Comment by isaacs** [comment]
No longer an issue on v9, I believe.
