### ISSUE TITLE
Relative "ignore" not working if pattern uses absolute path and vice versa

### ISSUE THREAD

**Issue by liuxh0** [isaacs/node-glob#379]
I'm trying to excluding some matches using `ignore` option.

If `ignore` uses relative path and pattern uses absolute path, ignore doesn't work. Like this:
```
glob.sync('/absolute/path/*', {
  ignore: ['path/*']
});
```

Vice versa it doesn't work either if `ignore` uses absolute path while pattern uses relative path.

**Comment by Fcmam5** [comment]
Add `cwd` option

```
const glob = require("glob");
const myAbsPath = '/absolute/path';
const options = {ignore: '__tests__/**', cwd: myAbsPath}

glob("**/*.js", options, (er, files) => {
  console.log(files);
});
```

**Comment by isaacs** [comment]
No longer an issue in v9.
