### ISSUE TITLE
Security Problems using Laravel Elixir

### ISSUE THREAD

**Issue by tfprado** [isaacs/node-glob#382]
Minimatch security warning with Lavarel. Different version of minimatch and I can't update them

Regular Expression Denial of Service  

browserify@16.2.3
│ └─┬ glob@7.1.3
│   └── minimatch@3.0.4

browserify@11.2.0
│ │ └─┬ glob@4.5.3
│ │   └── minimatch@2.0.10

**Comment by isaacs** [comment]
The latest version of glob depends on minimatch 3.0.4 which does not have a vulnerability.  There is nothing more that I can do besides updating to a fixed version and moving forward.  The vulnerability is already fixed, it's on consumers to stay up to date with fixes.

Please update your environment to use the latest versions of browserify and glob, and you should be fine.  (Note that `npm audit` and `npm audit fix` make this pretty easy to do.)
