### ISSUE TITLE
Side effect with options in common.js => setopts()

### ISSUE THREAD

**Issue by guitarneck** [isaacs/node-glob#388]
Hello,

Options parameters are changed through setopts() function in common.js.

This lines :
```js
// disable comments and negation in Minimatch.
// Note that they are not supported in Glob itself anyway.
  options.nonegate = true
  options.nocomment = true

  self.minimatch = new Minimatch(pattern, options)
```

Should I suggest something like this :
```js
  self.minimatch = new Minimatch(pattern, Object.merge(options,{nonegate:true,nocomment:true}))
```

(Sorry, github text editors not working with my browser)

**Comment by isaacs** [comment]
Not "intentional", per se, but also not an accident.  I'm open a PR to make it use Object.merge() instead.
