### ISSUE TITLE
Can I use it with memory-fs or WebSocket-fs? Because many times, fs only represents this machine. 

### ISSUE THREAD

**Issue by yuchonghua** [isaacs/node-glob#389]
Can I use it with [memory-fs](https://www.npmjs.com/package/memory-fs) or WebSocket-fs? Because many times, fs only represents this machine, expecting to pass in fs

**Comment by miser** [comment]
I have the same question. Have you resolved it?

**Comment by isaacs** [comment]
This does work in v8, by providing an `fs` option that implements stat, statSync, readdir, and readdirSync.  However, I'm considering removing this in v9, as it adds quite a lot of complexity.

Do you still need this feature?
