### ISSUE TITLE
How to only match files

### ISSUE THREAD

**Issue by Richienb** [isaacs/node-glob#390]
What regex do I provide to the glob function in order to only match **files** instead of **files and folders**?

**Comment by jcollum-nike** [comment]
This seems more appropriate on StackOverflow.com.

**Comment by ovo4096** [comment]
> 我为glob函数提供了什么正则表达式，以便只匹配**文件**而不是**文件和文件夹**？

Options:
```
{
        nodir: true
}
```

**Comment by Richienb** [comment]
Thanks!
