### ISSUE TITLE
Expansion of non-trivial globs fails

### ISSUE THREAD

**Issue by eltronix** [isaacs/node-glob#391]
Hey, having an issue using non-trivial patterns in an OR block like `+(pattern|pattern|pattern)`.

So plain `**/components/**/*.jsx` matches but `+(**/components/**/*.jsx)` doesn't.

Even weirder is trivial ones work just fine e.g `+(*.js|*.js)`

**Comment by isaacs** [comment]
Yes, that is how extglob patterns work, they cannot contain / characters. It’s a bash/glob-ism that node-glob preserves. Try `{,}` style expressions.

**Comment by eltronix** [comment]
Thanks @isaacs
