### ISSUE TITLE
How to Glob Pattern recursively?

### ISSUE THREAD

**Issue by dave-dm** [isaacs/node-glob#392]
I'm currently doing this, which seems pretty ugly:

```javascript

glob(
  "{!(node_modules)**/**/**/**/**/**/**/**/**/**/*+(name)*test.js," + 
  "!(node_modules)**/**/**/**/**/**/**/**/**/**/*+(name)*/*.test.js}", 
  console.log
)

```

Trying to match any .test.js file that has "name" in either its filename or any folder in its path, recursively.

**Comment by zikuai** [comment]
I'm recently to meet this problem

**Comment by dave-dm** [comment]
this is what I'm using right now, not sure if there's a better solution:

```javascript
const {execSync} = require('child_process')
const glob = require('glob')

const match = process.argv[2] || ''
let globPattern =
  `!(node_modules)**/{`
  + `**/**${match}*/**/*,`
  + `*${match}*/**/*,`
  + `*${match}*/*,`
  + `*${match}*,`
  + `**/*${match}*`
  + `}.test.js`

execSync(`tape -- "${globPattern}"`, {stdio: 'inherit'})
```

**Comment by isaacs** [comment]
A few notes about `**`: First, it is only relevant when it's the only item in a path portion.  So, `foo**/bar` is the same as `foo*/bar`.  Second, `**` will match zero or more path portions, so `foo/**/**/**/bar` is the same as `foo/**/bar`.  For clarity, never do `**` except separated by a slash, and never follow `**` with another `**`.  There's no point.

Try this:

```
!(node_modules)/**/*name*{,/**/*}.test.js
```

The path portions there are:

- The first is not `node_modules`
- Then zero or more items
- Then either:
    - a path portion matching `*name*.test.js`
    - a path portion matching `*name*` followed by zero or more path portions, followed by `*.test.js`

Am I understanding the intention properly?

Note that this _won't_ match a `*.test.js` in the current directory.  (There has to be a first section that is not `node_modules`.)  If you want to include the current dir, you can do `{.,!(node_modules)}/**/*name*{,/**/*}.test.js`.

**Comment by ws-perelyaynen** [comment]
@isaacs 
it seems that it works only when bash allows it. 
in other words, only when
`shopt -s globstar`
Am I right?
