### ISSUE TITLE
Oh my glob!

### ISSUE THREAD

**Issue by Diokuz** [isaacs/node-glob#399]
Why you guys removed an old supercool gif logo? :))

I used glob only because of it)

![image](https://user-images.githubusercontent.com/2929442/60353070-e1fa4280-99d1-11e9-97ed-e9af3d0df612.png)

**Comment by herman-rogers** [comment]
I second this. At least slap it in the wiki.

**Comment by lovetingyuan** [comment]
![oh-my-glob](https://user-images.githubusercontent.com/7310471/61122733-28bd6180-a4d5-11e9-8a95-b744827252c6.gif)
I like it too.

**Comment by lvl99** [comment]
Please bring it back...

**Comment by roccivic** [comment]
Duplicate of #396
