### ISSUE TITLE
Is there a maximum number of subdirectories to watch? 

### ISSUE THREAD

**Issue by Javi-er** [isaacs/node-glob#400]
I have my Sass files organized in a set of subdirectories: `dir1/dir2/dir3/dir4/dir5 ` 
And I set up the following rule to watch the changes in there: `src('**/*.scss', { cwd: './dir1' })`

Changes on `dir1/dir2/dir3/dir4/_somefile.scss` are picked correctly, however changes on `dir1/dir2/dir3/dir4/dir5/_someotherfile.scss` are ignored for some reason. Is there a max limit for nesting that I'm not aware of?

**Comment by isaacs** [comment]
There's no limit imposed by this module, unless you specifically set `maxLength` to a number other than `Infinity`.  (`maxLength` removed in glob v9.)  Your filesystem may impose a limit if there's as recursive symbolic link, but that wouldn't be followed anyway for `**`.

So I don't think this is a glob bug, unless you're using a very old version (even old as of this comment from 3.5 years ago).
