### ISSUE TITLE
Add an Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [isaacs/node-glob#402]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a canonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have an Ethereum address in their package.json file. 

Having an Ethereum address would allow various cryptocurrencies to be donated, including stablecoins pegged to USD, like USDC or DAI. Essentially it is another payment network like PayPal, but open and decentralized like the internet. Getting an address is relatively straightforward through something like MetaMask or Coinbase. You could also generate one on your own.

**Comment by jimmywarting** [comment]
pls don't bloat the package.json with other stuff that isn't related to npm or node. instead use something like: github sponsors

**Comment by isaacs** [comment]
Funny you should mention that!  Please update to the latest npm and run `npm fund glob`.  (Or just cut out the extra step and [click here](https://github.com/sponsors/isaacs).)  If you prefer crypto, 1AvzULWwbwLbfbFR7FmrL9BxKjshhY4rL1 is my BTC address.  (But it looks like I'd have to upload my drivers' license to receive funds?  I'll maybe get around to doing that someday.)

_taking off my "glob maintainer" hat, putting on my "npm maintainer" hat_

I'd be fine with incorporating eth or btc addresses in the `funding` object on package.json, but I think it's worth [opening an RFC to discuss it](https://github.com/npm/rfcs).  It'd be good to work out what the `npm fund` command should do when it sees a crypto currency address.
