### ISSUE TITLE
Does not match for negative ignore

### ISSUE THREAD

**Issue by zaverden** [isaacs/node-glob#409]
I have following structure:
```
data
├── section
│   └── file1.json
└── section_2
    └── file2.json
```

When I run
```
glob.sync('**', { ignore: ['!data/section/**'] }
```
I expect to get `[ 'data/section/file1.json' ]` but got an empty array.

In a real-world scenario (for similar files structure) I receive a set of project-root globs, but I need to get files from specific section only (without modifying globs). That's why I need for negative pattern in ignore

**Comment by isaacs** [comment]
Pattern negation isn't supported, in the main pattern or in the ignore option.  Why not just glob for the thing you're un-negating?

**Comment by justingrant** [comment]
> Why not just glob for the thing you're un-negating?

Here's a concrete examples of why glob negation is helpful in the configuration of [cSpell](https://cspell.org/configuration/): I want to spell-check my english localization strings, but not localized strings in any other language:
```json
    "src/locales/**",
    "!src/locales/en.yaml",
```

**Comment by isaacs** [comment]
@justingrant Ok, so use an `ignore` option, and a pattern.

```js
glob('src/locales/**', { ignore: 'src/locales/en.yaml' })
```

**Comment by justingrant** [comment]
The challenge (at least in this use case) is when the list is already negated, like in a .gitignore file or (like in this case) a JSON config file that can't call `glob` directly. Here's the ugly hack I ended up with. Not sure if there's a better way to do it.

```json
  "ignorePaths": [
    "src/locales/[^e]*.*",
    "src/locales/es.yaml",
  ],
```

glob('src', { ignore: 'src/locales/en.yaml' })

Yep, that works for simple cases, and if you're calling glob directly. It's harder when it's more indirect, for example in cSpell's case where it's a JSON config file and
