### ISSUE TITLE
Section with a single option returns empty match

### ISSUE THREAD

**Issue by asklar** [isaacs/node-glob#414]
```js
var glob = require("glob")
glob.sync('/*');          // returns a bunch of entries
glob.sync('{/*}'); // empty []
glob.sync('/{}*'); // empty []
glob.sync('/{*}'); // empty []

```

**Comment by isaacs** [comment]
Yeah, that's by design.  `{}` without any commas is a literal `{}`.  Try it in bash.

```
$ for i in {/*}; do echo $i; done
{/*}
```

You could argue that it's a bug in the design of the glob format, and I'd probably agree with you, I mean, it's freaking weird.  But it is what it is.  The goal of this module is to implement glob, not fix it.
