### ISSUE TITLE
Option for directory first

### ISSUE THREAD

**Issue by cata-code** [isaacs/node-glob#417]
Is there an option to make the results have the directories first, then the files, like most file browsers?
I tried `nosort` but it's not enough.

Or an option to get an object tree structure instead of a list of paths.

**Comment by isaacs** [comment]
There's no option to get an object tree structure, but there are plenty of modules on npm that do give you folder trees.

You could do something like this in the meantime, using `mark:true` to mark directories with a `/` and then sorting them yourself

```js
const matches = glob.sync('test/fixtures/a/**', { mark: true })
const sorted = matches.sort((a, b) => {
  const adir = a.substring(a.length - 1) === '/'
  const bdir = b.substring(b.length - 1) === '/'
  return adir === bdir ? a.localeCompare(b, 'en') : adir ? -1 : 1
})
console.log(sorted)
/*
[
  'abcdef/',
  'abcdef/g/',
  'abcfed/',
  'abcfed/g/',
  'b/',
  'b/c/',
  'bc/',
  'bc/e/',
  'c/',
  'c/d/',
  'c/d/c/',
  'cb/',
  'cb/e/',
  'symlink/',
  'symlink/a/',
  'symlink/a/b/',
  'x/',
  'z/',
  'abcdef/g/h',
  'abcfed/g/h',
  'b/c/d',
  'bc/e/f',
  'c/d/c/b',
  'cb/e/f',
  'symlink/a/b/c'
]
*/
```
