### ISSUE TITLE
Windows paths normalized to forward slashes, not platform-native backslashes

### ISSUE THREAD

**Issue by ryanblock** [isaacs/node-glob#419]
#### Description of issue

As many folks are aware, much of the world has sandardized on forward slashes as path / folder delimiters (eg `/path/to/your/file.txt` or `https://domain.com/path/to/your/view`).

Windows, however, has historically relied on backslashes (eg `C:\path\to\your\file.txt`).

Node, of course, respects both per-platform:
- *nix: `console.log(process.cwd()) // /path/to/current/folder`
- Win: `console.log(process.cwd()) // C:\\path\\to\\current\\folder`

When `node-glob` returns results on Windows, it outputs them with forward slash-normalized paths. This can cause cross-platform compatibility problems.

Example:
```
let files = glob.sync('*')
let relativePaths = files.map(file => file.replace(path.join(process.cwd(), path.sep)))
```
In Windows, the above code would not work, as using methods intended to ease cross platform compatibility (like `path.sep`) break with `node-glob`'s forward-slash normalized output.

#### Expected behavior
- Glob would output file paths that are platform-native and that can be used without additional denormalization steps

#### Repro steps
- Glob files on Windows; file paths are normalized to forward slashes
- Compare to `process.cwd()`, etc. in Windows; file Node presents backslash-normalized file paths

**Comment by jakearchibald** [comment]
I ran into this too. Node's [`path.resolve`](https://nodejs.org/api/path.html#path_path_normalize_path) helps.

**Comment by NotWearingPants** [comment]
On version 7.1.7:
```js
glob('/**') //= absolute with backslashes
glob('**') //= relative with forward slashes
glob('**', { realpath: true }) //= absolute with backslashes
glob('**', { absolute: true }) //= absolute with forward slashes
```
What is going on

It seems that [tiny-glob](https://www.npmjs.com/package/tiny-glob) works mostly the same and solves this issue, always returning native separators (unless you use an absolute path glob).

**Comment by ryanblock** [comment]
I'm pretty sure 8 resolves this by normalizing everything to forward slashes? Unless anyone disagrees, I am so incredibly happy to close this issue.

**Comment by isaacs** [comment]
Yep, that was the intent.  Closing!

**Comment by liudonghua123** [comment]
I use `filename.replace(/\\/g,'/')` like `glob.glob("./**/*.ts").then( filenames =>filenames.map(item => item.replace(/\\/g,'/'))).then(files=>console.info(files))`.

**Comment by isaacs** [comment]
You can also use the `path-scurry` objects which have `relativePosix()` and `fullpathPosix()` methods.

```ts
const results = (await glob('./**/*.ts', { withFileTypes: true })).map(p => p.relativePosix())
```

**Comment by liudonghua123** [comment]
Thanks, it is a more elegant method for doing this. 😄
