### ISSUE TITLE
Feature Request: have the glob function return a promise (while still handling the callback if specified)

### ISSUE THREAD

**Issue by Pomax** [isaacs/node-glob#420]
With promises and the async/await pattern now firmly established both in the browser and Node.js (not to mention https://deno.land now being a thing), it would be quite useful if `glob` supported the modern `async` pattern by returning a promise, in addition to still honoring the callback if specified, e.g.:

```
function glob(pattern, callback) {
  return new Promise((resolve, reject) => {
    whateverTheInternalCodeCallsAre(pattern, (err, files) => {
      if (callback) {
        callback(err, files);
      }
      if (err) {
        reject(err);
      } else {
        resolve(files);
      }
    });
  });
}
```

(and of course, "people can just write this themselves", but there would be _tremendous_ value in the library doing this for everyone, instead of thousands of people all having to roll that same code over and over)

**Comment by etienne-martin** [comment]
You can also do the following:

```typescript
import { promisify } from "util";
import g from "glob";

export const glob = promisify(g);
```

**Comment by Pomax** [comment]
Please note that this is _not_ a request for help because someone doesn't know how to use non-promise code in promise-based codebase, it's a feature request for the library itself. Suggestions on alternative ways to achieve a promise API are great on stackoverflow, but don't belong in a feature request issue.

**Comment by willemneal** [comment]
@Pomax I bet adding that functionality would be a welcomed PR, especially given its simplicity.

**Comment by Pomax** [comment]
Indeed, which is why I'd love to see _someone else familiar with this code_ write that PR. I'm already involved in too many open source projects as is, and writing a PR (even "a simple one") takes considerably more time that writing an issue comment given that I'd have to do a code dive first to make sure I'm writing code in the same style, and form not just the PRs but write proper tests for it as well. 

But if you think it's simple, you're clearly the better person to write it: I look forward to seeing your PR!

**Comment by isaacs** [comment]
> But if you think it's simple, you're clearly the better person to write it: I look forward to seeing your PR!

Ok, fine, you convinced me :joy:

#489

**Comment by Pomax** [comment]
Haha, and only 82 files changed =D

**Comment by isaacs** [comment]
> Haha, and only 82 files changed =D

Everything's simple if someone else does it :joy:
