### ISSUE TITLE
absolute `ignore` pattern containing `..` does not work unless `nomount` is set

### ISSUE THREAD

**Issue by amc1804** [isaacs/node-glob#421]
In this example (using glob@7.1.5) `foo` should be ignored, but is included in the output:

```
mkdir /tmp/glob-test
touch /tmp/glob-test/{foo,bar}
node -e "
const glob = require('glob');
glob('/tmp/glob-test/sub/../**',
  {ignore:'/tmp/glob-test/sub/../foo'},
  (err, files) => console.log(files));
"
[ '/tmp/glob-test', '/tmp/glob-test/bar', '/tmp/glob-test/foo' ]
```

The bug is avoided when `nomount` is true:

```
node -e "
const glob = require('glob');
glob('/tmp/glob-test/sub/../**',
  {ignore:'/tmp/glob-test/sub/../foo', nomount:true},
  (err, files) => console.log(files));
"
[ '/tmp/glob-test/sub/..', '/tmp/glob-test/sub/../bar' ]
```

Why am I putting `..` in the middle of absolute patterns? It wasn't my idea. I had `..` at the beginnings of relative patterns (the most typical place to use `..`), and glob-stream (gulp.src) insists on making the patterns absolute (using to-absolute-glob) for reasons I don't understand.

The bug doesn't seem to affect `ignore` patterns that end with `/**`:

```
node -e "
const glob = require('glob');
glob('/tmp/glob-test/sub/../**',
  {ignore:'/tmp/glob-test/sub/../**'},
  (err, files) => console.log(files));
"
[]
```

I wonder if this bug is related to #350 .

**Comment by isaacs** [comment]
Root mounting is removed in v9, making this no longer an issue.
