### ISSUE TITLE
Feature request: Add typescript definitions for glob

### ISSUE THREAD

**Issue by nspeedzy** [isaacs/node-glob#423]
So, I noticed that there are no typescript definitions for glob. I will try and work on a pull request for adding some typescript definitions to glob

**Comment by BioPhoton** [comment]
Really looking forward!

**Comment by nspeedzy** [comment]
@BioPhoton Sure! I'll start writing the type definitions

**Comment by nspeedzy** [comment]
Hello people. So it looks like there are type definitions for node-glob already
