### ISSUE TITLE
Network File Share path not Working

### ISSUE THREAD

**Issue by atummid** [isaacs/node-glob#424]
I have a NFS location BUT glob is not working with it BUT vanilla node function is working

require('fs').readdirSync("\\\\emea.corpdir.net\\XYZ\\file_exchange\\docfinder\\")---> Returning
BUT not 

glob("\\\\emea.corpdir.net\\XYZ\file_exchange\\docfinder",(err,res)=>console.log(err,res))

**Comment by remydavid** [comment]
Same here.

**Comment by isaacs** [comment]
It'll be supported in v9, but you will have to use `/` instead of `\` as your path separator in the pattern, as described in the readme.
