### ISSUE TITLE
"Not" operator does not match

### ISSUE THREAD

**Issue by possiblynova** [isaacs/node-glob#427]
I may be missing something, but from what I can see, the Not operator does not isn't matching anything:
[Image of problem](https://i.imgur.com/rmRA1uC.png)
[Other glob implementations seem to work](https://i.imgur.com/Q7b4noG.png)

**Comment by isaacs** [comment]
Negated patterns are not supported, but you can use `ignore` for this.

```js
// v8 and before
glob('**', { ignore: 'node_modules/**' }, (er, matches) => { ... })

// v9 and above
matches = await glob('**', { ignore: 'node_modules/**' })
```
