### ISSUE TITLE
Glob.sync dosen't update variable if called after files manipulations

### ISSUE THREAD

**Issue by neins** [isaacs/node-glob#432]
I use glob.sync to get all *.ttf files and write it into variable — `let ttfFiles = glob.sync(paths.src.fonts+'src/*.ttf');`, then I create new ttf files and call glob again in order to update current count of files, but it show me same amount and doesn't update variable.

Simplified example
```javascript
function generateFonts() {

 let ttfFiles = glob.sync(paths.src.fonts+'*.ttf'); // [ 'Gilroy-300.ttf', 'Playfair Display-400.ttf' ]

  src('Montserrat.otf')
  .pipe(otf2ttf())
  .pipe(dest(paths.src.fonts));

 //Try to update *.ttf files, call glob again
 ttfFiles = glob.sync(paths.src.fonts+'*.ttf'); // [ 'Gilroy-300.ttf', 'Playfair Display-400.ttf' ] 
                                                // it doesn't show Montserrat.ttf in array until I rerun the function
};

```

How to update variable? I suppose glob somehow cache first call and I had tried to set cache and statCache options in first call to false but it doesn't work. Maybe I misunderstood how does it works?

**Comment by neins** [comment]
It works when I delay call beginning with about 300 milliseconds. Entire font convertion task tooks about 25ms. 
```javascript
setTimeout(() => {
  console.log(glob.sync(paths.src.fonts+'*.ttf'))
}, 300)
```
But it is kinda hacky way for me and not preferable.

**Comment by neins** [comment]
I recently had found my solution, I just push string of new ttf file into array after its creating.

But I not close this issue beceause I suppose that problem with glob may be actual with other circumstances.

**Comment by kiuKisas** [comment]
Up, having the same issue
