### ISSUE TITLE
single term doesn't work inside brace

### ISSUE THREAD

**Issue by timepp** [isaacs/node-glob#434]
this is OK
```javascript
  const exts = ['py', 'pyc']
  glob.sync(`*.{${exts.join(',')}}`)
```

But the following doesn't match anything
```javascript
  const exts = ['py']
  glob.sync(`*.{${exts.join(',')}}`)
```

I have to branch my logic depending on how many elements inside `exts`

**Comment by WORMSS** [comment]
Confirmed
![image](https://user-images.githubusercontent.com/1384537/133221916-0bf352a1-2345-4aeb-adc3-1f31d2c52f97.png)

Made the example a tiny bit easier to read.
```js
import glob from 'glob';

console.log("1", glob.sync('*.{b}') );

console.log("2", glob.sync('*.{b,b}') );
```

```json
{
  "type": "module",
  "dependencies": {
    "glob": "7.1.7"
  }
}
```

**Comment by WORMSS** [comment]
I think the problem comes down to 
```js
if (options.nobrace ||
    !pattern.match(/\{.*\}/)) {
    // shortcut. no need to expand.
    return [pattern]
  }
``` 
in minimatch

Because it's returned `[pattern]` without removing the braces.. 
But even if it didn't shortcut and carried on to call `expand()` 
it seems even expand function has the exact same problem where it shortcuts and does not remove the braces... 

This seems like a bug that goes very deep down in logic.

**Comment by WORMSS** [comment]
https://github.com/juliangruber/brace-expansion/issues/56

**Comment by WORMSS** [comment]
@timepp seems you will have to special case it in your code...

Apparently this bug is consistent with some bullshito logic in a linux shell... because... yeah.. lets copy bugs from one system to an unrelated system

**Comment by juliangruber** [comment]
> Apparently this bug is consistent with some bullshito logic in a linux shell... because... yeah.. lets copy bugs from one system to an unrelated system

`brace-expansion` was designed with the sole purpose of reimplementing the bash logic. If node-glob wants to diverge from that, then one can either switch to another module or add an option to `brace-expansion` that would change its logic. Or of course one could special case the consumer logic to create a different string if there is just one option.

Which way to go is the choice of `node-glob`'s maintainers.

@WORMSS please try to use friendly language, we're all here to collaborate on good solutions.

**Comment by WORMSS** [comment]
> @WORMSS please try to use friendly language, we're all here to collaborate on good solutions.

Fixed
