### ISSUE TITLE
Error: EISDIR: illegal operation on a directory - docker windows image only

### ISSUE THREAD

**Issue by plachta11b** [isaacs/node-glob#436]
Hi, I have found weird issue, where glob.sync uses scandir syscall on a file. This behaviour only affects glob running in the docker container on windows daemon.

### Code
`glob.sync(path.join(".", "*", "*.csproj"))`

Using nodir option does not fix this issue.

### Configuration tested
node: v14.15.4
node: v12.18.3
image1: stefanscherer/node-windows:12.18.3-windowsservercore-2019
image2: mcr.microsoft.com/powershell:latest
node-glob: 7.1.6
node-glob: 7.1.4

### ERROR
```
Error: EISDIR: illegal operation on a directory, scandir 'C:/src/docker-compose.ci.yml'
    at Object.readdirSync (fs.js:1021:3)
    at GlobSync._readdir (C:\src\node_modules\glob\sync.js:288:41)
    at GlobSync._processReaddir (C:\src\node_modules\glob\sync.js:137:22)
    at GlobSync._process (C:\src\node_modules\glob\sync.js:132:10)
    at GlobSync._processReaddir (C:\src\node_modules\glob\sync.js:207:10)
    at GlobSync._process (C:\src\node_modules\glob\sync.js:132:10)
    at new GlobSync (C:\src\node_modules\glob\sync.js:48:10)
    at Function.globSync [as sync] (C:\src\node_modules\glob\sync.js:26:10)
    at u.getCsprojPaths (my_minified_project.js:1:xxxx)
    at u.run (my_minified_project.js:1:xxxx) {
  errno: -4068,
  syscall: 'scandir',
  code: 'EISDIR',
  path: 'C:/src/docker-compose.ci.yml'
}
```

### Filesystem Info
<details>
  <summary>Filesystem</summary>

- Volume Name : 
-   Volume Serial Number : 0xcc6a5586
-   Max Component Length : 255
-   File System Name : NTFS
-   Is ReadWrite 
-   Is Thinly-Provisioned
-   Supports Case-sensitive filenames
-   Preserves Case of filenames
-   Supports Unicode in filenames
-   Preserves & Enforces ACL's
-   Supports file-based Compression
-   Supports Disk Quotas **(not available in docker but in host machine)**
-   Supports Sparse files
-   Supports Reparse Points
-   Returns Handle Close Result Information
-   Supports POSIX-style Unlink and Rename
-   Supports Object Identifiers
-   Supports Encrypted File System
-   Supports Named Streams
-   Supports Transactions **(not available in docker but in host machine)**
-   Supports Hard Links
-   Supports Extended Attributes
-   Supports Open By FileID
-   Supports USN Journal **(not available in docker but in host machine)**

</details>

### Privileges
PS C:\src> **icacls .\docker-compose.ci.yml**
.\docker-compose.ci.yml NT AUTHORITY\SYSTEM:(F)
                        BUILTIN\Administrators:(F)
                        S-1-5-21-2625033213-654498683-907056245-1002:(F)

Successfully processed 1 files; Failed processing 0 files

**Comment by bartecargo** [comment]
@plachta11b I know it's a year on from your initial report, but do you recall if you resolved this problem? We've run into the same problem when using a local Windows directory mounted into a Windows container.

**Comment by plachta11b** [comment]
@bartecargo Yes it is too long ago and I forgot what was the cause. I remember that I have big issues with non lts microsoft windows images. Maybe it is linked to this issue too.

**Comment by plachta11b** [comment]
It affects all tested (both servercore and windows) windows containers with hyperv virtualisation. As workaround we are moving project files out of mounted folder and then copy output files back in CI.

**Comment by isaacs** [comment]
Wow, that is really confusingly weird.  It's saying "This is a directory, which is why I can't readdir it" when the error you'd expect there is `ENOTDIR`, because it's clearly not a directory.  Of all the error codes to mix up 🤦

The good news is that v9 is much better about this already.  Any error encountered anywhere just means "nope, can't do that thing".  If it saw the file, but then readdir failed, oh well, guess it's not a dir, move on and handle as if it's a file or some other thing.
