### ISSUE TITLE
feature: add AsyncIterable

### ISSUE THREAD

**Issue by waynevanson** [isaacs/node-glob#441]
Generators are fun and only read what they need to. The implementation below does it all in advance, but if applicable, would like a pull based implementation (similar to streams).

Implementation based on currently available API's:

```ts
import * as Glob from "glob";

export async function* glob(pattern: string, options?: Glob.IOptions) {
  const results = await Glob.__promisify__(pattern, options);

  for await (const result of results) {
    yield result;
  }
}
```

**Comment by isaacs** [comment]
Will be in v8, because Glob will be a Minipass stream.
