### ISSUE TITLE
Incorrect results when no read/execute permissions

### ISSUE THREAD

**Issue by smblott-github** [isaacs/node-glob#452]
This can't be right, no?

```
#!/bin/sh

whoami
ls -ld supervise

cat > test.coffee <<EOF
g = require "glob"
g.glob "*/does-not-exist.txt", (e, files) ->
  console.log e, files
EOF

coffee test.coffee
```

![image](https://user-images.githubusercontent.com/2641335/149313719-54fffecc-b24a-4c3f-9993-d9167c6183e2.png)

(There are other readable files and directories in the CWD too.)

**Comment by isaacs** [comment]
I take it that the file does not exist?  If so, no, that is not right, indeed.

I'm not sure what's going on there, but I can't reproduce using glob v9 or v8.  Maybe try upgrading to the latest released version?
