### ISSUE TITLE
*/** matches top level directories

### ISSUE THREAD

**Issue by fhd** [isaacs/node-glob#453]
I've noticed what _looks_ to me like a bug: I would expect the pattern `*/**` to match all paths with a minimum depth of one, but it appears to match directories (not files) at the top level as well. A concrete example:

```
$ mkdir -p node_modules && npm install glob@7.2.0
$ mkdir -p test/1/2/3 && cd test
$ echo 'require("glob")("*/**", (_, f) => console.log(f))' | node
[ '1', '1/2', '1/2/3' ]
```

I would have expected `[ '1/2', '1/2/3' ]`, but `1` was also matched.

_minimatch_, on the other hand, behaves as I'd expect:

```
$ mkdir -p node_modules && npm install minimatch@3.0.4
$ echo 'console.log(require("minimatch")("1", "*/**"))' | node
false
$ echo 'console.log(require("minimatch")("1/2", "*/**"))' | node
true
$ echo 'console.log(require("minimatch")("1/2/3", "*/**"))' | node
true
```

I'd be happy to help out - either with a patch if it is indeed a bug, or some documentation if it's defined behaviour, but I'd first need to know which one it is, couldn't mange to find out on my own.

(Tests above were performed with Node.js v16.10.0 on macOS 12.1.)

**Comment by isaacs** [comment]
Nope.  `**` can match _zero_ or more path portions.  So `*/**` matches `a` as well as `a/b/c/d`.

Observe:

```bash
#!/usr/bin/env bash

set -e

shopt -s globstar
shopt -s extglob

rm -rf a b c

mkdir -p {a,b,c}/{1,2,3}
touch {a,b,c}/{1,2,3}/{foo,bar,baz}
# tree

for i in */**; do
  echo $i # includes a, b, c
done
```

```
a  <-- here
a/1
a/1/bar
a/1/baz
a/1/foo
a/2
a/2/bar
a/2/baz
a/2/foo
a/3
a/3/bar
a/3/baz
a/3/foo
b  <-- here
b/1
b/1/bar
b/1/baz
b/1/foo
b/2
b/2/bar
b/2/baz
b/2/foo
b/3
b/3/bar
b/3/baz
b/3/foo
c  <-- here
c/1
c/1/bar
c/1/baz
c/1/foo
c/2
c/2/bar
c/2/baz
c/2/foo
c/3
c/3/bar
c/3/baz
c/3/foo
```

**Comment by isaacs** [comment]
The pattern that does what you want is `*/{*/**,*}`

**Comment by isaacs** [comment]
> I'd be happy to help out - either with a patch if it is indeed a bug, or some documentation if it's defined behaviour, but I'd first need to know which one it is, couldn't mange to find out on my own.

Technically it's documented that this library matches the behavior of recent versions of bash (v5, I think?  or 4.3?  I think those are the same anyway), so it's _sort of_ documented, but yeah, that could definitely be improved.  Patch welcome for that, as long as it's not just dumping `man bash` into the readme 😆

**Comment by fhd** [comment]
Thanks! I suppose that does make sense indeed - maybe just a bit unintuitive. If I can find a good place to mention this I'll do a PR!
