### ISSUE TITLE
Miniver ^3.0.4 dependency breaks when minimatch 3.0.5 is installed

### ISSUE THREAD

**Issue by creslin287** [isaacs/node-glob#455]
Hey,

Node v0.12.18.  Our version of pm2 depends on a version of shelljs, which depends on glob, which depends on ^3.0.4 of minimatch.  New release of minimatch is busted due to newer syntax used.  I suppose there are a lots of way to look at it, but this arguably breaks semver, IMHO.

  /var/www/html/admin/modules/pm2/node/node_modules/pm2/node_modules/shelljs/node_modules/glob/node_modules/minimatch/minimatch.js:4                             
  const path = (() => { try { return require('path') } catch (e) {}})() || {

Would you be ok if I pushed a PR changing the dependency version requirement for glob to be 3.0.4 instead of ^3.0.4 until minimatch fixes it?

Thanks,
Matthew Fredrickson

**Comment by maczyt** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ealmiladi** [comment]
Yes! We need this as well!!

**Comment by isaacs** [comment]
Fixed on minimatch 3.0.6
