### ISSUE TITLE
Problem with root directory of devices/volumes in windows

### ISSUE THREAD

**Issue by develmusa** [isaacs/node-glob#458]
Using  ```*``` in the root directory of a device/volume in Windows doesn't return any results.

✅ This pattern is working fine:  ```"[drive:]/[folder]/*"``` ex: ```"C:/tmp/*"```

❌ This pattern doesn't find nothing: ```"[drive:]/*"``` ex: ```"C:/*"``` 

Am I missing something or is this a bug?

**Comment by isaacs** [comment]
It needs a bit more testing, but I believe this is fixed in v9.
