### ISSUE TITLE
Minimatch version update

### ISSUE THREAD

**Issue by mmedvedik** [isaacs/node-glob#464]
I found minimatch v3.0.4 currently resolved version by the latest glob contains an RDOS vulnerability: https://www.huntr.dev/bounties/e4e1393c-d590-4492-9f43-8be3f3321629/ . Since critical changes in v3.0.5 (https://github.com/isaacs/minimatch/issues/153) the minimatch version will not update itself (glob package.json accepts only patch versions updates). Do you plan to upgrade minimatch dependencies to v3.0.5 or higher?

**Comment by animatedboy** [comment]
I see the new release tag 7.2.1 which has the changes for minimatch. And its not pushed to npm registry. when the sam has been planned?

**Comment by akerpelm** [comment]
also curious if there is any estimated completion to resolve this.
