### ISSUE TITLE
Coordinated fix on Feb 12 broke Windows path handling between node-glob and minimatch

### ISSUE THREAD

**Issue by jsuddsjr** [isaacs/node-glob#471]
When using `allowWindowsEscape=true` in minimatch options, glob is forcing minimatch to treat the path as though it contained _escapes_ rather than Windows path separators (backslashes). Notice the negation in the following statement, which would entirely fix the issue if it were allowed to run.

```js
  if (!options.allowWindowsEscape && path.sep !== '/') {
    pattern = pattern.split(path.sep).join('/')
  }
```

Therefore, `glob@7.2.2` combined with `minimatch@^3.1.1` _cannot_ locate files using patterns like:

    E:\\Src\\repo\\packages\\test\\.storybook\\main{'.js','.jsx'}

Unfortunately, this is causing the latest version of Storybook to fail to locate configuration files in its default state in Windows. Error: No configuration files have been found in your configDir.

Please coordinate another fix.

**Comment by dkrnl** [comment]
similar issue after `npm update`
```
WARNING in svg-spritemap-webpack-plugin
No source files match the patterns: 'source\img\svg-sprite\*.svg'
```

**Comment by nicolas377** [comment]
For right now, the only solution I can think of is to pin glob at 7.2.1.

**Comment by nicolas377** [comment]
@jsuddsjr Is this not an issue on 7.2.1? If so, how about 7.2.0?

**Comment by nicolas377** [comment]
The issue seems to be at 73feafd17f1c04633349652605e12fbbaef9b3cf. It will not show up on non-windows systems.

allowWindowsEscape is documented [here](https://github.com/isaacs/minimatch/tree/v3.1.1#allowwindowsescape), which indicates that the translation from `\` to `/` will not occur. That is an undocumented breaking change for windows users. I will open a PR to revert the setting of allowWindowsEscape. For right now, pin glob to 7.2.0 with npm overrides, like this:

package.json
```json
  "overrides": {
    "glob": "7.2.0"
  }
```

**Comment by h1orz** [comment]
> @jsuddsjr Is this not an issue on 7.2.1? If so, how about 7.2.0?

7.2.0 is work.

**Comment by nicolas377** [comment]
Could you try overriding glob to my PR and checking if it works?

package.json
```json
  "overrides": {
    "glob": "github:nicolas377/node-glob#revert-allowWindowsEscape"
  }
```

**Comment by h1orz** [comment]
> Could you try overriding glob to my PR and checking if it works?
> 
> package.json
> 
> ```json
>   "overrides": {
>     "glob": "github:nicolas377/node-glob#revert-allowWindowsEscape"
>   }
> ```



> Could you try overriding glob to my PR and checking if it works?
> 
> package.json
> 
> ```json
>   "overrides": {
>     "glob": "github:nicolas377/node-glob#revert-allowWindowsEscape"
>   }
> ```

It is work.
```
  # yarn
  "overrides": {
    "glob": "github:nicolas377/node-glob#revert-allowWindowsEscape"
  }
```

**Comment by novrain** [comment]
https://github.com/stylus/stylus/issues/2680

**Comment by jsuddsjr** [comment]
> @jsuddsjr Is this not an issue on 7.2.1? If so, how about 7.2.0?

7.2.1 introduced the flag, 7.2.0 works as expected.

**Comment by isaacs** [comment]
Can you try using glob 7.2.3?

If that doesn't work, idk, might just have to roll back that change entirely, or do a different thing.

**Comment by nicolas377** [comment]
The only problem was setting that config option to true, the upgrade didn't break anything. 7.2.3 should be working. If it is, I'll go ahead and close my PR.

**Comment by h1orz** [comment]
Great, 7.2.3 is work.
