### ISSUE TITLE
Windows with space doesnt work

### ISSUE THREAD

**Issue by monmonja** [isaacs/node-glob#484]
I have the following code
`glob("C:\Users\First Name\Desktop\project\source\content\javascript\build\*.js", 
    {},
    (err, files) => { console.log(files); },
);`
when execute it doesnt list any files. It works with 7.2.0 but not on ^8.0.3

**Comment by nicolas377** [comment]
See #467 for information on your issue.

**Comment by isaacs** [comment]
Yes.  It's not the space that's causing problems, it's the path separators.  Use `/` characters instead of `\` in glob patterns.

You can do this, if it's any easier:

```js
glob('*.js', { cwd: 'C:\\Users\\First Name\\Desktop\\project\\source\\content\\javascript\\build' }, cb)
```

Note that in v9, it will no longer take a callback, and return a promise instead.

**Comment by timothylcooke** [comment]
I'm trying to get typescript unit tests working, and it breaks on Windows (possibly other platforms too?) if any files have a space in their name. Apparently `node --test` requires quotes around files with spaces in their names, and I can't figure out a way to make that happen with `glob -c`

    npx glob -c "node --watch --import tsx --test" "./tests/*.ts"
