### ISSUE TITLE
concurrent Globs behave incorrectly because of inflight usage

### ISSUE THREAD

**Issue by jedwards1211** [isaacs/node-glob#485]
If I abort one `Glob` and start a new one on the same directory, the new one often fails to emit all of the valid matches.

Looking in the debugger, there are many places like this
```
Glob.prototype._readdir = function (abs, inGlobStar, cb) {
  if (this.aborted)
    return

  cb = inflight('readdir\0'+abs+'\0'+inGlobStar, cb)
  if (!cb)
    return
```

In the new `Glob` run, `inflight` sees that there's still a running `readdir` call from the old, aborted glob.  `inflight` returns `null` and `_readdir` returns early.  But because the old glob is aborted, it never calls the callback, so the new `Glob` never gets the results.

Also, it's fundamentally incorrect to dedupe the requests with `inflight` this way, because one Glob may get results from a deduped request that's fulfilled by another Glob with different options.  (For example, the `readdir` results depend on the `mark` option).  Global caching/deduplication should be avoided.

## Reproduction
```js
const { Glob } = require('glob')

const glob1 = new Glob('*')
glob1.abort()

const glob2 = new Glob('*')
glob2.on('match', (f) => console.error(f))
glob2.on('abort', () => console.error('abort'))
glob2.on('error', (e) => console.error(e.stack))
glob2.on('end', () => console.error('end'))
```

### Expected output
Contents of the current working directory, followed by `end`

### Actual output
Nothing!  The event loop dies because `glob2` is waiting on the inflighted `readdir` callback, but it never gets called back because `glob1` was aborted before `readdir` finished.

If you comment out `glob1.abort()`, `glob2` produces the expected output.

**Comment by isaacs** [comment]
Fixed in v9
