### ISSUE TITLE
package.json not found in srcDir file glob patterns

### ISSUE THREAD

**Issue by opsett** [isaacs/node-glob#491]
**on package.json**  
  "... scripts": {
        "dev": "nw source/",
        "prod": "nwbuild source/ --mode run -p win64  --buildDir  dist/"
    },

_**npm run dev**_ works but _**npm run prod**_ fails with following error message: _**[ ERROR ] 2023-01-28T12:38:42.542Z package.json not found in srcDir file glob patterns**_

Also used the  CLI to try the command: _**npm nwbuild ./ --mode=run --version=latest --flavor=sdk**_ , but no effect except version id "9.3.1" was returned

**Comment by isaacs** [comment]
I think this is an issue with whatever nw or nwbuild is, not the glob library. Try running `npm bugs nw`.

**Comment by opsett** [comment]
Thanks for your timely response.
