### ISSUE TITLE
How to replace `root` option?

### ISSUE THREAD

**Issue by Zamiell** [isaacs/node-glob#492]
Hello, and thanks for the library.

When upgrading to version 9, I see from the change log that the `root` option is removed. However, there is no indication of how to migrate existing code that uses the option. Can you provide an example of what to do?

Also, I propose that this information is also added to the change log for others looking to upgrade.

**Comment by isaacs** [comment]
The root option could be used in a variety of ways, and had a ton of surprising side effects. It would be easier for you to share what you were doing with it and then I can help you figure out how to do that in a sensible way. There's no clear corollary that works in general.

**Comment by isaacs** [comment]
Having slept on this, I suppose it _could_ be brought back, but it'd be weird when the pattern starts with a drive letter or UNC path on Windows.  It would have to be _strictly_ limited to patterns starting with `/`, which (at least on Windows) are _not_ UNC paths.  Then it's just a matter of resolving to the root option, rather than `cwd.resolve('/')` 🤔

**Comment by Zamiell** [comment]
I was using it like this:
https://github.com/IsaacScript/isaacscript/blob/f44970198bf547dc592f352ccabf0c2c02ed4a7c/scripts/rewriteSourceMapDeclarationMapPaths.mts

I realized I could use `cwd` to kind of emulate what I was doing before, so now I am doing this:
https://github.com/IsaacScript/isaacscript/blob/8f4af0b1c032a368ee2380c85ebd5e5999838f15/scripts/rewriteSourceMapDeclarationMapPaths.mts

But it's kind of a pain in the butt because I have to manually build up the path again, if that makes sense. (Because using the `cwd` chops off the first part of the path.)

**Comment by Zamiell** [comment]
Hrm, after looking through the available options again, I suspect I should be using `absolute` option in combination with `cwd`?

**Comment by isaacs** [comment]
Yeah, if you just want absolute paths, then `{absolute: true}` is the way to go.

If you still have a use case for `root`, maybe take a look at #498 and see if it gives you what you need?  You can test it out by running:

```
npm install github:isaacs/node-glob#pull/498
```

**Comment by Zamiell** [comment]
To be more concise, my use case for `root` was "get files matching a glob in a specific subdirectory". (The subdirectory cannot be part of the glob itself, as I am a Windows user, and Node's `path.join` will produce paths that are incomprehensible to `glob`.)

For this specific use-case, it sounds like using the `cwd` + `absolute` options would handle this pretty well. Thus, I'm fine with removing root.

Maybe we should update the patch notes to include some of this discussion?

**Comment by isaacs** [comment]
@Zamiell i just noticed the url of your gists, and it spooked me out, because an isaacscript is what they'll put me in when I die. 

(This is a pun. "isaacs crypt")
