### ISSUE TITLE
[suggestion] revert hasMagic

### ISSUE THREAD

**Issue by geekact** [isaacs/node-glob#496]
I prefer that `hasMagic('test/{a,b}.js')` should returning `true` rather than false.

Current version: 9.0.1

**Comment by isaacs** [comment]
There is no longer any distinction made between grace expansion and just passing in an array of files, so this was always a bit inconsistent, but it could perhaps be done with an option. Can you share the use case where this distinction is relevant?

**Comment by geekact** [comment]
All right, add an option to enable this feature will be very compatible.

**Comment by geekact** [comment]
For more complex scenario, `test/{a,b}/path/to/{c,d,e}.js` should spread `2 x 3 = 6` array items

**Comment by isaacs** [comment]
Yes, brace expansions are multiplicative, but they're essentially a shorthand for filling up an array of patterns.  Internally, that's what's happening, it just blows up to fill the pattern list, and from then on, glob doesn't do anything with braces, or even know that they were used.

**Comment by isaacs** [comment]
@geekact Can you try out #499 and see if it meets your needs?  You can install it by doing:

```
npm i github:isaacs/node-glob#pull/499
```

```js
import { hasMagic } from 'glob'
console.log(hasMagic('a{b,c}d', { magicalBraces: true }))
```

**Comment by geekact** [comment]
Fail to install by pnpm
```
Could not resolve pull/499 to a commit of git+ssh://git@github.com/isaacs/node-glob.git.
```
And I believe it can works fine since you have written test case
