### ISSUE TITLE
MaxListenersExceededWarning on Minipass

### ISSUE THREAD

**Issue by gallofeliz** [isaacs/node-glob#510]
Hello,

I have this error on my logs :
```
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(destroyed) listeners added to [Minipass]. Use emitter.setMaxListeners() to increase limit
```

Here the code :
```typescript
const pruneBefore = dayjs().subtract(maxAge, 'milliseconds').format('YYYY-MM-DDTHH:mm:ss')
for await (const file of globIterate('/data/cam1/**/*.jpg', {nodir: true, signal: undefined}))  {
    const date = basename(file).replace('.jpg', '')
    if (date < pruneBefore) {
        await unlink(file)
    }
}

for (const dir of (await glob('/data/cam1/*/**/', {signal: undefined})).sort().reverse())  {
    if ((await readdir(dir)).length === 0) {
        await rmdir(dir)
    }
}
```

I didn't see this warning during development, probably because of limited directories/files. 

Does the warning show on your side ? I didn't find similar case on closed issues.

Regards

**Comment by isaacs** [comment]
I guess if there's files in there that aren't jpg's, you'd want to do something like:

```js
return /\.jpg$/.test(file) && basename(file, '.jpg') < pruneBefore
```

**Comment by gallofeliz** [comment]
Thanks @isaacs for your answer. I will test rimraf as it seems to better fit my needs.

Regards

**Comment by isaacs** [comment]
Updated to add "glob:true" to the example. It's like I don't even read my own changelogs lol

**Comment by isaacs** [comment]
Thanks for the report.  Fixed in minipass.  If you're still encountering this, `npm update minipass` or just `npm update` should fix it.

**Comment by gallofeliz** [comment]
Thanks, I will test it soon (wanted to rest this week end :) )

Regards
