### ISSUE TITLE
! pattern not working

### ISSUE THREAD

**Issue by musicq** [isaacs/node-glob#516]
This glob pattern is not working in both version 8 and 9, however, it works in version 7.

`?(drawable-!(xxxhdpi)|raw)/**/*.@(png|svg|jpg)`

File structure

```
root/
├── raw/
│   └── a.json
├── drawable-hdpi/
│   └── b.jpg
├── drawable-mdpi/
│   └── c.jpg
├── drawable-xhdpi/
│   └── d.jpg
├── drawable-xxhdpi/
│   └── e.jpg
└── drawable-xxxhdpi/
    └── f.jpg
```

In both 8 and 9, it will only filter the files under `raw` folder.

But in v7, all the images and json files can be filtered.

```js
glob(
  '?(drawable-!(xxxhdpi)|raw)/**/*.@(png|svg|jpg)',
  {
    cwd: '/root',
    dot: true,
  },
  (error, files) => {
    if (error) {
      console.error(error)
    }

    console.log(files)
  },
)
```

**Comment by isaacs** [comment]
Just by reading the pattern, I'd expect it to show all the files shown except those under `drawable-xxxhdpi`, correct?

If it's not doing that, then yes that is a bug, likely in minimatch.

**Comment by musicq** [comment]
@isaacs yes correct! v7 will list all the files except `drawable-xxxhdpi`, but in v8 v9 it will only list the files under the `raw` folder.
