### ISSUE TITLE
problem between 7.1.3 and 8.1.0 when i use glob.sync

### ISSUE THREAD

**Issue by wq1559** [isaacs/node-glob#517]
hello， im faced a using problem， below is my code
`import { resolve } from "path";`
 `const routeArr = ["user"];`
 `const apipath =  ' D:\workspace\project'`;
 `routeArr.forEach(item => {
     glob.sync(resolve(apiPath, './'+ item + ".js")).forEach(require);
    });
`
it will return empty array []  in version 8.1.0;

but in version 7.1.3, it will work as expected, and return  filenames array found matching the pattern;

**Comment by isaacs** [comment]
You have to use / as the path separator for glob patterns, as it says in the readme. But you can set the cwd option to set the current working fit for the search. 

Try this:

```js
import { resolve } from "path";
const routeArr = ["user"];
const apipath = 'D:\\workspace\\project';
routeArr.forEach(item => {
  glob.sync(item + ".js", {
    cwd: apipath,
  })).forEach(require);
});
```

**Comment by wq1559** [comment]
Thanks. it resolved.

**Comment by wq1559** [comment]
> You have to use / as the path separator for glob patterns, as it says in the readme. But you can set the cwd option to set the current working fit for the search.
> 
> Try this:
> 
> ```js
> import { resolve } from "path";
> const routeArr = ["user"];
> const apipath = 'D:\\workspace\\project';
> routeArr.forEach(item => {
>   glob.sync(item + ".js", {
>     cwd: apipath,
>   })).forEach(require);
> });
> ```
Thanks. it resolved.
