### ISSUE TITLE
Package cannot be used without the esModuleInterop flag

### ISSUE THREAD

**Issue by mrmlnc** [isaacs/node-glob#518]
Hello, @isaacs,

First of all, thank you for your work. I see that glob@9 has taken a big step forward and now can compete with the `fast-glob` solution.

Unfortunately, I ran into a problem when upgrading to the new version. Right now this package cannot be used without the `esModuleInterop` flag in the TypeScript configuration.

```ts
node_modules/glob/dist/mjs/glob.d.ts:3:8 - error TS1259: Module '"<…>/OpenSource/glob-issue/node_modules/minipass/index"' can only be default-imported using the 'esModuleInterop' flag

3 import Minipass from 'minipass';
         ~~~~~~~~

  node_modules/minipass/index.d.ts:150:1
    150 export = Minipass
        ~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
    
// …

node_modules/path-scurry/dist/cjs/index.d.ts:4:8 - error TS1259: Module '"<…>/OpenSource/glob-issue/node_modules/lru-cache/index"' can only be default-imported using the 'esModuleInterop' flag

4 import LRUCache from 'lru-cache';
         ~~~~~~~~

  node_modules/lru-cache/index.d.ts:869:1
    869 export = LRUCache
        ~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

Repository for reproducing the problem:

https://github.com/mrmlnc/glob-typescript-issue

I might have a solution to that problem. Change all import's for `minipass` and `lru-cache` packages:

```diff
-import Minipass from 'minipass';
+import * as Minipass from 'minipass';
```

This is a change without having to do anything in your dependencies. Or do something like [this](https://github.com/isaacs/minipass/pull/46) for your dependencies.

All right, maybe there's another solution to all this.

**Comment by isaacs** [comment]
Hm, the change to minipass was straighforward enough, but lru-cache is written in TS and has a workaround to support setting the default export in CJS without losing type information entirely or requiring people to do `const LRUCache = require('lru-cache').default`

I'll take a look at that example repo, maybe see if there's a way to make this stuff all work.  It's very challenging to get ESM+CJS+TS all building properly from a single codebase in a way that doesn't break.  I suspect that I might just have to make a clean break on all my modules that use a default export, and just use named exports everywhere, which would be a shame.

> First of all, thank you for your work. I see that glob@9 has taken a big step forward and now can compete with the fast-glob solution.

Thanks, you flatter me, but I'm not sure about that. Node-glob might be more correct in a handful of edge cases, but fast-glob is just unrealistically fast. It's black magic, very impressive ;)  If you have any suggestions to make glob faster, I'd be grateful, but I suspect it just comes down to different choices. Mirroring Bash 100% faithfully means handling some really bizarre stuff.

**Comment by isaacs** [comment]
Aha, it seems that `allowSyntheticDefaultImports` is also related to this somehow.

Without either that or `esModuleInterop`, having both `export default Minipass` and `export = Minipass` blows up.  The error message says that `esModuleInterop` is required, but actually either one works.

I'm pretty sure that `import * as Minipass from 'minipass'` won't work with the ESM build though, because it'll get `{ default: Minipass }`, not the actual Minipass constructor.

**Comment by isaacs** [comment]
Yeah, so... playing with this more, there doesn't seem to be any way to have a default export from a commonjs file that can be default-imported (without `.default`) into commonjs, with accurate types, unless either `esModuleInterop` or `allowSyntheticDefaultImports` are supported.

So the options are:
- I stop shipping default exports.  (Breaking change to all modules doing so.)
- Use ESM
- Use one of those two flags.

I think I'm going to start moving all my modules to solely using named exports, but that's definitely gonna take a minute.  In the meantime, I recommend using `esModuleInterop` or `allowSyntheticDefaultImports`, or pull in the ESM builds.

**Comment by isaacs** [comment]
Removed all default exports from glob as of v10.  Upgrade and this problem goes away.  I'm flipping the CJS/ESM/TS table on this one lol
