### ISSUE TITLE
Allow option for returning linux paths (like in version 8)

### ISSUE THREAD

**Issue by HarelM** [isaacs/node-glob#521]
I think this library is great! Thanks for all the effort put into it.
I also think the recent support for windows is great as well!
Having said that, when upgrading to version 10 a lot of places in my code started failing due to the support for windows as we run the same code on windows and linux.
Some where easy to fix but other were less.
The following is an example of something that broke:
```js
const allTestsRoot = path.join('.', 'test', 'integration', 'query', 'tests');
let globPattern = path.join(allTestsRoot, '**/style.json');
globPattern = globPattern.replace(/\\/g, '/'); // this is needed for windows
const testStyles = globSync(globPattern);
for (const styleJson of testStyles) {
    const testCaseRoot = path.dirname(styleJson); // this will return '.' on windows
    const caseName = path.relative(allTestsRoot, testCaseRoot); // this will return '../../../..' on windows
```

Before version 10 the content of `style.json` would be with `/` on windows, which allows path.dirname to return the correct dir.
Would be great to have some options to "bring back" this behavior - something like `returnLinuxPath` that can be used in windows as well.
Let me know if more information is needed.

**Comment by isaacs** [comment]
Hm, yeah that would be handy in a lot of cases for me, too.

The flag should go in path-scurry, and then glob can just pass it along. `returnPosixPath: boolean` or something?

**Comment by isaacs** [comment]
(I've used BSD systems for long enough that calling macOS "linux" feels deeply wrong, lol)

**Comment by HarelM** [comment]
sure :-) I can't argue here... I knew I was writing a wrong name for the parameter but couldn't remember the right term...

**Comment by isaacs** [comment]
This was fixed by a1cba4da1612fd0b8d7adffd7da536f75a729454, I just put the wrong number in the commit message 😅 

Landed as `{ posix:boolean }` option, published in 10.1.0.

**Comment by isaacs** [comment]
The `"return"` and `"paths"` bits of that seemed extraneous, since this module always returns paths :)

**Comment by HarelM** [comment]
Thanks for the quick resolution!
