### ISSUE TITLE
nocase:true not working properly on linux

### ISSUE THREAD

**Issue by aabluedragon** [isaacs/node-glob#526]
For the given example, let's say we have the following directory in our file system (linux)
`/home/myusername/app/StylES`
The following code will not find this entry:
```javascript
const results = glob.globSync('styles', {cwd:"/home/myusername/app", nocase:true});
console.log(results.length) // prints 0
```

**Comment by isaacs** [comment]
Does it work if you add `nocaseMagicOnly: false` to the options?

**Comment by aabluedragon** [comment]
Tried adding that, typescript says `'nocaseMagicOnly' does not exist in type 'GlobOptions'`
Either way, I tried and it didn't work.

**Comment by isaacs** [comment]
Oh right, it's a minimatch option. I think if you specify nocase, but it's a normally case sensitive file system, we need to disable that option. On May 4, 2023, at 14:18, Alon Amir ***@***.***> wrote:﻿
Tried adding that, typescript says 'nocaseMagicOnly' does not exist in type 'GlobOptions'
Either way, I tried and it didn't work.

**Comment by aabluedragon** [comment]
So, is it planned to fix nocase:true to work over linux as well, or support `nocaseMagicOnly` to overcome it?
This is a very useful feature to have on case sensitive operating systems.

**Comment by isaacs** [comment]
Fix it in Linux. Basically, have glob set nocaseMagicOnly as appropriate, based on both the platform and nocase.
