### ISSUE TITLE
How can it be used against a set of paths in an array?

### ISSUE THREAD

**Issue by justinmchase** [isaacs/node-glob#530]
Suppose what I want is not to scan the file system at all, but I have a bunch of path strings in an array and I want to apply them to a glob to see which matches? 

Does this library have such a feature?

**Comment by isaacs** [comment]
Glob doesn't, but minimatch (the library glob uses to perform matching) does.

```console
$ npm install minimatch
```

```js
import { minimatch } from 'minimatch'
// or: const { minimatch } = require('minimatch')
const paths = ['/a/b/c', '/a/b/x', '/x/y/z', '/i/j/k/x']
const fn = minimatch.filter('**/x')
console.log(paths.filter(fn))
// output: [ '/a/b/x', '/i/j/k/x' ] 
```

**Comment by justinmchase** [comment]
perfect, thanks.
