### ISSUE TITLE
globSync with process.cwd() path no more working since v9

### ISSUE THREAD

**Issue by popod** [isaacs/node-glob#535]
Hi,

```js
globSync(path.join(process.cwd(), 'modules/**/client/'))
```

Works well on glob `8.1.0` but only return an empty array since glob v9. This code works well with glob v9 on my Mac, the problem is only on my Linux server.

What could be the problem ?

**Comment by isaacs** [comment]
The only reason why process.cwd() would be weird in a glob expression is windows, where the cwd has / path separators. 

Two things to investigate with this puzzle:

Is the cwd the same in both cases? Ie, are there files in the cwd that ought to match on the Linux machine?

Typically, Linux file systems are case sensitive, and Darwin file systems are not. Is the path named `Modules` or `Client` or something? You can set `{ nocase: true }` to force a case insensitive match on a case sensitive file system.

**Comment by popod** [comment]
Hi,

Thank you for your fast reply.. I think that this is not a case sensitive/insensitive problem. And yes, they are matching files.

Here is a reproductible exemple of my usecase. Works on my Mac, but not on my server which run on "Debian GNU/Linux 8 (jessie)"

```js
const path = require('path')
const glob = require('glob')

// mkdir modules
// mkdir modules/accounting
// mkdir modules/accounting/client
// mkdir modules/accounting/client/controller
// mkdir modules/analytics
// mkdir modules/analytics/client
// mkdir modules/analytics/client/controller
// mkdir modules/analytics/client/services

const files = glob.sync(path.join(process.cwd(), 'modules/*/client/'))

console.log('cwd  :', process.cwd())
console.log('glob :', path.join(process.cwd(), 'modules/*/client/'))
console.log(files)

// Result with glob 8.1.0
//
// cwd  : /home/clients/8a5230040414ace8330e2e1e7e67545f/web/test1
// glob : /home/clients/8a5230040414ace8330e2e1e7e67545f/web/test1/modules/*/client/
// [
//  '/home/clients/8a5230040414ace8330e2e1e7e67545f/web/test1/modules/accounting/client/',
//  '/home/clients/8a5230040414ace8330e2e1e7e67545f/web/test1/modules/analytics/client/'
// ]

// Result with glob 9.0.0
//
// cwd  : /home/clients/8a5230040414ace8330e2e1e7e67545f/web/test1
// glob : /home/clients/8a5230040414ace8330e2e1e7e67545f/web/test1/modules/*/client/
// []
```

**Comment by isaacs** [comment]
Wait a minute, `glob.sync` doesn't exist on 9.0.0, so running the code provided should result in this:

```
const files = glob.sync(path.join(process.cwd(), 'modules/*/client/'))
                   ^

TypeError: glob.sync is not a function
    at Object.<anonymous> (/home/isaacs/glob-gh-535/t.js:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

But this works for me on Linux:

```bash
#!/usr/bin/env bash
mkdir -p modules/{accounting,analytics}/client/{controller,services}
echo {} > package.json
npm i glob@9.0.0
node -p '
const { globSync } = require("glob")
path = require("path")
globSync(path.join(process.cwd(), "modules/*/client"))
'
```

Are you sure you're using glob 9.0.0?  Using glob 10.3.0, the code provided results in:

```
$ node t.js 
cwd  : /home/isaacs/glob-gh-535
glob : /home/isaacs/glob-gh-535/modules/*/client/
[
  '/home/isaacs/glob-gh-535/modules/analytics/client',
  '/home/isaacs/glob-gh-535/modules/accounting/client'
]
```

Tested on: `Linux izs 4.15.0-166-generic #174-Ubuntu SMP Wed Dec 8 19:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by popod** [comment]
Hi, thank you for your reply !

> Wait a minute, glob.sync doesn't exist on 9.0.0, so running the code provided should result in this:

Yes, sorry.. I use `glob.globSync()` with gulp 9.0.0 and upper.

> Are you sure you're using glob 9.0.0? Using glob 10.3.0 (or 9.3.5), the code provided results in:

Yes, I'm using glob 9.0.0. This problem appears when I update glob from 8.1.0 to 9.0.0 (no others code changes).. gulp works well without the `process.cwd()` part, but this special case does not works for me.. I've already investigate without any solution.. Trying glob 10.3.0 too, but I've the same problem.

I don't know what to tests and how to try debug this.. But I think I'm facing to an edge case..

**Comment by isaacs** [comment]
Ah, ok. I'm not familiar with how gulp is using glob, but since it works fine using glob directly, I think the problem can be narrowed down to gulp's usage.

Have you posted an issue on gulp? If it claims to work with glob 9.0.0, but in fact doesn't, then that seems like a bug to me.

The code you posted seems to use glob directly, but when I run that code on a Linux system, I see the expected results. Can you reproduce this using _only_ glob, and not gulp? If not, I think this is likely not a glob bug.

**Comment by popod** [comment]
Sorry, this is my mistake, nothing related to `gulp`.. I want to say `glob`. I've edit my comment.

> The code you posted seems to use glob directly, but when I run that code on a Linux system, I see the expected results. Can you reproduce this using only glob, and not gulp? If not, I think this is likely not a glob bug.

Yes, I can reproduce the problem with only `glob` (works on 8.1.0 and no more with 9.0.0) by only using the exemple script provided.

I will continue to investigate..
