### ISSUE TITLE
Update `path-scurry` dependency version

### ISSUE THREAD

**Issue by HarelM** [isaacs/node-glob#537]
It seems that when updating `@types/node` to version 20.3.1 typescript check on glob fails with the following error message:
```
Error: node_modules/path-scurry/dist/cjs/index.d.ts(115,31): error TS2720: Class 'PathBase' incorrectly implements class 'Dirent'. Did you mean to extend 'Dirent' and inherit its members as a subclass?
  Property 'path' is missing in type 'PathBase' but required in type 'Dirent'.
```

I believe this was already addressed in path-scury but this version is not used here are far as I can tell:
https://github.com/isaacs/node-glob/blob/66bcedf93ce1f0a3f8a99e614ed855be6e1e95b8/package.json#L66

Any chance to update the version to latest and release a new version of glob?

Thanks for all the hard work around this library!

**Comment by isaacs** [comment]
Happy to update it, but I'm on hotel wifi so it'll be a minute.

In the meantime, `npm update path-scurry` should pull in the latest for you, because `1.9.0` is equivalent to `>=1.9.0 <2.0.0-0`.

**Comment by HarelM** [comment]
Thanks for the super-fast response and fix!!
