### ISSUE TITLE
Memory leak detected due to inflight

### ISSUE THREAD

**Issue by karanbht007** [isaacs/node-glob#540]
Hi,

This project is still using inflight as a dependency, which is known to have a memory leak in it: https://github.com/isaacs/inflight/issues/5

Inflight has not been updated since 2016. Would it be possible to remove inflight from this project's dependencies? I can see comment that inflight will be removed in v8 and again in v9 but it's still using it.
Ref- https://github.com/isaacs/node-glob/issues/435#issuecomment-1040540546

**Comment by MohdFarmanTR** [comment]
Hi @isaacs,

As a result of memory leaks in Globe's inflight packages, we are also dealing with a high vulnerability issue.

The most recent version of glob, 10.3.3, still depends on inflight? I've only looked at package.json and package-lock.json, but there aren't any inflight dependencies there.
Please confirm, someone. @isaacs

**Comment by isaacs** [comment]
The `inflight` module is only used in development dependencies.  It's used by tap, c8, and a few others.  It hasn't been used by glob since the publication of version 8.0.0, on 2022-04-11T17:25:05.849Z.

**Comment by rm0123** [comment]
> The `inflight` module is only used in development dependencies. It's used by tap, c8, and a few others. It hasn't been used by glob since the publication of version 8.0.0, on 2022-04-11T17:25:05.849Z.

Hello, Maybe I missed something but I got the glob module version 8.1.0 (>=8.0.0) and I noticed that the inflight module is used and installed in production, as you see below :

in the package.json
`"dependencies": { "fs.realpath": "^1.0.0", "inflight": "^1.0.4", "inherits": "2", "minimatch": "^5.0.1", "once": "^1.3.0" }`
 

in the package-lock.json
`  "inflight": { "version": "1.0.6", "resolved": "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz", "integrity": "sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=", "requires": { "once": "^1.3.0", "wrappy": "1" } },
`
 
Thanks by advance
