### ISSUE TITLE
Problem glob 7.1.3 => 10.3.3

### ISSUE THREAD

**Issue by TheHellTower** [isaacs/node-glob#541]
Hello,

In [this](https://github.com/TheHellTower/Discord-Bot-List/blob/master/src/bot/Utils.js) file I'm using glob, I got dependabot telling me that I was able to update to the last version(10.3.3 when I write this message) so I tried but I got a error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received an instance of Object
```
Because of pomisify, however I tried to do `require("glob").glob` to access it but it for some reasons doesn't work anymore but don't crash too.

Do you have any idea ?

Best Regards,
TheHellTower.

**Comment by TheHellTower** [comment]
Ref: https://github.com/TheHellTower/Discord-Bot-List/pull/72

**Comment by isaacs** [comment]
You don't have to promisify it. Glob returns a promise now.

**Comment by TheHellTower** [comment]
> You don't have to promisify it. Glob returns a promise now.

Even without promisify I still can't get what I want
![Code_GZMjvyt3ob](https://github.com/isaacs/node-glob/assets/119943599/1e8454b6-e448-48e9-a2c6-4396e76fd4ad)
![Code_mhnlW5JC1X](https://github.com/isaacs/node-glob/assets/119943599/36a145f8-093b-48dc-8da5-828b0dac744b)

**Comment by isaacs** [comment]
I can't read screenshots, sorry. Please provide some example code as text.

**Comment by TheHellTower** [comment]
> I can't read screenshots, sorry. Please provide some example code as text.

Sorry, like I said the code is from the following code: https://github.com/TheHellTower/Discord-Bot-List/blob/master/src/bot/Utils.js

Just updated like this:
```js
/////
//const glob = promisify(require("glob"));
const {glob} = require("glob");
/////

console.log(glob(`${this.directory}bot/commands/**/*.js`, { ignore: "node_modules/**" }).matches)
return glob(`${this.directory}bot/commands/**/*.js`, { ignore: "node_modules/**" }).then((commands) => {
console.log(commands)
/////
```

But none give me a array with my files.

**Comment by isaacs** [comment]
Is this running on Windows? Glob patterns cannot use `\` as a path separator. You might try `glob(pattern, { cwd: this.directory })` if so.

**Comment by TheHellTower** [comment]
> glob(pattern, { cwd: this.directory })

```js
return console.log(glob(`bot/commands/**/*.js`, { cwd: this.directory }))
```
A part of the logged result
```JS
minimatch: Minimatch {
    options: {
      cwd: 'C:\\Users\\TheHellTower_THT\\Desktop\\Development\\GitHub\\Projects\\Discord-Bot-List\\src\\',
      nonegate: true,
      nocomment: true,
      allowWindowsEscape: false
    },
    set: [ [Array] ],
    pattern: 'bot/commands/**/*.js',
    regexp: null,
    negate: false,
    comment: false,
    empty: false,
    partial: false,
    globSet: [ 'bot/commands/**/*.js' ],
    globParts: [ [Array] ]
  },
  options: {
    cwd: 'C:\\Users\\TheHellTower_THT\\Desktop\\Development\\GitHub\\Projects\\Discord-Bot-List\\src\\',
    nonegate: true,
    nocomment: true,
    allowWindowsEscape: false
  }
```

Still getting: `matches: [ <1 empty item> ]`

**Comment by TheHellTower** [comment]
Solved !
```js
return glob.sync(`${this.directory}bot/commands/**/*.js`).map(commandFile => {
...
})
```
Thanks !
