### ISSUE TITLE
Unsafe Glob library because of inflight memory leak vulnerability

### ISSUE THREAD

**Issue by rm0123** [isaacs/node-glob#545]
Hi, I use glob version [v8.1.0](https://github.com/isaacs/node-glob/releases/tag/v8.1.0). but a vulnerability is raised regarding the last inflight module version (v1.0.6), all versions are impacted). The vulnerability concerns memory leaks. Using an alternative as fast-glob does, Glob could be work fine without memory leak issue making Glob library safe. Is the glob patched version is plan ?

` 
"dependencies": {
    "fs.realpath": "^1.0.0",
    "inflight": "^1.0.4",
    "inherits": "2",
    "minimatch": "^5.0.1",
    "once": "^1.3.0"
  }
`

Thanks & Regards.

**Comment by isaacs** [comment]
The current version is 10.3.3, and it does not use inflight.
