### ISSUE TITLE
tilde "c:\progra~1\" doesn't work with windowsPathsNoEscape: true

### ISSUE THREAD

**Issue by anthony-redFox** [isaacs/node-glob#547]
Pattern `c:\progra~1\*.ext` with `windowsPathsNoEscape: true` should works the same as "c:\program files\\*.ext"

**Comment by isaacs** [comment]
Yeah, what's happening there is that it's reading the `c:\` directory, and finding `['Program Files']`, but testing against the `progra~1` doesn't find anything.

What it really should do, which would also have the benefit of being faster in the vast majority of cases, is concatenate all non-magic string portions of the pattern, and just readdir at that first location. Then it'd call `readdir` on `c:\progra~1` in this case, which does return the results expected. Of course, it means you'll get results like `c:\progra~1\Whatever`, but I assume that's probably fine, yes?

**Comment by isaacs** [comment]
Didn't impact perf to any significant degree that I could determine from the benchmarks, even trying to hand it a benchmark that would benefit as much as possible from the shortcut. I guess readdir is just pretty fast 😅 

But fixed on 10.3.4.
