### ISSUE TITLE
glob pattern works in PowerShell, but not inside of package.json script

### ISSUE THREAD

**Issue by trusktr** [isaacs/node-glob#549]
I can run this successfully in Windows PowerShell:

```
npx rimraf './foo/**/!(*.gitkeep)'
```

and it leaves behind .gitkeep files, but deletes everything else.

When I put it inside of a package.json script, to run it with npm,

```js
{
  "scripts": {
    "clean": "rimraf './foo/**/!(*.gitkeep)'"
  }
}
```

and then in PowerShell run `npm run clean`, it doesn't work, nothing gets deleted inside of `./foo`.

Any ideas?

**Comment by trusktr** [comment]
Changing it to this worked:

```js
{
  "scripts": {
    "clean": "rimraf \"./foo/**/!(*.gitkeep)\""
  }
}
```

Maybe this has to do with npm in Windows executing with CMD, not PowerShell. Not related to glob.

**Comment by isaacs** [comment]
> Maybe this has to do with npm in Windows executing with CMD, not PowerShell.

☝️ that.
