### ISSUE TITLE
Use node: protocol in imports?

### ISSUE THREAD

**Issue by ebadervolvo** [isaacs/node-glob#550]
## Description
I'm facing a Storybook build issue with the following error:
```
export 'fileURLToPath' (imported as 'fileURLToPath') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)
```
I think it is related to https://github.com/isaacs/node-glob/blob/main/src/glob.ts#L11 where some hoisting issue with conflicting url packages casuses this.

I wonder if this would be solved by using the `node:` protocol when importing Node built-ins?
```
import { fileURLToPath } from 'node:url'
```
ref: https://nodejs.org/api/esm.html#node-imports

## Version
glob: 10.3.4

**Comment by isaacs** [comment]
This seems like a storybook issue. I think we removed the `node:` prefixes because it broke on one of the versions supported here. But `url` is a built in module, so it should behave the same either way.
