### ISSUE TITLE
return type of glob withFileTypes is not exported

### ISSUE THREAD

**Issue by boneskull** [isaacs/node-glob#551]
Calling `glob(x, {withFileTypes: true})` resolves with a `Path[]`, but `Path` is not exported from `glob`; that means if a consumer needs the type, e.g.:

```ts
let paths: Path[];
try {
  paths = await glob('*', {withFileTypes: true});
} catch {
  // ...
}
```

...they cannot get the `Path` type unless they either a) assume that `path-scurry` will always be resolvable since `glob` is, or b) add `path-scurry` as a direct dependency, or c):

```ts
// dude
let paths: Exclude<Awaited<ReturnType<typeof glob>>, string[]>;
```

Suggestion: `export type {Path}` somewhere in `src/index.ts`.  I can send a PR if you wish.

ty

**Comment by isaacs** [comment]
Ah, yeah, it should probably just re-export all the types from `path-scurry`, cuz why not.

PR welcome :)

**Comment by isaacs** [comment]
```
// dude
```

😂
