### ISSUE TITLE
childrenIgnored wrong return?

### ISSUE THREAD

**Issue by pilaoda** [isaacs/node-glob#552]
https://github.com/isaacs/node-glob/blob/ed22c06c060a89f02b30d996c0eec032b1781962/src/ignore.ts#L109-L111
Maybe I misunderstanding the purpose here, shouldn't this block `return` true rather single true?

**Comment by pilaoda** [comment]
I run into a problem that the ignore option didn't ignore a infinite symlink directory and iterate its infinite files, I think the problem is this code doesn't work expected.

**Comment by isaacs** [comment]
Omg, yes, that is obviously a bug, good spot.

What's funny is that it actually still works, assuming the path isn't an ELOOP, just _way slower_ because it iterates over every file.
