### ISSUE TITLE
Is `README.md` not updated?

### ISSUE THREAD

**Issue by garysassano** [isaacs/node-glob#554]
From the `README.md`:
```
import { glob, globSync, globStream, globStreamSync, Glob } from 'glob'
```
But the only things I'm able to import are:
```
import { glob, Glob, GlobSync } from 'glob'
```
It looks like `globSync()`, `globIterate()`, `globIterateSync()`, `globStream()`, `globStreamSync()` don't exist.

Thus this example doesn't work for me:
```
const imagesAlt = globSync('{css,public}/*.{png,jpeg}')
```
But I am able to do this instead:
```
const imagesAlt = glob.sync('{css,public}/*.{png,jpeg}')
```

**Comment by isaacs** [comment]
What does `npm ls glob` say? Is it v10?

**Comment by garysassano** [comment]
Now that you mention it, I've noticed that pnpm installed glob v8.1.0, but why?

**Comment by isaacs** [comment]
Couldn't say. If you were using npm, then you could do `npm why glob@8`, might still work on a pnpm tree.
