### ISSUE TITLE
throw '"glob"' has no exported member named 'globSync'. Did you mean 'GlobSync' in 10.3.7

### ISSUE THREAD

**Issue by kiner-tang** [isaacs/node-glob#555]
![image](https://github.com/isaacs/node-glob/assets/10286961/576da5c8-23a2-45dd-92a1-477014154b36)

**Comment by cpojer** [comment]
Can confirm, simply using `10.3.7` and using `import { globSync } from 'glob';` causes this error. Downgrading to `10.3.6` resolves the issue.

Repro: https://codesandbox.io/p/sandbox/npm-playground-forked-ch2hmh?file=%2Findex.ts%3A3%2C7

**Comment by kiner-tang** [comment]
> Can confirm, simply using `10.3.7` and using `import { globSync } from 'glob';` causes this error. Downgrading to `10.3.6` resolves the issue.
> 
> Repro: https://codesandbox.io/p/sandbox/npm-playground-forked-ch2hmh?file=%2Findex.ts%3A3%2C7

Yes, I lock the glob version to `10.3.6` to solve this issue now. Hope to solve this problem soon!

**Comment by colinrotherham** [comment]
TypeScript won't enable [`resolvePackageJsonExports`](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports) by default, but can help for now https://github.com/isaacs/node-glob/issues/556#issuecomment-1733508381

**Comment by isaacs** [comment]
I'll add the `types` field back in, but you _really_ need to start doing `"module": "node16"` or `"module": "nodeNext"` in your tsconfigs, or you're almost certainly getting subtly wrong types any time you import a hybrid module, especially if you are building commonjs.

If you have that option enabled, but are still seeing these warnings, make sure that the module emitting the warning is covered by the tsconfig in question (ie, included in `files` or `include`, and not excluded by `exclude` options).

**Comment by isaacs** [comment]
Ah, actually, no, that leads to incorrect types being exported for the commonjs build, which is why tshy enforces that top level `types` remain unset.

Enable [resolvePackageJsonExports](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports), that is the correct way to address this.
