### ISSUE TITLE
Module '"glob'" has no exported member 'GlobOptionsWithFileTypesUnset' in 10.3.7

### ISSUE THREAD

**Issue by d-ellis** [isaacs/node-glob#556]
![image](https://github.com/isaacs/node-glob/assets/62145437/45f3fd86-8b9e-4945-a6c5-40a43dca4662)

Repro: https://codesandbox.io/p/sandbox/npm-playground-forked-wzlncl?file=%2Findex.ts%3A2%2C1

Works in 10.3.6, but not anymore in 10.3.7

**Comment by d-ellis** [comment]
Did some more digging. The issue seems to be because when using 10.3.6, the types are imported from `./node_modules/glob/dist/mjs/index.d.ts`, whilst in 10.3.7 the types are coming from `./node_modules/@types/glob/index.d.ts`
Looks like the types are now included in `./node_modules/glob/dist/esm/index.d.ts` but they aren't being automatically used when importing from glob

**Comment by colinrotherham** [comment]
Commit https://github.com/isaacs/node-glob/commit/b7d7667df0698b0e2c5589319b2b9b801eae35c0 removes the default exports in favour of package exports only:

```patch
-  "main": "./dist/cjs/src/index.js",
-  "module": "./dist/mjs/index.js",
-  "types": "./dist/mjs/index.d.ts",
```

TypeScript won't doesn't enable [`resolvePackageJsonExports`](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports) by default:

>`true` when [moduleResolution](https://www.typescriptlang.org/docs/handbook/compiler-options.html#moduleResolution) is `node16`, `nodenext`, or `bundler`; otherwise `false`

@d-ellis Hopefully this is something you can enable for now?

Ideally both top-level exports and package exports will be needed for compatibility. There's a similar issue with ESLint plugins not using package exports too https://github.com/isaacs/node-glob/issues/557#issuecomment-1733497303

**Comment by isaacs** [comment]
dupe https://github.com/isaacs/node-glob/issues/555

**Comment by isaacs** [comment]
Enable [resolvePackageJsonExports](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports)
