### ISSUE TITLE
Typescript: Cannot find type declarations

### ISSUE THREAD

**Issue by cexbrayat** [isaacs/node-glob#560]
Similar to what happened https://github.com/isaacs/rimraf/issues/290 , I think that the commit introducing `tshy` broke the typings in `node-glob`.

With v10.3.7+:

```
(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module 'glob' or its corresponding type declarations.
src/utils.ts: (6:22)

6 import { glob } from 'glob';
```

Rolling back to v10.3.6 works fine

**Comment by adelsz** [comment]
This is breaking the build for us too

**Comment by isaacs** [comment]
Duplicate https://github.com/isaacs/node-glob/issues/557

You need to enable `resolvePackageJsonExports` in tsconfig. The easiest way to do this is to set `module` and `moduleResolution` to `"node16"` or `"nodeNext"`, but you can also set `"resolvePackageJsonExports": true`.
