### ISSUE TITLE
Cannot find module 'glob' or its corresponding type declarations

### ISSUE THREAD

**Issue by joshkolenko** [isaacs/node-glob#561]
Getting this error in a project I've been working on. Seems to be caused by the removal of the `main`, `module` & `types` properties in `package.json` in version `10.3.7`. Adding those properties back to `package.json` fixed the issue for me.

For clarity sake, here's my `tsconfig.json`. Changing `moduleResolution` to `NodeNext` fixed this specific issue but caused more issues in my project with other dependencies.

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "target": "ESNext",
    "strict": true,
    "paths": {
      "@scripts/*": ["./scripts/*"]
    }
  },
  "include": ["lib/types", "lib/types/**/*"]
}
```

**Comment by isaacs** [comment]
Please see: https://github.com/isaacs/node-glob/issues/557

Set up your tsconfig properly. 

Going to leave this one open so that hopefully others see the link and stop posting this duplicate.
