### ISSUE TITLE
add a flag like `--ignore-path` similar to Prettier

### ISSUE THREAD

**Issue by jcbhmr** [isaacs/node-glob#562]
this is (right now) an idea specific to the cli.

```sh
# in a c/wasm project
glob -c"clang-format -i" "**/*.c" --ignore-path=.gitignore
```
👆 something like this to avoid `clang-format`-ing all the `build/_deps/some-lib/src/thing.c` from CMake deps would be very nice. 👈 that's just _my_ use-case but i can imagine some others:
- run some js analyzer that takes _file arguments_ (not globs) on all **non-dist** js files
- run `glob -c"node --test" "**/*.test.js"` **without** globbing dist
- probably other tools i dont know about

right now I'm using this wrapper `glob.js` script

<details>

```js
#!/usr/bin/env node
import { readFile } from "node:fs/promises";
import { spawn } from "node:child_process";

function ignoreToGlob(ignoreText) {
  return ignoreText
    .split(/\r?\n/g)
    .map((x) => x.trim())
    .filter((x) => x && !x.startsWith("#"))
    .map((x) => {
      if (x.startsWith("!")) {
        if (x.startsWith("!/")) {
          return x;
        } else {
          return `!**/${x.slice(1)}`;
        }
      } else {
        if (x.startsWith("/")) {
          return x;
        } else {
          return `**/${x}`;
        }
      }
    })
    .flatMap((x) => {
      if (x.endsWith("/")) {
        return `${x}**`;
      } else {
        return [x, `${x}/**`];
      }
    });
}

const index = process.argv.indexOf("--ignore-file");
if (index !== -1) {
  const [, ignorePath] = process.argv.splice(index, 2);
  const ignoreText = await readFile(ignorePath, "utf8");
  const ignoreGlobs = ignoreToGlob(ignoreText);
  const extraArgv = ignoreGlobs.flatMap((x) => ["-i", x]);
  process.argv.push(...extraArgv);
}

const child = spawn("npx", ["glob", ...process.argv.slice(2)], {
  stdio: "inherit",
});
child.on("exit", process.exit);
```

</details>

it would be nice if this feature were available included with the cli, but i understand if its out of scope.  this just a friendly feature request 😊

**Comment by isaacs** [comment]
I can see how it'd be useful. Unfortunately, just having a cli script at all is pretty controversial, and past experience with npm has taught me that properly handling `.gitignore` "just like git does" is much less straightforward than one might expect. Your wrapper works fine for your use case, but once something like that is there, people start to expect it to properly handle absolute paths (which are mounted on the folder of the `.gitignore` file, not on the root of the fs as they are in this script), nested `.gitignore` files it finds, negated ignores within ignored folders (which aren't actually supported by glob ignores currently), and so on.

So I think yes, it is out of scope.
