### ISSUE TITLE
Recent bump of `jackspeak` dep should have been a major version bump

### ISSUE THREAD

**Issue by zac-jacobson** [isaacs/node-glob#566]
Recent bump of `jackspeak` dep includes a transition from `cliui` to `@isaacs/cliui`, and that is a breaking change for my non-ESM electron project. This should've been a bump in major version number.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module ./node_modules/string-width/index.js from ./node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in ./node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
```

**Comment by OleksandrKucherenko** [comment]
WTF?! this is not the right way to solve the problem that you introduce. Which version is the latest and compatible with CJS?

**Comment by OleksandrKucherenko** [comment]
I see, version 7.2.3 is the last that works well for me.

All newer versions raise esm error with string-width, ansi-*, etc...

Json-server, mocks-server, concurrently - failed after that, they expect string-width in cjs format.

**Comment by OleksandrKucherenko** [comment]
```diff
webpack.config@1.0.0-alpha /Users/o.kucherenko2/workspace/githubs/webpack.config
├─┬ concurrently@8.2.2
│ └─┬ yargs@17.7.2
│   ├─┬ cliui@8.0.1
│   │ ├── string-width@4.2.3 deduped
│   │ └─┬ wrap-ansi@7.0.0
│   │   └── string-width@4.2.3 deduped
│   └── string-width@4.2.3
└─┬ glob@10.3.10
  └─┬ jackspeak@2.3.6
    └─┬ @isaacs/cliui@8.0.2
      ├── string-width@5.1.2
      ├─┬ wrap-ansi-cjs@npm:wrap-ansi@7.0.0
      │ └── string-width@4.2.3 deduped
      └─┬ wrap-ansi@8.1.0
+       └── string-width@5.1.2
```

**Comment by isaacs** [comment]
@OleksandrKucherenko What package manager are you using?

**Comment by OleksandrKucherenko** [comment]
Yarn 1.xx, and i do not have a chance to upgrade it to latest (enterprise monorepo)

**Comment by isaacs** [comment]
Well, like I said, it's a yarn v1 bug. The feature is quite old, no idea why yarn still doesn't support it. I recommend using a package manager that doesn't have this bug, such as npm or pnpm.
