### ISSUE TITLE
Memory leak in inflight dependency

### ISSUE THREAD

**Issue by LakshmiPhani7680** [isaacs/node-glob#573]
Hi,
I have inflight package still in version 10.0.2, the problem is if i remove this inflight package i am not able to use the npm commands so is there anyway to resolve this issue? and is there anyway to resolve this issue in 8.x versions of npm also? please respond as it was one of the main vulnerability in npm package.

**Comment by isaacs** [comment]
Run `npm ls glob inflight` and `npm why inflight` and share the output, please. Glob 10 does not use inflight.

**Comment by davidguilherme** [comment]
@isaacs loads of package still use glob v8 or less. From v9 the API changed from callbacks to promises, I think it would be reasonable to patch v8 so people can easily upgrade to (or even use overrides/resolution in the package.json). What do you think?

**Comment by frontzhm** [comment]
我看邮件的反应很迟钝。。。如果有事发短信提醒我看邮件。。。。。。

**Comment by isaacs** [comment]
I disagree. I'm not going to touch ancient versions of things. Fork it and patch if you want to do extra work to avoid upgrading, or override with a patched version of inflight. Not my job, sorry.
