### ISSUE TITLE
Using vulnerable package inflight

### ISSUE THREAD

**Issue by albin-joseph** [isaacs/node-glob#574]
I am using `glob` package in my project. I scanned the source code with `snyk`. I got a medium vulnerability _Missing Release of Resource after Effective Lifetime_. It's due to one of the dependencies of glob package named `inflight`. When I checked, I observed that this package is not updated for the last 7 years. Please find the detailed report https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116, https://cwe.mitre.org/data/definitions/772.html.

**Comment by isaacs** [comment]
https://github.com/isaacs/node-glob/issues/573
