### ISSUE TITLE
`glob.sync(...)` is not returning values when `".."` and `nocase: true` are used together.

### ISSUE THREAD

**Issue by josh08h** [isaacs/node-glob#575]
**Versions:**
Glob version: 10.3.10
System: MacOS 12.5 darwin

**Issue**
`glob.sync(...)` is not returning values when `".."` is used in the path unless `nocase: false` is set.

```
const glob = require("glob");
const path = require("path");

console.log(glob.sync("*", { nocase: true }).length)
// 17
console.log(glob.sync("*", { nocase: false }).length)
// 17

console.log(glob.sync("../*", { nocase: true }).length)
// 0
console.log(glob.sync("../*", { nocase: false }).length)
// 15
```

Am I missing something obvious here?

**Comment by frontzhm** [comment]
我看邮件的反应很迟钝。。。如果有事发短信提醒我看邮件。。。。。。

**Comment by josh08h** [comment]
We were pinning `minimatch` to `3.x` via `resolutions` which caused the breakage.
