### ISSUE TITLE
results are in reverse alphabetical order

### ISSUE THREAD

**Issue by mmkal** [isaacs/node-glob#576]
Hi! It seems in v10, results are in reverse alphabetical order.

Repro: go to https://npm.runkit.com/glob and paste in:

```js
var glob = require("glob")
var path = require('path')

console.log(glob.globSync('*/*.*', { cwd: path.join(__dirname, '..') }))
```

This was not the case in glob v8. Not sure about 9.

**Comment by isaacs** [comment]
They're not sorted at all, and the order is non deterministic, set by os latency. Do not depend on it.

**Comment by mmkal** [comment]
That's good to know! They do seem to consistently be in reverse order though, for the cases I've tried. Do you think there's something that got changed recently that caused that? I'll make sure to add a `.sort()` wherever I'm accidentally depending on it, but I imagine there are others who will find the reverse order unexpected and might hit issues.

Failing that, would you accept a docs update pull request?

**Comment by 1j01** [comment]
Version 9 removed sorting. To sort results [just as version 8 did](https://github.com/isaacs/node-glob/blob/v8.1.0/common.js#L20), use:
```js
glob.sync(...).sort((a, b)=> a.localeCompare(b, 'en'))
```

**Comment by isaacs** [comment]
> They do seem to consistently be in reverse order though, for the cases I've tried.

That is 100% a result of how your computer's file system chooses to return results. On a different operating system, file system, disk controller, ..., it could easily be returned in alphabetical order, in order of last access, entirely random, or any other arbitrary order.

Sort if you depend on it, don't depend on it if you're not sorting it yourself.

**Comment by isaacs** [comment]
And yes, doc patch welcome 🤗

**Comment by 75lb** [comment]
> Version 9 removed sorting. To sort results [just as version 8 did](https://github.com/isaacs/node-glob/blob/v8.1.0/common.js#L20), use:

thanks for pointing this out.. IMO, it's better we do our own sorting - v8 assumed all users require American English sorting (as you [highlighted](https://github.com/isaacs/node-glob/blob/v8.1.0/common.js#L20)) which results in incorrectly sorted output for non-Americans.. Russians, for example.. 

```
$ node
> 'Р'.localeCompare('С', 'ru')
-1
> 'P'.localeCompare('C', 'en')
1
```
