### ISSUE TITLE
`follow: true` doesn't follow more that 1 symbolic link

### ISSUE THREAD

**Issue by pamelalozano16** [isaacs/node-glob#579]
"_By default, a ** in a pattern will follow 1 symbolic link if it is not the first item in the pattern, or none if it is the first item in the pattern, following the same behavior as Bash._". However, some dependent modules contain multiple nested symbolic links, and the option follow: true only operates for a single level of symlinks.

**dir_foo**
```
foo.txt
```

**dir_bar**
```
foo
```

**dir_baz** 
```
bar
```
In this case 
`glob.sync('dir_baz/**', {follow:true, nodir:true})` returns `foo` instead of `foo.txt`.

**Comment by pamelalozano16** [comment]
@isaacs any thoughts on this? 🤔

**Comment by isaacs** [comment]
Seems to be working as intended to me, no?

```
$ tree
./
├── dir_bar/
│   └── foo -> ../dir_foo/
├── dir_baz/
│   └── bar -> ../dir_bar/
└── dir_foo/
    └── foo.txt

6 directories, 1 file

$ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> require('../').globSync('dir_baz/**', {follow:true})
[
  'dir_baz',
  'dir_baz/bar',
  'dir_baz/bar/foo',
  'dir_baz/bar/foo/foo.txt'
]
> require('../').glob('dir_baz/**', {follow:true}).then(console.log)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 143,
  [Symbol(trigger_async_id_symbol)]: 132
}
> [
  'dir_baz',
  'dir_baz/bar',
  'dir_baz/bar/foo',
  'dir_baz/bar/foo/foo.txt'
]
> require('../').glob('dir_baz/**', {follow:true, nodir:true}).then(console.log)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 257,
  [Symbol(trigger_async_id_symbol)]: 246
}
> [ 'dir_baz/bar', 'dir_baz/bar/foo', 'dir_baz/bar/foo/foo.txt' ]

> require('../').globSync('dir_baz/**', {follow:true, nodir: true})
[ 'dir_baz/bar', 'dir_baz/bar/foo', 'dir_baz/bar/foo/foo.txt' ]
```

**Comment by pamelalozano16** [comment]
In the given example, shouldn't `> require('../').globSync('dir_baz/**', {follow:true, nodir: true})` return 
`[ 'dir_baz/bar/foo/foo.txt' ]` only and not `[ 'dir_baz/bar', 'dir_baz/bar/foo', 'dir_baz/bar/foo/foo.txt' ]`?

I see that [`if (ifDir && this.opts.nodir) return undefined`](https://github.com/isaacs/node-glob/blob/97611cd366e5906a4c58df3f5214af843b0a5e63/src/walker.ts#L187) uses [`.isDirectory()`](https://github.com/isaacs/path-scurry/blob/main/src/index.ts#L699) function from path_scurry, checks if the current `.path`, is a directory. However, when `.path` is a symlink that points to a directory it is not skipped.
The path is still added to `this.matches`, since `ifDir` equals `false`.

**Comment by frontzhm** [comment]
我看邮件的反应很迟钝。。。如果有事发短信提醒我看邮件。。。。。。

**Comment by isaacs** [comment]
@pamelalozano16 Yeah, this is interesting. It's *not* actually a directory, so maybe it should be included. But you've set `follow: true`, so maybe we should be testing the target rather than the entry itself. I'm somewhat torn.

@frontzhm 请在此处的评论中使用英语。

**Comment by nex3** [comment]
+1 for treating symlinks to directories as directories with `follow: true`. I think the expectation when that option is passed is that symlinks become fully transparent representations of whatever they link to as much as possible, and doing otherwise is likely to break users who aren't thinking carefully about edge cases. This also matches the behavior of earlier versions of `glob`, and so is less likely to cause breakages for users upgrading.

**Comment by isaacs** [comment]
@nex3 Yeah, I've noodled on it more since posting that comment earlier today, and I think you're right. `follow:true` should be "symlinks are treated as their targets in every way", not "follow symlinks, but still treat them differently than directories".

**Comment by isaacs** [comment]
Will publish once CI says it's ok
