### ISSUE TITLE
Glob behaves differently when handed a drive letter root as its directory (Windows)

### ISSUE THREAD

**Issue by cbartondock** [isaacs/node-glob#583]
Output of `glob(finalGlob, { dot: true, cwd: directory, follow: true })` is `globfiles`:

![image](https://github.com/isaacs/node-glob/assets/4482454/5f9ade78-3587-4c9c-9054-1e6f79f1c4a1)

Notice that for the case where directory is not the root of the drive, the drive letter is not included (the correct behavior since absolute is not set) whereas for the case where directory is `D:\` the files start with `D:\\`.

**Comment by frontzhm** [comment]
我看邮件的反应很迟钝。。。如果有事发短信提醒我看邮件。。。。。。

**Comment by isaacs** [comment]
I can't read screenshots very easily. Can you post the JavaScript you're running and copy the terminal output as plain text?

**Comment by isaacs** [comment]
Is this the same as #584?
