### ISSUE TITLE
Update to path-scurry and glob broke npm temporarily

### ISSUE THREAD

**Issue by justin-masse** [isaacs/node-glob#585]
This is working now, but there was an issue for a little while when installing `node-gyp` which uses `glob` as a dependency @ ^10.3.0:

<img width="939" alt="Screenshot 2024-05-09 at 10 26 15" src="https://github.com/isaacs/node-glob/assets/6918754/6cf56bda-2bef-474b-bf23-3db4f6a92ca5">

Temporarily glob could not find `path-scurry^1.11.0` which was causing our CI to break when installing node-gyp

**Comment by justin-masse** [comment]
I'm curious, was the new version of `glob` just released before the new version of path-scurry? I don't know how that would be possible based on teh package-lock in that repo... or was this version published too quickly while `path-scurry` was still propagating to npm servers/etc?

**Comment by isaacs** [comment]
Sometimes "eventual consistency" is a little more "eventual" than we'd like.

I definitely published path-scurry first, but when they're within minutes of each other, I've seen that happen before. It's rare, but rare thing * millions of people installing millions of packages = daily occurrence.

**Comment by isaacs** [comment]
There's also your local `~/.npm` cache to consider. Say you fetch glob and then 2 minutes later fetch path-scurry. Then 3 minutes later (the glob cache has expired) you try to fetch both. `path-scurry` is still cached, but glob revalidates, and so you apparently get the later thing before the earlier thing.

Gets complicated. 🤷
