### ISSUE TITLE
Question: fix for types issue re: shelljs reference to glob types

### ISSUE THREAD

**Issue by jpshack-at-palomar** [isaacs/node-glob#590]
I read an [answer from iasaacs](https://stackoverflow.com/questions/75890950) in stackoverflow to the issue about the error below being corrected by upgrading to latest glob and removing dependencies. I am encountering this as transitive dependency in shelljs also reported at https://github.com/shelljs/shelljs/issues/1148. Would you confirm or deny [my comment](https://github.com/shelljs/shelljs/issues/1148#issuecomment-2182499022) re: the appropriate approach to sorting this in shelljs so we can get the shelljs issue sorted with its maintaners? Greatly appreciated.

```
node_modules/@types/glob/index.d.ts:29:42 - error TS2694: Namespace '"/opt/workspace/personal/kioskify-backend/functions/node_modules/minimatch/dist/cjs/index"' has no exported member 'IOptions'.

29     interface IOptions extends minimatch.IOptions {
                                            ~~~~~~~~

node_modules/@types/glob/index.d.ts:75:30 - error TS2724: '"/opt/workspace/personal/kioskify-backend/functions/node_modules/minimatch/dist/cjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?

75         minimatch: minimatch.IMinimatch;
                                ~~~~~~~~~~

node_modules/@types/rimraf/index.d.ts:33:21 - error TS2694: Namespace '"/opt/workspace/personal/kioskify-backend/functions/node_modules/glob/dist/mjs/index"' has no exported member 'IOptions'.

33         glob?: glob.IOptions | false | undefined;
                       ~~~~~~~~
```

**Comment by isaacs** [comment]
Confirmed. Remove the DT type defs, and install a version that ships the actual types itself.

`@types/*` packages should never be a production dependency, and should not be used when the project in question ships type definitions itself. It's always just a recipe for weird conflicts and confusion.
