### ISSUE TITLE
Node 14 support broken due to jackspeak dependency

### ISSUE THREAD

**Issue by SeinopSys** [isaacs/node-glob#593]
Trying to execute `npx glob` using Node 14.20.1 results in the following:

```
npx: installed 41 in 2.817s
file:///Users/seinopsys/.npm/_npx/4474/lib/node_modules/glob/node_modules/jackspeak/dist/esm/index.js:496
                cause ??= { name: field, found: value };
                      ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
```

The `??=` operator is only supported from Node version 15.14.0 onwards ([source](https://node.green/#ES2021-features-Logical-Assignment-----basic-support)).

According to the `engines` field in `package.json` node 14.20.1 matches the allowed version range but I do not see any actions validating that it actually works with this version.

I would like to suggest adding validations for all supported Node versions or dropping support for these older versions via removing them from the `engines` constraint if they are no longer actively validated.

**Comment by isaacs** [comment]
If you're using EOL node versions, especially those that have been EOL as long as node 14 has, you must lock dependencies, and carefully review every update, even patch updates. That's what "EOL" means. Of course, it's best to just update to a node version that's actively supported, but that's not always an option.

The glob lib works in 14, it's just the bin that doesn't.
