### ISSUE TITLE
v10.4.0 raised minimum required node version to 18

### ISSUE THREAD

**Issue by connor4312** [isaacs/node-glob#594]
In https://github.com/isaacs/node-glob/commit/ed0d061c5bc6a9f4f05e94e3ba902a4f8649ebdf, a require for `node:url` was added which implicitly raises the Node version above what was previously supported and is still declared [in its engines](https://github.com/isaacs/node-glob/blob/eef7ea35afe511079c5bf83862ed57ece2bbf7fa/package.json#L96). This wasn't detected because Node 16 checks were [removed earlier](https://github.com/isaacs/node-glob/commit/b5d0f640893eba729bb8675a51a73ffbc0760b35).

This is probably worth a changelog entry at minimum

**Comment by isaacs** [comment]
The engines states `">=16 || 14 >=14.18"`.

Node 16.0.0 and 14.18.0 (the lowest versions in each line allowed by the engines range) both support `require("node:url")`.

```
$ node -v
v14.18.0

$ node -p 'require("node:url")'
{
  Url: [Function: Url],
  parse: [Function: urlParse],
  resolve: [Function: urlResolve],
  resolveObject: [Function: urlResolveObject],
  format: [Function: urlFormat],
  URL: [class URL],
  URLSearchParams: [class URLSearchParams],
  domainToASCII: [Function: domainToASCII],
  domainToUnicode: [Function: domainToUnicode],
  pathToFileURL: [Function: pathToFileURL],
  fileURLToPath: [Function: fileURLToPath],
  urlToHttpOptions: [Function: urlToHttpOptions]
}
```

```
$ node -v
v16.0.0

$ node -p 'require("node:url")'
{
  Url: [Function: Url],
  parse: [Function: urlParse],
  resolve: [Function: urlResolve],
  resolveObject: [Function: urlResolveObject],
  format: [Function: urlFormat],
  URL: [class URL],
  URLSearchParams: [class URLSearchParams],
  domainToASCII: [Function: domainToASCII],
  domainToUnicode: [Function: domainToUnicode],
  pathToFileURL: [Function: pathToFileURL],
  fileURLToPath: [Function: fileURLToPath],
  urlToHttpOptions: [Function: urlToHttpOptions]
}
```

So, I'm not sure what problem you're encountering with it, but it's not node version.

Are you running into issues with Jest? I've heard from a lot of people that the `node:...` module ids aren't supported until recently. Try updating that maybe?
