### ISSUE TITLE
upgrade problem

### ISSUE THREAD

**Issue by wghule** [isaacs/node-glob#595]
Please try to be compatible with upgrades as much as possible。the older version please make it avaliable！

**Comment by wghule** [comment]
npm registry：https://www.npmjs.com/package/glob?activeTab=versions

**Comment by isaacs** [comment]
Every version ever published is still available.

**Comment by isaacs** [comment]
They're just deprecated, so you may need to tick the "show deprecated versions" box to see them in that list. But they're there. Just unsupported.
