### ISSUE TITLE
你一更新害死人了

### ISSUE THREAD

**Issue by TryChai** [isaacs/node-glob#597]
![image](https://github.com/isaacs/node-glob/assets/30064871/ba0d4959-a48a-4f04-a977-e76e666934a1)
能不能考虑下 这种不能升级node 版本的小公司 
你一更新 我就发布了版 
能不能考虑考虑

**Comment by isaacs** [comment]
https://nodejs.org/en/blog/announcements/nodejs16-eol/

16 been EOL for 10 months. 14 has been EOL for over a year. Pin your deps and only upgrade carefully if you are using EOL platform versions.
