### ISSUE TITLE
Fix the v10.4.2 - v10.4.4 releases to still support Node 16.19.1

### ISSUE THREAD

**Issue by cdtweb** [isaacs/node-glob#598]
```
error glob@10.4.4: The engine "node" is incompatible with this module. Expected version "14 >=14.21 || 16 >=16.20 || 18 || 20 || >=22". Got "16.19.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

We don't actually include node-glob directly, but it is coming through  @redux-devtools/extension which has `^v10.4.1` -- so maybe we can go and get them to fix it by locking v10.4.1.. but any features you've released since then, security or otherwise, will be lost... 

I see you have introduced v11.0.0, but I still have the issue with the v10.4.x branch by way of this 3rd party package. 

Thanks!

**Comment by TryChai** [comment]
I do think so ,you update maybe a good thing ,but has many user was not got the version , you should show a idea to help us deal with it ,because we are project was uesed in production ,wo do not want to change it by we has many thing to do .

**Comment by BruceAndyLee** [comment]
I guess we should do something like this in our package.json from now on:

```json
"resolutions": {
  "glob": "10.3.3" // which is the version that still supports node below 20
},
```

**Comment by isaacs** [comment]
I pushed a glob 10 release without any engines restriction.

Moving forward, until an npm with proper engines filtering is in widespread use, I'll just bump major and update engines to latest every time I touch anything. People prefer to have more copies of identical code in node_modules, I guess.

**Comment by TryChai** [comment]
Yes, I also like to use new versions of things, but my project doesn't support it, it's hard to support it, and I can't support it, so it's good to just keep the existing one

**Comment by TryChai** [comment]
> I guess we should do something like this in our package.json from now on:
> 
> ```json
> "resolutions": {
>   "glob": "10.3.3" // which is the version that still supports node below 20
> },
> ```
> 
> or, rather
> 
> ```json
> "overrides": {
>   "the-package-that-requested-incompatible-version-of-glob": {
>     "glob": "10.3.3"
>   }
> }
> ```

thanks my friend

**Comment by isaacs** [comment]
@TryChai that is not necessary. Glob v10 doesn't have an engines restriction.

**Comment by TryChai** [comment]
ok, thank you ,thanks for you change ,i has study a day for update node version ,it is pity, fail in end
