### ISSUE TITLE
inflight@1.0.6: This module is not supported, and leaks memory.

### ISSUE THREAD

**Issue by MaxBB-RC** [isaacs/node-glob#605]
Apologies if this isn't the correct way to raise this, but npm is giving the following warning:

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

Can this be addressed at some point?

Thanks

**Comment by isaacs** [comment]
It's been addressed. Just upgrade.

**Comment by Vimiso** [comment]
Is this a breaking change, or can we safely upgrade to the latest version?
