### ISSUE TITLE
(node:40203) ExperimentalWarning: globSync is an experimental feature and might change at any time

### ISSUE THREAD

**Issue by talkohavy** [isaacs/node-glob#606]
## Describe the issue

Hey,
I have installed `glob` v11.0.0, and am using a function called `globSync`.  
When it runs I see this message:

```
(node:40203) ExperimentalWarning: globSync is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

What does it mean? Should I use something else instead? And if not, how do I make this warning go away. It ruins the output of me beautiful CLI tool.

**Comment by isaacs** [comment]
If you're getting this warning, you're not using the globSync function from this library. Share the code, and run with --trace-deprecation as the error suggests.

**Comment by talkohavy** [comment]
Sorry... you are correct.

I didn't even realize there's `globSync` within fs...
Please close this issue.
So embarassing...
