### ISSUE TITLE
Glob eating up 1GB of RAM on a Windows 7 x64 machine?

### ISSUE THREAD

**Issue by gremo** [isaacs/node-glob#66]
Directory `lastfm_test` contains 104212 JSON files. When I try to glob all JSON files:

```javascript
var glob = require('glob');

glob(__dirname + '/lastfm_test/**/*.json', {}, function (err, files) {
    console.log(files.length);
});
```

... the `node.exe` process start eating RAM, until it reaches 1GB and stopping because the scan finished. Sometimes I get a Windows error about no memory left. It seems that RAM consumption grows as the number of files in the folder. Node version is 0.10.5.

Is this considered "normal"?

**Comment by isaacs** [comment]
I suspect that this is no longer an issue, as this module has been heavily refactored and slimmed down since then.  Closing for now, but please do pipe up if it's still a problem in the latest release.

**Comment by danielgindi** [comment]
Still an issue. Globbing a folder with a depth of 1 subfolder, and total of 1.5 million files - takes up 12GB of memory. While it should be about 100MB.
