### ISSUE TITLE
[FEATURE] option to sort by numeric value?

### ISSUE THREAD

**Issue by jokeyrhyme** [isaacs/node-glob#75]
If you have files named:
- 1
- 9
- 10

then the resulting Array of filename will be sorted as:
- 1
- 10
- 9

This is because the sort is based on ASCII character value (I think), and the first character of "10" is "1", which is less than "9".

It would be neat if there was an option to sort based on numeric value, taking into account the actual value of all leading digits together.

**Comment by tunnckoCore** [comment]
omg, and why this should be in the core? lol. In any way you get the result so you can do it what you want. Just pass `nosort` to disable internal sorting.

**Comment by isaacs** [comment]
Yeah, I think it'd be ok to add a feature to let you pass in a JavaScript sort function (of the kind passed to Array.sort), but the default built in sorting will remain as it currently is.

**Comment by isaacs** [comment]
v9 no longer sorts by anything, so it's up to you to sort the results however you see fit.
