### ISSUE TITLE
Better Unicode normalization support

### ISSUE THREAD

**Issue by chcokr** [isaacs/node-glob#94]
Hi,

I suggest a Unicode normalization option be added to the library. I deal with files named in non-ASCII Unicode a lot, and I notice that because of normalization issues (especially on OS X), some files don't get tracked properly. A silly quick workaround is to change the code at line 95 of `glob.js` to the following:

    this.on("end", function (matches) {
        matches = matches.map(function (match) {
            require("unorm");
            return match.normalize();
        });

        cb(null, matches)
    })

Of course this is nothing fundamental (heck, a user can add that part to his callback anyway). Perhaps there could be a more fundamental way of handling the issue! I get a feeling that those not familiar with Unicode normalization could stay frustrated for hours.

Thanks :)

**Comment by isaacs** [comment]
I would accept a patch to do something like this.  If it's expensive in terms of performance then it should be optional.

**Comment by chcokr** [comment]
I find little motivation to do this now, closing.
